
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `agents` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model agents
 * This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info.
 */
export type agentsModel = runtime.Types.Result.DefaultSelection<Prisma.$agentsPayload>

export type AggregateAgents = {
  _count: AgentsCountAggregateOutputType | null
  _avg: AgentsAvgAggregateOutputType | null
  _sum: AgentsSumAggregateOutputType | null
  _min: AgentsMinAggregateOutputType | null
  _max: AgentsMaxAggregateOutputType | null
}

export type AgentsAvgAggregateOutputType = {
  years_experience: number | null
  rating: runtime.Decimal | null
  total_sales: number | null
  total_listings: number | null
}

export type AgentsSumAggregateOutputType = {
  years_experience: number | null
  rating: runtime.Decimal | null
  total_sales: number | null
  total_listings: number | null
}

export type AgentsMinAggregateOutputType = {
  id: string | null
  profile_id: string | null
  license_number: string | null
  agency_name: string | null
  phone: string | null
  verified: boolean | null
  verification_date: Date | null
  years_experience: number | null
  bio: string | null
  photo_url: string | null
  rating: runtime.Decimal | null
  total_sales: number | null
  total_listings: number | null
  created_at: Date | null
  updated_at: Date | null
  whatsapp: string | null
}

export type AgentsMaxAggregateOutputType = {
  id: string | null
  profile_id: string | null
  license_number: string | null
  agency_name: string | null
  phone: string | null
  verified: boolean | null
  verification_date: Date | null
  years_experience: number | null
  bio: string | null
  photo_url: string | null
  rating: runtime.Decimal | null
  total_sales: number | null
  total_listings: number | null
  created_at: Date | null
  updated_at: Date | null
  whatsapp: string | null
}

export type AgentsCountAggregateOutputType = {
  id: number
  profile_id: number
  license_number: number
  agency_name: number
  specialization: number
  phone: number
  verified: number
  verification_date: number
  years_experience: number
  bio: number
  photo_url: number
  rating: number
  total_sales: number
  total_listings: number
  created_at: number
  updated_at: number
  whatsapp: number
  _all: number
}


export type AgentsAvgAggregateInputType = {
  years_experience?: true
  rating?: true
  total_sales?: true
  total_listings?: true
}

export type AgentsSumAggregateInputType = {
  years_experience?: true
  rating?: true
  total_sales?: true
  total_listings?: true
}

export type AgentsMinAggregateInputType = {
  id?: true
  profile_id?: true
  license_number?: true
  agency_name?: true
  phone?: true
  verified?: true
  verification_date?: true
  years_experience?: true
  bio?: true
  photo_url?: true
  rating?: true
  total_sales?: true
  total_listings?: true
  created_at?: true
  updated_at?: true
  whatsapp?: true
}

export type AgentsMaxAggregateInputType = {
  id?: true
  profile_id?: true
  license_number?: true
  agency_name?: true
  phone?: true
  verified?: true
  verification_date?: true
  years_experience?: true
  bio?: true
  photo_url?: true
  rating?: true
  total_sales?: true
  total_listings?: true
  created_at?: true
  updated_at?: true
  whatsapp?: true
}

export type AgentsCountAggregateInputType = {
  id?: true
  profile_id?: true
  license_number?: true
  agency_name?: true
  specialization?: true
  phone?: true
  verified?: true
  verification_date?: true
  years_experience?: true
  bio?: true
  photo_url?: true
  rating?: true
  total_sales?: true
  total_listings?: true
  created_at?: true
  updated_at?: true
  whatsapp?: true
  _all?: true
}

export type AgentsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which agents to aggregate.
   */
  where?: Prisma.agentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of agents to fetch.
   */
  orderBy?: Prisma.agentsOrderByWithRelationInput | Prisma.agentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.agentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` agents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` agents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned agents
  **/
  _count?: true | AgentsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AgentsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AgentsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AgentsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AgentsMaxAggregateInputType
}

export type GetAgentsAggregateType<T extends AgentsAggregateArgs> = {
      [P in keyof T & keyof AggregateAgents]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAgents[P]>
    : Prisma.GetScalarType<T[P], AggregateAgents[P]>
}




export type agentsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.agentsWhereInput
  orderBy?: Prisma.agentsOrderByWithAggregationInput | Prisma.agentsOrderByWithAggregationInput[]
  by: Prisma.AgentsScalarFieldEnum[] | Prisma.AgentsScalarFieldEnum
  having?: Prisma.agentsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AgentsCountAggregateInputType | true
  _avg?: AgentsAvgAggregateInputType
  _sum?: AgentsSumAggregateInputType
  _min?: AgentsMinAggregateInputType
  _max?: AgentsMaxAggregateInputType
}

export type AgentsGroupByOutputType = {
  id: string
  profile_id: string
  license_number: string
  agency_name: string | null
  specialization: string[]
  phone: string | null
  verified: boolean | null
  verification_date: Date | null
  years_experience: number | null
  bio: string | null
  photo_url: string | null
  rating: runtime.Decimal | null
  total_sales: number | null
  total_listings: number | null
  created_at: Date | null
  updated_at: Date | null
  whatsapp: string | null
  _count: AgentsCountAggregateOutputType | null
  _avg: AgentsAvgAggregateOutputType | null
  _sum: AgentsSumAggregateOutputType | null
  _min: AgentsMinAggregateOutputType | null
  _max: AgentsMaxAggregateOutputType | null
}

type GetAgentsGroupByPayload<T extends agentsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AgentsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AgentsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AgentsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AgentsGroupByOutputType[P]>
      }
    >
  >



export type agentsWhereInput = {
  AND?: Prisma.agentsWhereInput | Prisma.agentsWhereInput[]
  OR?: Prisma.agentsWhereInput[]
  NOT?: Prisma.agentsWhereInput | Prisma.agentsWhereInput[]
  id?: Prisma.UuidFilter<"agents"> | string
  profile_id?: Prisma.UuidFilter<"agents"> | string
  license_number?: Prisma.StringFilter<"agents"> | string
  agency_name?: Prisma.StringNullableFilter<"agents"> | string | null
  specialization?: Prisma.StringNullableListFilter<"agents">
  phone?: Prisma.StringNullableFilter<"agents"> | string | null
  verified?: Prisma.BoolNullableFilter<"agents"> | boolean | null
  verification_date?: Prisma.DateTimeNullableFilter<"agents"> | Date | string | null
  years_experience?: Prisma.IntNullableFilter<"agents"> | number | null
  bio?: Prisma.StringNullableFilter<"agents"> | string | null
  photo_url?: Prisma.StringNullableFilter<"agents"> | string | null
  rating?: Prisma.DecimalNullableFilter<"agents"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_sales?: Prisma.IntNullableFilter<"agents"> | number | null
  total_listings?: Prisma.IntNullableFilter<"agents"> | number | null
  created_at?: Prisma.DateTimeNullableFilter<"agents"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"agents"> | Date | string | null
  whatsapp?: Prisma.StringNullableFilter<"agents"> | string | null
  profiles?: Prisma.XOR<Prisma.ProfilesScalarRelationFilter, Prisma.profilesWhereInput>
  properties?: Prisma.PropertiesListRelationFilter
}

export type agentsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  profile_id?: Prisma.SortOrder
  license_number?: Prisma.SortOrder
  agency_name?: Prisma.SortOrderInput | Prisma.SortOrder
  specialization?: Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  verified?: Prisma.SortOrderInput | Prisma.SortOrder
  verification_date?: Prisma.SortOrderInput | Prisma.SortOrder
  years_experience?: Prisma.SortOrderInput | Prisma.SortOrder
  bio?: Prisma.SortOrderInput | Prisma.SortOrder
  photo_url?: Prisma.SortOrderInput | Prisma.SortOrder
  rating?: Prisma.SortOrderInput | Prisma.SortOrder
  total_sales?: Prisma.SortOrderInput | Prisma.SortOrder
  total_listings?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  whatsapp?: Prisma.SortOrderInput | Prisma.SortOrder
  profiles?: Prisma.profilesOrderByWithRelationInput
  properties?: Prisma.propertiesOrderByRelationAggregateInput
}

export type agentsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  profile_id?: string
  license_number?: string
  AND?: Prisma.agentsWhereInput | Prisma.agentsWhereInput[]
  OR?: Prisma.agentsWhereInput[]
  NOT?: Prisma.agentsWhereInput | Prisma.agentsWhereInput[]
  agency_name?: Prisma.StringNullableFilter<"agents"> | string | null
  specialization?: Prisma.StringNullableListFilter<"agents">
  phone?: Prisma.StringNullableFilter<"agents"> | string | null
  verified?: Prisma.BoolNullableFilter<"agents"> | boolean | null
  verification_date?: Prisma.DateTimeNullableFilter<"agents"> | Date | string | null
  years_experience?: Prisma.IntNullableFilter<"agents"> | number | null
  bio?: Prisma.StringNullableFilter<"agents"> | string | null
  photo_url?: Prisma.StringNullableFilter<"agents"> | string | null
  rating?: Prisma.DecimalNullableFilter<"agents"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_sales?: Prisma.IntNullableFilter<"agents"> | number | null
  total_listings?: Prisma.IntNullableFilter<"agents"> | number | null
  created_at?: Prisma.DateTimeNullableFilter<"agents"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"agents"> | Date | string | null
  whatsapp?: Prisma.StringNullableFilter<"agents"> | string | null
  profiles?: Prisma.XOR<Prisma.ProfilesScalarRelationFilter, Prisma.profilesWhereInput>
  properties?: Prisma.PropertiesListRelationFilter
}, "id" | "profile_id" | "license_number">

export type agentsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  profile_id?: Prisma.SortOrder
  license_number?: Prisma.SortOrder
  agency_name?: Prisma.SortOrderInput | Prisma.SortOrder
  specialization?: Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  verified?: Prisma.SortOrderInput | Prisma.SortOrder
  verification_date?: Prisma.SortOrderInput | Prisma.SortOrder
  years_experience?: Prisma.SortOrderInput | Prisma.SortOrder
  bio?: Prisma.SortOrderInput | Prisma.SortOrder
  photo_url?: Prisma.SortOrderInput | Prisma.SortOrder
  rating?: Prisma.SortOrderInput | Prisma.SortOrder
  total_sales?: Prisma.SortOrderInput | Prisma.SortOrder
  total_listings?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  whatsapp?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.agentsCountOrderByAggregateInput
  _avg?: Prisma.agentsAvgOrderByAggregateInput
  _max?: Prisma.agentsMaxOrderByAggregateInput
  _min?: Prisma.agentsMinOrderByAggregateInput
  _sum?: Prisma.agentsSumOrderByAggregateInput
}

export type agentsScalarWhereWithAggregatesInput = {
  AND?: Prisma.agentsScalarWhereWithAggregatesInput | Prisma.agentsScalarWhereWithAggregatesInput[]
  OR?: Prisma.agentsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.agentsScalarWhereWithAggregatesInput | Prisma.agentsScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"agents"> | string
  profile_id?: Prisma.UuidWithAggregatesFilter<"agents"> | string
  license_number?: Prisma.StringWithAggregatesFilter<"agents"> | string
  agency_name?: Prisma.StringNullableWithAggregatesFilter<"agents"> | string | null
  specialization?: Prisma.StringNullableListFilter<"agents">
  phone?: Prisma.StringNullableWithAggregatesFilter<"agents"> | string | null
  verified?: Prisma.BoolNullableWithAggregatesFilter<"agents"> | boolean | null
  verification_date?: Prisma.DateTimeNullableWithAggregatesFilter<"agents"> | Date | string | null
  years_experience?: Prisma.IntNullableWithAggregatesFilter<"agents"> | number | null
  bio?: Prisma.StringNullableWithAggregatesFilter<"agents"> | string | null
  photo_url?: Prisma.StringNullableWithAggregatesFilter<"agents"> | string | null
  rating?: Prisma.DecimalNullableWithAggregatesFilter<"agents"> | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_sales?: Prisma.IntNullableWithAggregatesFilter<"agents"> | number | null
  total_listings?: Prisma.IntNullableWithAggregatesFilter<"agents"> | number | null
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"agents"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"agents"> | Date | string | null
  whatsapp?: Prisma.StringNullableWithAggregatesFilter<"agents"> | string | null
}

export type agentsCreateInput = {
  id?: string
  license_number: string
  agency_name?: string | null
  specialization?: Prisma.agentsCreatespecializationInput | string[]
  phone?: string | null
  verified?: boolean | null
  verification_date?: Date | string | null
  years_experience?: number | null
  bio?: string | null
  photo_url?: string | null
  rating?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_sales?: number | null
  total_listings?: number | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  whatsapp?: string | null
  profiles: Prisma.profilesCreateNestedOneWithoutAgentsInput
  properties?: Prisma.propertiesCreateNestedManyWithoutAgentsInput
}

export type agentsUncheckedCreateInput = {
  id?: string
  profile_id: string
  license_number: string
  agency_name?: string | null
  specialization?: Prisma.agentsCreatespecializationInput | string[]
  phone?: string | null
  verified?: boolean | null
  verification_date?: Date | string | null
  years_experience?: number | null
  bio?: string | null
  photo_url?: string | null
  rating?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_sales?: number | null
  total_listings?: number | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  whatsapp?: string | null
  properties?: Prisma.propertiesUncheckedCreateNestedManyWithoutAgentsInput
}

export type agentsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  license_number?: Prisma.StringFieldUpdateOperationsInput | string
  agency_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  specialization?: Prisma.agentsUpdatespecializationInput | string[]
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  verification_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  years_experience?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photo_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rating?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_sales?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  total_listings?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profiles?: Prisma.profilesUpdateOneRequiredWithoutAgentsNestedInput
  properties?: Prisma.propertiesUpdateManyWithoutAgentsNestedInput
}

export type agentsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  profile_id?: Prisma.StringFieldUpdateOperationsInput | string
  license_number?: Prisma.StringFieldUpdateOperationsInput | string
  agency_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  specialization?: Prisma.agentsUpdatespecializationInput | string[]
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  verification_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  years_experience?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photo_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rating?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_sales?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  total_listings?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  properties?: Prisma.propertiesUncheckedUpdateManyWithoutAgentsNestedInput
}

export type agentsCreateManyInput = {
  id?: string
  profile_id: string
  license_number: string
  agency_name?: string | null
  specialization?: Prisma.agentsCreatespecializationInput | string[]
  phone?: string | null
  verified?: boolean | null
  verification_date?: Date | string | null
  years_experience?: number | null
  bio?: string | null
  photo_url?: string | null
  rating?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_sales?: number | null
  total_listings?: number | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  whatsapp?: string | null
}

export type agentsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  license_number?: Prisma.StringFieldUpdateOperationsInput | string
  agency_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  specialization?: Prisma.agentsUpdatespecializationInput | string[]
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  verification_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  years_experience?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photo_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rating?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_sales?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  total_listings?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type agentsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  profile_id?: Prisma.StringFieldUpdateOperationsInput | string
  license_number?: Prisma.StringFieldUpdateOperationsInput | string
  agency_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  specialization?: Prisma.agentsUpdatespecializationInput | string[]
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  verification_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  years_experience?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photo_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rating?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_sales?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  total_listings?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type agentsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  profile_id?: Prisma.SortOrder
  license_number?: Prisma.SortOrder
  agency_name?: Prisma.SortOrder
  specialization?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  verified?: Prisma.SortOrder
  verification_date?: Prisma.SortOrder
  years_experience?: Prisma.SortOrder
  bio?: Prisma.SortOrder
  photo_url?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  total_sales?: Prisma.SortOrder
  total_listings?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  whatsapp?: Prisma.SortOrder
}

export type agentsAvgOrderByAggregateInput = {
  years_experience?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  total_sales?: Prisma.SortOrder
  total_listings?: Prisma.SortOrder
}

export type agentsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  profile_id?: Prisma.SortOrder
  license_number?: Prisma.SortOrder
  agency_name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  verified?: Prisma.SortOrder
  verification_date?: Prisma.SortOrder
  years_experience?: Prisma.SortOrder
  bio?: Prisma.SortOrder
  photo_url?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  total_sales?: Prisma.SortOrder
  total_listings?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  whatsapp?: Prisma.SortOrder
}

export type agentsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  profile_id?: Prisma.SortOrder
  license_number?: Prisma.SortOrder
  agency_name?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  verified?: Prisma.SortOrder
  verification_date?: Prisma.SortOrder
  years_experience?: Prisma.SortOrder
  bio?: Prisma.SortOrder
  photo_url?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  total_sales?: Prisma.SortOrder
  total_listings?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  whatsapp?: Prisma.SortOrder
}

export type agentsSumOrderByAggregateInput = {
  years_experience?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  total_sales?: Prisma.SortOrder
  total_listings?: Prisma.SortOrder
}

export type AgentsNullableScalarRelationFilter = {
  is?: Prisma.agentsWhereInput | null
  isNot?: Prisma.agentsWhereInput | null
}

export type agentsCreatespecializationInput = {
  set: string[]
}

export type agentsUpdatespecializationInput = {
  set?: string[]
  push?: string | string[]
}

export type NullableBoolFieldUpdateOperationsInput = {
  set?: boolean | null
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableDecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type agentsCreateNestedOneWithoutProfilesInput = {
  create?: Prisma.XOR<Prisma.agentsCreateWithoutProfilesInput, Prisma.agentsUncheckedCreateWithoutProfilesInput>
  connectOrCreate?: Prisma.agentsCreateOrConnectWithoutProfilesInput
  connect?: Prisma.agentsWhereUniqueInput
}

export type agentsUncheckedCreateNestedOneWithoutProfilesInput = {
  create?: Prisma.XOR<Prisma.agentsCreateWithoutProfilesInput, Prisma.agentsUncheckedCreateWithoutProfilesInput>
  connectOrCreate?: Prisma.agentsCreateOrConnectWithoutProfilesInput
  connect?: Prisma.agentsWhereUniqueInput
}

export type agentsUpdateOneWithoutProfilesNestedInput = {
  create?: Prisma.XOR<Prisma.agentsCreateWithoutProfilesInput, Prisma.agentsUncheckedCreateWithoutProfilesInput>
  connectOrCreate?: Prisma.agentsCreateOrConnectWithoutProfilesInput
  upsert?: Prisma.agentsUpsertWithoutProfilesInput
  disconnect?: Prisma.agentsWhereInput | boolean
  delete?: Prisma.agentsWhereInput | boolean
  connect?: Prisma.agentsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.agentsUpdateToOneWithWhereWithoutProfilesInput, Prisma.agentsUpdateWithoutProfilesInput>, Prisma.agentsUncheckedUpdateWithoutProfilesInput>
}

export type agentsUncheckedUpdateOneWithoutProfilesNestedInput = {
  create?: Prisma.XOR<Prisma.agentsCreateWithoutProfilesInput, Prisma.agentsUncheckedCreateWithoutProfilesInput>
  connectOrCreate?: Prisma.agentsCreateOrConnectWithoutProfilesInput
  upsert?: Prisma.agentsUpsertWithoutProfilesInput
  disconnect?: Prisma.agentsWhereInput | boolean
  delete?: Prisma.agentsWhereInput | boolean
  connect?: Prisma.agentsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.agentsUpdateToOneWithWhereWithoutProfilesInput, Prisma.agentsUpdateWithoutProfilesInput>, Prisma.agentsUncheckedUpdateWithoutProfilesInput>
}

export type agentsCreateNestedOneWithoutPropertiesInput = {
  create?: Prisma.XOR<Prisma.agentsCreateWithoutPropertiesInput, Prisma.agentsUncheckedCreateWithoutPropertiesInput>
  connectOrCreate?: Prisma.agentsCreateOrConnectWithoutPropertiesInput
  connect?: Prisma.agentsWhereUniqueInput
}

export type agentsUpdateOneWithoutPropertiesNestedInput = {
  create?: Prisma.XOR<Prisma.agentsCreateWithoutPropertiesInput, Prisma.agentsUncheckedCreateWithoutPropertiesInput>
  connectOrCreate?: Prisma.agentsCreateOrConnectWithoutPropertiesInput
  upsert?: Prisma.agentsUpsertWithoutPropertiesInput
  disconnect?: Prisma.agentsWhereInput | boolean
  delete?: Prisma.agentsWhereInput | boolean
  connect?: Prisma.agentsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.agentsUpdateToOneWithWhereWithoutPropertiesInput, Prisma.agentsUpdateWithoutPropertiesInput>, Prisma.agentsUncheckedUpdateWithoutPropertiesInput>
}

export type agentsCreateWithoutProfilesInput = {
  id?: string
  license_number: string
  agency_name?: string | null
  specialization?: Prisma.agentsCreatespecializationInput | string[]
  phone?: string | null
  verified?: boolean | null
  verification_date?: Date | string | null
  years_experience?: number | null
  bio?: string | null
  photo_url?: string | null
  rating?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_sales?: number | null
  total_listings?: number | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  whatsapp?: string | null
  properties?: Prisma.propertiesCreateNestedManyWithoutAgentsInput
}

export type agentsUncheckedCreateWithoutProfilesInput = {
  id?: string
  license_number: string
  agency_name?: string | null
  specialization?: Prisma.agentsCreatespecializationInput | string[]
  phone?: string | null
  verified?: boolean | null
  verification_date?: Date | string | null
  years_experience?: number | null
  bio?: string | null
  photo_url?: string | null
  rating?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_sales?: number | null
  total_listings?: number | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  whatsapp?: string | null
  properties?: Prisma.propertiesUncheckedCreateNestedManyWithoutAgentsInput
}

export type agentsCreateOrConnectWithoutProfilesInput = {
  where: Prisma.agentsWhereUniqueInput
  create: Prisma.XOR<Prisma.agentsCreateWithoutProfilesInput, Prisma.agentsUncheckedCreateWithoutProfilesInput>
}

export type agentsUpsertWithoutProfilesInput = {
  update: Prisma.XOR<Prisma.agentsUpdateWithoutProfilesInput, Prisma.agentsUncheckedUpdateWithoutProfilesInput>
  create: Prisma.XOR<Prisma.agentsCreateWithoutProfilesInput, Prisma.agentsUncheckedCreateWithoutProfilesInput>
  where?: Prisma.agentsWhereInput
}

export type agentsUpdateToOneWithWhereWithoutProfilesInput = {
  where?: Prisma.agentsWhereInput
  data: Prisma.XOR<Prisma.agentsUpdateWithoutProfilesInput, Prisma.agentsUncheckedUpdateWithoutProfilesInput>
}

export type agentsUpdateWithoutProfilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  license_number?: Prisma.StringFieldUpdateOperationsInput | string
  agency_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  specialization?: Prisma.agentsUpdatespecializationInput | string[]
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  verification_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  years_experience?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photo_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rating?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_sales?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  total_listings?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  properties?: Prisma.propertiesUpdateManyWithoutAgentsNestedInput
}

export type agentsUncheckedUpdateWithoutProfilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  license_number?: Prisma.StringFieldUpdateOperationsInput | string
  agency_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  specialization?: Prisma.agentsUpdatespecializationInput | string[]
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  verification_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  years_experience?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photo_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rating?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_sales?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  total_listings?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  properties?: Prisma.propertiesUncheckedUpdateManyWithoutAgentsNestedInput
}

export type agentsCreateWithoutPropertiesInput = {
  id?: string
  license_number: string
  agency_name?: string | null
  specialization?: Prisma.agentsCreatespecializationInput | string[]
  phone?: string | null
  verified?: boolean | null
  verification_date?: Date | string | null
  years_experience?: number | null
  bio?: string | null
  photo_url?: string | null
  rating?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_sales?: number | null
  total_listings?: number | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  whatsapp?: string | null
  profiles: Prisma.profilesCreateNestedOneWithoutAgentsInput
}

export type agentsUncheckedCreateWithoutPropertiesInput = {
  id?: string
  profile_id: string
  license_number: string
  agency_name?: string | null
  specialization?: Prisma.agentsCreatespecializationInput | string[]
  phone?: string | null
  verified?: boolean | null
  verification_date?: Date | string | null
  years_experience?: number | null
  bio?: string | null
  photo_url?: string | null
  rating?: runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_sales?: number | null
  total_listings?: number | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  whatsapp?: string | null
}

export type agentsCreateOrConnectWithoutPropertiesInput = {
  where: Prisma.agentsWhereUniqueInput
  create: Prisma.XOR<Prisma.agentsCreateWithoutPropertiesInput, Prisma.agentsUncheckedCreateWithoutPropertiesInput>
}

export type agentsUpsertWithoutPropertiesInput = {
  update: Prisma.XOR<Prisma.agentsUpdateWithoutPropertiesInput, Prisma.agentsUncheckedUpdateWithoutPropertiesInput>
  create: Prisma.XOR<Prisma.agentsCreateWithoutPropertiesInput, Prisma.agentsUncheckedCreateWithoutPropertiesInput>
  where?: Prisma.agentsWhereInput
}

export type agentsUpdateToOneWithWhereWithoutPropertiesInput = {
  where?: Prisma.agentsWhereInput
  data: Prisma.XOR<Prisma.agentsUpdateWithoutPropertiesInput, Prisma.agentsUncheckedUpdateWithoutPropertiesInput>
}

export type agentsUpdateWithoutPropertiesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  license_number?: Prisma.StringFieldUpdateOperationsInput | string
  agency_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  specialization?: Prisma.agentsUpdatespecializationInput | string[]
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  verification_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  years_experience?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photo_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rating?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_sales?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  total_listings?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  profiles?: Prisma.profilesUpdateOneRequiredWithoutAgentsNestedInput
}

export type agentsUncheckedUpdateWithoutPropertiesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  profile_id?: Prisma.StringFieldUpdateOperationsInput | string
  license_number?: Prisma.StringFieldUpdateOperationsInput | string
  agency_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  specialization?: Prisma.agentsUpdatespecializationInput | string[]
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  verified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  verification_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  years_experience?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  bio?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photo_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rating?: Prisma.NullableDecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string | null
  total_sales?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  total_listings?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  whatsapp?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type AgentsCountOutputType
 */

export type AgentsCountOutputType = {
  properties: number
}

export type AgentsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  properties?: boolean | AgentsCountOutputTypeCountPropertiesArgs
}

/**
 * AgentsCountOutputType without action
 */
export type AgentsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentsCountOutputType
   */
  select?: Prisma.AgentsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AgentsCountOutputType without action
 */
export type AgentsCountOutputTypeCountPropertiesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.propertiesWhereInput
}


export type agentsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  profile_id?: boolean
  license_number?: boolean
  agency_name?: boolean
  specialization?: boolean
  phone?: boolean
  verified?: boolean
  verification_date?: boolean
  years_experience?: boolean
  bio?: boolean
  photo_url?: boolean
  rating?: boolean
  total_sales?: boolean
  total_listings?: boolean
  created_at?: boolean
  updated_at?: boolean
  whatsapp?: boolean
  profiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
  properties?: boolean | Prisma.agents$propertiesArgs<ExtArgs>
  _count?: boolean | Prisma.AgentsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["agents"]>

export type agentsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  profile_id?: boolean
  license_number?: boolean
  agency_name?: boolean
  specialization?: boolean
  phone?: boolean
  verified?: boolean
  verification_date?: boolean
  years_experience?: boolean
  bio?: boolean
  photo_url?: boolean
  rating?: boolean
  total_sales?: boolean
  total_listings?: boolean
  created_at?: boolean
  updated_at?: boolean
  whatsapp?: boolean
  profiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["agents"]>

export type agentsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  profile_id?: boolean
  license_number?: boolean
  agency_name?: boolean
  specialization?: boolean
  phone?: boolean
  verified?: boolean
  verification_date?: boolean
  years_experience?: boolean
  bio?: boolean
  photo_url?: boolean
  rating?: boolean
  total_sales?: boolean
  total_listings?: boolean
  created_at?: boolean
  updated_at?: boolean
  whatsapp?: boolean
  profiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["agents"]>

export type agentsSelectScalar = {
  id?: boolean
  profile_id?: boolean
  license_number?: boolean
  agency_name?: boolean
  specialization?: boolean
  phone?: boolean
  verified?: boolean
  verification_date?: boolean
  years_experience?: boolean
  bio?: boolean
  photo_url?: boolean
  rating?: boolean
  total_sales?: boolean
  total_listings?: boolean
  created_at?: boolean
  updated_at?: boolean
  whatsapp?: boolean
}

export type agentsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "profile_id" | "license_number" | "agency_name" | "specialization" | "phone" | "verified" | "verification_date" | "years_experience" | "bio" | "photo_url" | "rating" | "total_sales" | "total_listings" | "created_at" | "updated_at" | "whatsapp", ExtArgs["result"]["agents"]>
export type agentsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
  properties?: boolean | Prisma.agents$propertiesArgs<ExtArgs>
  _count?: boolean | Prisma.AgentsCountOutputTypeDefaultArgs<ExtArgs>
}
export type agentsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
}
export type agentsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
}

export type $agentsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "agents"
  objects: {
    profiles: Prisma.$profilesPayload<ExtArgs>
    properties: Prisma.$propertiesPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    profile_id: string
    license_number: string
    agency_name: string | null
    specialization: string[]
    phone: string | null
    verified: boolean | null
    verification_date: Date | null
    years_experience: number | null
    bio: string | null
    photo_url: string | null
    rating: runtime.Decimal | null
    total_sales: number | null
    total_listings: number | null
    created_at: Date | null
    updated_at: Date | null
    whatsapp: string | null
  }, ExtArgs["result"]["agents"]>
  composites: {}
}

export type agentsGetPayload<S extends boolean | null | undefined | agentsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$agentsPayload, S>

export type agentsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<agentsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AgentsCountAggregateInputType | true
  }

export interface agentsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['agents'], meta: { name: 'agents' } }
  /**
   * Find zero or one Agents that matches the filter.
   * @param {agentsFindUniqueArgs} args - Arguments to find a Agents
   * @example
   * // Get one Agents
   * const agents = await prisma.agents.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends agentsFindUniqueArgs>(args: Prisma.SelectSubset<T, agentsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__agentsClient<runtime.Types.Result.GetResult<Prisma.$agentsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Agents that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {agentsFindUniqueOrThrowArgs} args - Arguments to find a Agents
   * @example
   * // Get one Agents
   * const agents = await prisma.agents.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends agentsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, agentsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__agentsClient<runtime.Types.Result.GetResult<Prisma.$agentsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Agents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {agentsFindFirstArgs} args - Arguments to find a Agents
   * @example
   * // Get one Agents
   * const agents = await prisma.agents.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends agentsFindFirstArgs>(args?: Prisma.SelectSubset<T, agentsFindFirstArgs<ExtArgs>>): Prisma.Prisma__agentsClient<runtime.Types.Result.GetResult<Prisma.$agentsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Agents that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {agentsFindFirstOrThrowArgs} args - Arguments to find a Agents
   * @example
   * // Get one Agents
   * const agents = await prisma.agents.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends agentsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, agentsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__agentsClient<runtime.Types.Result.GetResult<Prisma.$agentsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Agents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {agentsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Agents
   * const agents = await prisma.agents.findMany()
   * 
   * // Get first 10 Agents
   * const agents = await prisma.agents.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const agentsWithIdOnly = await prisma.agents.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends agentsFindManyArgs>(args?: Prisma.SelectSubset<T, agentsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$agentsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Agents.
   * @param {agentsCreateArgs} args - Arguments to create a Agents.
   * @example
   * // Create one Agents
   * const Agents = await prisma.agents.create({
   *   data: {
   *     // ... data to create a Agents
   *   }
   * })
   * 
   */
  create<T extends agentsCreateArgs>(args: Prisma.SelectSubset<T, agentsCreateArgs<ExtArgs>>): Prisma.Prisma__agentsClient<runtime.Types.Result.GetResult<Prisma.$agentsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Agents.
   * @param {agentsCreateManyArgs} args - Arguments to create many Agents.
   * @example
   * // Create many Agents
   * const agents = await prisma.agents.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends agentsCreateManyArgs>(args?: Prisma.SelectSubset<T, agentsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Agents and returns the data saved in the database.
   * @param {agentsCreateManyAndReturnArgs} args - Arguments to create many Agents.
   * @example
   * // Create many Agents
   * const agents = await prisma.agents.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Agents and only return the `id`
   * const agentsWithIdOnly = await prisma.agents.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends agentsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, agentsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$agentsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Agents.
   * @param {agentsDeleteArgs} args - Arguments to delete one Agents.
   * @example
   * // Delete one Agents
   * const Agents = await prisma.agents.delete({
   *   where: {
   *     // ... filter to delete one Agents
   *   }
   * })
   * 
   */
  delete<T extends agentsDeleteArgs>(args: Prisma.SelectSubset<T, agentsDeleteArgs<ExtArgs>>): Prisma.Prisma__agentsClient<runtime.Types.Result.GetResult<Prisma.$agentsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Agents.
   * @param {agentsUpdateArgs} args - Arguments to update one Agents.
   * @example
   * // Update one Agents
   * const agents = await prisma.agents.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends agentsUpdateArgs>(args: Prisma.SelectSubset<T, agentsUpdateArgs<ExtArgs>>): Prisma.Prisma__agentsClient<runtime.Types.Result.GetResult<Prisma.$agentsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Agents.
   * @param {agentsDeleteManyArgs} args - Arguments to filter Agents to delete.
   * @example
   * // Delete a few Agents
   * const { count } = await prisma.agents.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends agentsDeleteManyArgs>(args?: Prisma.SelectSubset<T, agentsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Agents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {agentsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Agents
   * const agents = await prisma.agents.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends agentsUpdateManyArgs>(args: Prisma.SelectSubset<T, agentsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Agents and returns the data updated in the database.
   * @param {agentsUpdateManyAndReturnArgs} args - Arguments to update many Agents.
   * @example
   * // Update many Agents
   * const agents = await prisma.agents.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Agents and only return the `id`
   * const agentsWithIdOnly = await prisma.agents.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends agentsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, agentsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$agentsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Agents.
   * @param {agentsUpsertArgs} args - Arguments to update or create a Agents.
   * @example
   * // Update or create a Agents
   * const agents = await prisma.agents.upsert({
   *   create: {
   *     // ... data to create a Agents
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Agents we want to update
   *   }
   * })
   */
  upsert<T extends agentsUpsertArgs>(args: Prisma.SelectSubset<T, agentsUpsertArgs<ExtArgs>>): Prisma.Prisma__agentsClient<runtime.Types.Result.GetResult<Prisma.$agentsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Agents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {agentsCountArgs} args - Arguments to filter Agents to count.
   * @example
   * // Count the number of Agents
   * const count = await prisma.agents.count({
   *   where: {
   *     // ... the filter for the Agents we want to count
   *   }
   * })
  **/
  count<T extends agentsCountArgs>(
    args?: Prisma.Subset<T, agentsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AgentsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Agents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AgentsAggregateArgs>(args: Prisma.Subset<T, AgentsAggregateArgs>): Prisma.PrismaPromise<GetAgentsAggregateType<T>>

  /**
   * Group by Agents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {agentsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends agentsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: agentsGroupByArgs['orderBy'] }
      : { orderBy?: agentsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, agentsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAgentsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the agents model
 */
readonly fields: agentsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for agents.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__agentsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  profiles<T extends Prisma.profilesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.profilesDefaultArgs<ExtArgs>>): Prisma.Prisma__profilesClient<runtime.Types.Result.GetResult<Prisma.$profilesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  properties<T extends Prisma.agents$propertiesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.agents$propertiesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$propertiesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the agents model
 */
export interface agentsFieldRefs {
  readonly id: Prisma.FieldRef<"agents", 'String'>
  readonly profile_id: Prisma.FieldRef<"agents", 'String'>
  readonly license_number: Prisma.FieldRef<"agents", 'String'>
  readonly agency_name: Prisma.FieldRef<"agents", 'String'>
  readonly specialization: Prisma.FieldRef<"agents", 'String[]'>
  readonly phone: Prisma.FieldRef<"agents", 'String'>
  readonly verified: Prisma.FieldRef<"agents", 'Boolean'>
  readonly verification_date: Prisma.FieldRef<"agents", 'DateTime'>
  readonly years_experience: Prisma.FieldRef<"agents", 'Int'>
  readonly bio: Prisma.FieldRef<"agents", 'String'>
  readonly photo_url: Prisma.FieldRef<"agents", 'String'>
  readonly rating: Prisma.FieldRef<"agents", 'Decimal'>
  readonly total_sales: Prisma.FieldRef<"agents", 'Int'>
  readonly total_listings: Prisma.FieldRef<"agents", 'Int'>
  readonly created_at: Prisma.FieldRef<"agents", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"agents", 'DateTime'>
  readonly whatsapp: Prisma.FieldRef<"agents", 'String'>
}
    

// Custom InputTypes
/**
 * agents findUnique
 */
export type agentsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the agents
   */
  select?: Prisma.agentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the agents
   */
  omit?: Prisma.agentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.agentsInclude<ExtArgs> | null
  /**
   * Filter, which agents to fetch.
   */
  where: Prisma.agentsWhereUniqueInput
}

/**
 * agents findUniqueOrThrow
 */
export type agentsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the agents
   */
  select?: Prisma.agentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the agents
   */
  omit?: Prisma.agentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.agentsInclude<ExtArgs> | null
  /**
   * Filter, which agents to fetch.
   */
  where: Prisma.agentsWhereUniqueInput
}

/**
 * agents findFirst
 */
export type agentsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the agents
   */
  select?: Prisma.agentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the agents
   */
  omit?: Prisma.agentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.agentsInclude<ExtArgs> | null
  /**
   * Filter, which agents to fetch.
   */
  where?: Prisma.agentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of agents to fetch.
   */
  orderBy?: Prisma.agentsOrderByWithRelationInput | Prisma.agentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for agents.
   */
  cursor?: Prisma.agentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` agents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` agents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of agents.
   */
  distinct?: Prisma.AgentsScalarFieldEnum | Prisma.AgentsScalarFieldEnum[]
}

/**
 * agents findFirstOrThrow
 */
export type agentsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the agents
   */
  select?: Prisma.agentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the agents
   */
  omit?: Prisma.agentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.agentsInclude<ExtArgs> | null
  /**
   * Filter, which agents to fetch.
   */
  where?: Prisma.agentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of agents to fetch.
   */
  orderBy?: Prisma.agentsOrderByWithRelationInput | Prisma.agentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for agents.
   */
  cursor?: Prisma.agentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` agents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` agents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of agents.
   */
  distinct?: Prisma.AgentsScalarFieldEnum | Prisma.AgentsScalarFieldEnum[]
}

/**
 * agents findMany
 */
export type agentsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the agents
   */
  select?: Prisma.agentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the agents
   */
  omit?: Prisma.agentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.agentsInclude<ExtArgs> | null
  /**
   * Filter, which agents to fetch.
   */
  where?: Prisma.agentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of agents to fetch.
   */
  orderBy?: Prisma.agentsOrderByWithRelationInput | Prisma.agentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing agents.
   */
  cursor?: Prisma.agentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` agents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` agents.
   */
  skip?: number
  distinct?: Prisma.AgentsScalarFieldEnum | Prisma.AgentsScalarFieldEnum[]
}

/**
 * agents create
 */
export type agentsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the agents
   */
  select?: Prisma.agentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the agents
   */
  omit?: Prisma.agentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.agentsInclude<ExtArgs> | null
  /**
   * The data needed to create a agents.
   */
  data: Prisma.XOR<Prisma.agentsCreateInput, Prisma.agentsUncheckedCreateInput>
}

/**
 * agents createMany
 */
export type agentsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many agents.
   */
  data: Prisma.agentsCreateManyInput | Prisma.agentsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * agents createManyAndReturn
 */
export type agentsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the agents
   */
  select?: Prisma.agentsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the agents
   */
  omit?: Prisma.agentsOmit<ExtArgs> | null
  /**
   * The data used to create many agents.
   */
  data: Prisma.agentsCreateManyInput | Prisma.agentsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.agentsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * agents update
 */
export type agentsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the agents
   */
  select?: Prisma.agentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the agents
   */
  omit?: Prisma.agentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.agentsInclude<ExtArgs> | null
  /**
   * The data needed to update a agents.
   */
  data: Prisma.XOR<Prisma.agentsUpdateInput, Prisma.agentsUncheckedUpdateInput>
  /**
   * Choose, which agents to update.
   */
  where: Prisma.agentsWhereUniqueInput
}

/**
 * agents updateMany
 */
export type agentsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update agents.
   */
  data: Prisma.XOR<Prisma.agentsUpdateManyMutationInput, Prisma.agentsUncheckedUpdateManyInput>
  /**
   * Filter which agents to update
   */
  where?: Prisma.agentsWhereInput
  /**
   * Limit how many agents to update.
   */
  limit?: number
}

/**
 * agents updateManyAndReturn
 */
export type agentsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the agents
   */
  select?: Prisma.agentsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the agents
   */
  omit?: Prisma.agentsOmit<ExtArgs> | null
  /**
   * The data used to update agents.
   */
  data: Prisma.XOR<Prisma.agentsUpdateManyMutationInput, Prisma.agentsUncheckedUpdateManyInput>
  /**
   * Filter which agents to update
   */
  where?: Prisma.agentsWhereInput
  /**
   * Limit how many agents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.agentsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * agents upsert
 */
export type agentsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the agents
   */
  select?: Prisma.agentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the agents
   */
  omit?: Prisma.agentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.agentsInclude<ExtArgs> | null
  /**
   * The filter to search for the agents to update in case it exists.
   */
  where: Prisma.agentsWhereUniqueInput
  /**
   * In case the agents found by the `where` argument doesn't exist, create a new agents with this data.
   */
  create: Prisma.XOR<Prisma.agentsCreateInput, Prisma.agentsUncheckedCreateInput>
  /**
   * In case the agents was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.agentsUpdateInput, Prisma.agentsUncheckedUpdateInput>
}

/**
 * agents delete
 */
export type agentsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the agents
   */
  select?: Prisma.agentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the agents
   */
  omit?: Prisma.agentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.agentsInclude<ExtArgs> | null
  /**
   * Filter which agents to delete.
   */
  where: Prisma.agentsWhereUniqueInput
}

/**
 * agents deleteMany
 */
export type agentsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which agents to delete
   */
  where?: Prisma.agentsWhereInput
  /**
   * Limit how many agents to delete.
   */
  limit?: number
}

/**
 * agents.properties
 */
export type agents$propertiesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the properties
   */
  select?: Prisma.propertiesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the properties
   */
  omit?: Prisma.propertiesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.propertiesInclude<ExtArgs> | null
  where?: Prisma.propertiesWhereInput
  orderBy?: Prisma.propertiesOrderByWithRelationInput | Prisma.propertiesOrderByWithRelationInput[]
  cursor?: Prisma.propertiesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PropertiesScalarFieldEnum | Prisma.PropertiesScalarFieldEnum[]
}

/**
 * agents without action
 */
export type agentsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the agents
   */
  select?: Prisma.agentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the agents
   */
  omit?: Prisma.agentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.agentsInclude<ExtArgs> | null
}
