
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `email_campaigns` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model email_campaigns
 * Email marketing campaign records — tracks both Resend broadcast and DB-segment batch sends.
 */
export type email_campaignsModel = runtime.Types.Result.DefaultSelection<Prisma.$email_campaignsPayload>

export type AggregateEmail_campaigns = {
  _count: Email_campaignsCountAggregateOutputType | null
  _avg: Email_campaignsAvgAggregateOutputType | null
  _sum: Email_campaignsSumAggregateOutputType | null
  _min: Email_campaignsMinAggregateOutputType | null
  _max: Email_campaignsMaxAggregateOutputType | null
}

export type Email_campaignsAvgAggregateOutputType = {
  total_recipients: number | null
  sent_count: number | null
  failed_count: number | null
}

export type Email_campaignsSumAggregateOutputType = {
  total_recipients: number | null
  sent_count: number | null
  failed_count: number | null
}

export type Email_campaignsMinAggregateOutputType = {
  id: string | null
  name: string | null
  template_name: string | null
  subject: string | null
  audience_type: string | null
  audience_id: string | null
  send_mode: string | null
  status: string | null
  scheduled_at: Date | null
  sent_at: Date | null
  total_recipients: number | null
  sent_count: number | null
  failed_count: number | null
  resend_id: string | null
  created_by: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Email_campaignsMaxAggregateOutputType = {
  id: string | null
  name: string | null
  template_name: string | null
  subject: string | null
  audience_type: string | null
  audience_id: string | null
  send_mode: string | null
  status: string | null
  scheduled_at: Date | null
  sent_at: Date | null
  total_recipients: number | null
  sent_count: number | null
  failed_count: number | null
  resend_id: string | null
  created_by: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Email_campaignsCountAggregateOutputType = {
  id: number
  name: number
  template_name: number
  subject: number
  audience_type: number
  audience_id: number
  audience_filter: number
  send_mode: number
  status: number
  template_props: number
  scheduled_at: number
  sent_at: number
  total_recipients: number
  sent_count: number
  failed_count: number
  resend_id: number
  created_by: number
  created_at: number
  updated_at: number
  _all: number
}


export type Email_campaignsAvgAggregateInputType = {
  total_recipients?: true
  sent_count?: true
  failed_count?: true
}

export type Email_campaignsSumAggregateInputType = {
  total_recipients?: true
  sent_count?: true
  failed_count?: true
}

export type Email_campaignsMinAggregateInputType = {
  id?: true
  name?: true
  template_name?: true
  subject?: true
  audience_type?: true
  audience_id?: true
  send_mode?: true
  status?: true
  scheduled_at?: true
  sent_at?: true
  total_recipients?: true
  sent_count?: true
  failed_count?: true
  resend_id?: true
  created_by?: true
  created_at?: true
  updated_at?: true
}

export type Email_campaignsMaxAggregateInputType = {
  id?: true
  name?: true
  template_name?: true
  subject?: true
  audience_type?: true
  audience_id?: true
  send_mode?: true
  status?: true
  scheduled_at?: true
  sent_at?: true
  total_recipients?: true
  sent_count?: true
  failed_count?: true
  resend_id?: true
  created_by?: true
  created_at?: true
  updated_at?: true
}

export type Email_campaignsCountAggregateInputType = {
  id?: true
  name?: true
  template_name?: true
  subject?: true
  audience_type?: true
  audience_id?: true
  audience_filter?: true
  send_mode?: true
  status?: true
  template_props?: true
  scheduled_at?: true
  sent_at?: true
  total_recipients?: true
  sent_count?: true
  failed_count?: true
  resend_id?: true
  created_by?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type Email_campaignsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which email_campaigns to aggregate.
   */
  where?: Prisma.email_campaignsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of email_campaigns to fetch.
   */
  orderBy?: Prisma.email_campaignsOrderByWithRelationInput | Prisma.email_campaignsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.email_campaignsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` email_campaigns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` email_campaigns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned email_campaigns
  **/
  _count?: true | Email_campaignsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Email_campaignsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Email_campaignsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Email_campaignsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Email_campaignsMaxAggregateInputType
}

export type GetEmail_campaignsAggregateType<T extends Email_campaignsAggregateArgs> = {
      [P in keyof T & keyof AggregateEmail_campaigns]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEmail_campaigns[P]>
    : Prisma.GetScalarType<T[P], AggregateEmail_campaigns[P]>
}




export type email_campaignsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.email_campaignsWhereInput
  orderBy?: Prisma.email_campaignsOrderByWithAggregationInput | Prisma.email_campaignsOrderByWithAggregationInput[]
  by: Prisma.Email_campaignsScalarFieldEnum[] | Prisma.Email_campaignsScalarFieldEnum
  having?: Prisma.email_campaignsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Email_campaignsCountAggregateInputType | true
  _avg?: Email_campaignsAvgAggregateInputType
  _sum?: Email_campaignsSumAggregateInputType
  _min?: Email_campaignsMinAggregateInputType
  _max?: Email_campaignsMaxAggregateInputType
}

export type Email_campaignsGroupByOutputType = {
  id: string
  name: string
  template_name: string
  subject: string
  audience_type: string
  audience_id: string | null
  audience_filter: runtime.JsonValue | null
  send_mode: string
  status: string
  template_props: runtime.JsonValue | null
  scheduled_at: Date | null
  sent_at: Date | null
  total_recipients: number | null
  sent_count: number | null
  failed_count: number | null
  resend_id: string | null
  created_by: string
  created_at: Date | null
  updated_at: Date | null
  _count: Email_campaignsCountAggregateOutputType | null
  _avg: Email_campaignsAvgAggregateOutputType | null
  _sum: Email_campaignsSumAggregateOutputType | null
  _min: Email_campaignsMinAggregateOutputType | null
  _max: Email_campaignsMaxAggregateOutputType | null
}

type GetEmail_campaignsGroupByPayload<T extends email_campaignsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Email_campaignsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Email_campaignsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Email_campaignsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Email_campaignsGroupByOutputType[P]>
      }
    >
  >



export type email_campaignsWhereInput = {
  AND?: Prisma.email_campaignsWhereInput | Prisma.email_campaignsWhereInput[]
  OR?: Prisma.email_campaignsWhereInput[]
  NOT?: Prisma.email_campaignsWhereInput | Prisma.email_campaignsWhereInput[]
  id?: Prisma.UuidFilter<"email_campaigns"> | string
  name?: Prisma.StringFilter<"email_campaigns"> | string
  template_name?: Prisma.StringFilter<"email_campaigns"> | string
  subject?: Prisma.StringFilter<"email_campaigns"> | string
  audience_type?: Prisma.StringFilter<"email_campaigns"> | string
  audience_id?: Prisma.StringNullableFilter<"email_campaigns"> | string | null
  audience_filter?: Prisma.JsonNullableFilter<"email_campaigns">
  send_mode?: Prisma.StringFilter<"email_campaigns"> | string
  status?: Prisma.StringFilter<"email_campaigns"> | string
  template_props?: Prisma.JsonNullableFilter<"email_campaigns">
  scheduled_at?: Prisma.DateTimeNullableFilter<"email_campaigns"> | Date | string | null
  sent_at?: Prisma.DateTimeNullableFilter<"email_campaigns"> | Date | string | null
  total_recipients?: Prisma.IntNullableFilter<"email_campaigns"> | number | null
  sent_count?: Prisma.IntNullableFilter<"email_campaigns"> | number | null
  failed_count?: Prisma.IntNullableFilter<"email_campaigns"> | number | null
  resend_id?: Prisma.StringNullableFilter<"email_campaigns"> | string | null
  created_by?: Prisma.UuidFilter<"email_campaigns"> | string
  created_at?: Prisma.DateTimeNullableFilter<"email_campaigns"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"email_campaigns"> | Date | string | null
  profiles?: Prisma.XOR<Prisma.ProfilesScalarRelationFilter, Prisma.profilesWhereInput>
}

export type email_campaignsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  template_name?: Prisma.SortOrder
  subject?: Prisma.SortOrder
  audience_type?: Prisma.SortOrder
  audience_id?: Prisma.SortOrderInput | Prisma.SortOrder
  audience_filter?: Prisma.SortOrderInput | Prisma.SortOrder
  send_mode?: Prisma.SortOrder
  status?: Prisma.SortOrder
  template_props?: Prisma.SortOrderInput | Prisma.SortOrder
  scheduled_at?: Prisma.SortOrderInput | Prisma.SortOrder
  sent_at?: Prisma.SortOrderInput | Prisma.SortOrder
  total_recipients?: Prisma.SortOrderInput | Prisma.SortOrder
  sent_count?: Prisma.SortOrderInput | Prisma.SortOrder
  failed_count?: Prisma.SortOrderInput | Prisma.SortOrder
  resend_id?: Prisma.SortOrderInput | Prisma.SortOrder
  created_by?: Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  profiles?: Prisma.profilesOrderByWithRelationInput
}

export type email_campaignsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.email_campaignsWhereInput | Prisma.email_campaignsWhereInput[]
  OR?: Prisma.email_campaignsWhereInput[]
  NOT?: Prisma.email_campaignsWhereInput | Prisma.email_campaignsWhereInput[]
  name?: Prisma.StringFilter<"email_campaigns"> | string
  template_name?: Prisma.StringFilter<"email_campaigns"> | string
  subject?: Prisma.StringFilter<"email_campaigns"> | string
  audience_type?: Prisma.StringFilter<"email_campaigns"> | string
  audience_id?: Prisma.StringNullableFilter<"email_campaigns"> | string | null
  audience_filter?: Prisma.JsonNullableFilter<"email_campaigns">
  send_mode?: Prisma.StringFilter<"email_campaigns"> | string
  status?: Prisma.StringFilter<"email_campaigns"> | string
  template_props?: Prisma.JsonNullableFilter<"email_campaigns">
  scheduled_at?: Prisma.DateTimeNullableFilter<"email_campaigns"> | Date | string | null
  sent_at?: Prisma.DateTimeNullableFilter<"email_campaigns"> | Date | string | null
  total_recipients?: Prisma.IntNullableFilter<"email_campaigns"> | number | null
  sent_count?: Prisma.IntNullableFilter<"email_campaigns"> | number | null
  failed_count?: Prisma.IntNullableFilter<"email_campaigns"> | number | null
  resend_id?: Prisma.StringNullableFilter<"email_campaigns"> | string | null
  created_by?: Prisma.UuidFilter<"email_campaigns"> | string
  created_at?: Prisma.DateTimeNullableFilter<"email_campaigns"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"email_campaigns"> | Date | string | null
  profiles?: Prisma.XOR<Prisma.ProfilesScalarRelationFilter, Prisma.profilesWhereInput>
}, "id">

export type email_campaignsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  template_name?: Prisma.SortOrder
  subject?: Prisma.SortOrder
  audience_type?: Prisma.SortOrder
  audience_id?: Prisma.SortOrderInput | Prisma.SortOrder
  audience_filter?: Prisma.SortOrderInput | Prisma.SortOrder
  send_mode?: Prisma.SortOrder
  status?: Prisma.SortOrder
  template_props?: Prisma.SortOrderInput | Prisma.SortOrder
  scheduled_at?: Prisma.SortOrderInput | Prisma.SortOrder
  sent_at?: Prisma.SortOrderInput | Prisma.SortOrder
  total_recipients?: Prisma.SortOrderInput | Prisma.SortOrder
  sent_count?: Prisma.SortOrderInput | Prisma.SortOrder
  failed_count?: Prisma.SortOrderInput | Prisma.SortOrder
  resend_id?: Prisma.SortOrderInput | Prisma.SortOrder
  created_by?: Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.email_campaignsCountOrderByAggregateInput
  _avg?: Prisma.email_campaignsAvgOrderByAggregateInput
  _max?: Prisma.email_campaignsMaxOrderByAggregateInput
  _min?: Prisma.email_campaignsMinOrderByAggregateInput
  _sum?: Prisma.email_campaignsSumOrderByAggregateInput
}

export type email_campaignsScalarWhereWithAggregatesInput = {
  AND?: Prisma.email_campaignsScalarWhereWithAggregatesInput | Prisma.email_campaignsScalarWhereWithAggregatesInput[]
  OR?: Prisma.email_campaignsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.email_campaignsScalarWhereWithAggregatesInput | Prisma.email_campaignsScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"email_campaigns"> | string
  name?: Prisma.StringWithAggregatesFilter<"email_campaigns"> | string
  template_name?: Prisma.StringWithAggregatesFilter<"email_campaigns"> | string
  subject?: Prisma.StringWithAggregatesFilter<"email_campaigns"> | string
  audience_type?: Prisma.StringWithAggregatesFilter<"email_campaigns"> | string
  audience_id?: Prisma.StringNullableWithAggregatesFilter<"email_campaigns"> | string | null
  audience_filter?: Prisma.JsonNullableWithAggregatesFilter<"email_campaigns">
  send_mode?: Prisma.StringWithAggregatesFilter<"email_campaigns"> | string
  status?: Prisma.StringWithAggregatesFilter<"email_campaigns"> | string
  template_props?: Prisma.JsonNullableWithAggregatesFilter<"email_campaigns">
  scheduled_at?: Prisma.DateTimeNullableWithAggregatesFilter<"email_campaigns"> | Date | string | null
  sent_at?: Prisma.DateTimeNullableWithAggregatesFilter<"email_campaigns"> | Date | string | null
  total_recipients?: Prisma.IntNullableWithAggregatesFilter<"email_campaigns"> | number | null
  sent_count?: Prisma.IntNullableWithAggregatesFilter<"email_campaigns"> | number | null
  failed_count?: Prisma.IntNullableWithAggregatesFilter<"email_campaigns"> | number | null
  resend_id?: Prisma.StringNullableWithAggregatesFilter<"email_campaigns"> | string | null
  created_by?: Prisma.UuidWithAggregatesFilter<"email_campaigns"> | string
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"email_campaigns"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"email_campaigns"> | Date | string | null
}

export type email_campaignsCreateInput = {
  id?: string
  name: string
  template_name: string
  subject: string
  audience_type: string
  audience_id?: string | null
  audience_filter?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  send_mode: string
  status?: string
  template_props?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  scheduled_at?: Date | string | null
  sent_at?: Date | string | null
  total_recipients?: number | null
  sent_count?: number | null
  failed_count?: number | null
  resend_id?: string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  profiles: Prisma.profilesCreateNestedOneWithoutEmail_campaignsInput
}

export type email_campaignsUncheckedCreateInput = {
  id?: string
  name: string
  template_name: string
  subject: string
  audience_type: string
  audience_id?: string | null
  audience_filter?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  send_mode: string
  status?: string
  template_props?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  scheduled_at?: Date | string | null
  sent_at?: Date | string | null
  total_recipients?: number | null
  sent_count?: number | null
  failed_count?: number | null
  resend_id?: string | null
  created_by: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type email_campaignsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  template_name?: Prisma.StringFieldUpdateOperationsInput | string
  subject?: Prisma.StringFieldUpdateOperationsInput | string
  audience_type?: Prisma.StringFieldUpdateOperationsInput | string
  audience_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audience_filter?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  send_mode?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  template_props?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  scheduled_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  sent_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  total_recipients?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sent_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  failed_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  resend_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  profiles?: Prisma.profilesUpdateOneRequiredWithoutEmail_campaignsNestedInput
}

export type email_campaignsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  template_name?: Prisma.StringFieldUpdateOperationsInput | string
  subject?: Prisma.StringFieldUpdateOperationsInput | string
  audience_type?: Prisma.StringFieldUpdateOperationsInput | string
  audience_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audience_filter?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  send_mode?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  template_props?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  scheduled_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  sent_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  total_recipients?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sent_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  failed_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  resend_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type email_campaignsCreateManyInput = {
  id?: string
  name: string
  template_name: string
  subject: string
  audience_type: string
  audience_id?: string | null
  audience_filter?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  send_mode: string
  status?: string
  template_props?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  scheduled_at?: Date | string | null
  sent_at?: Date | string | null
  total_recipients?: number | null
  sent_count?: number | null
  failed_count?: number | null
  resend_id?: string | null
  created_by: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type email_campaignsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  template_name?: Prisma.StringFieldUpdateOperationsInput | string
  subject?: Prisma.StringFieldUpdateOperationsInput | string
  audience_type?: Prisma.StringFieldUpdateOperationsInput | string
  audience_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audience_filter?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  send_mode?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  template_props?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  scheduled_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  sent_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  total_recipients?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sent_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  failed_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  resend_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type email_campaignsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  template_name?: Prisma.StringFieldUpdateOperationsInput | string
  subject?: Prisma.StringFieldUpdateOperationsInput | string
  audience_type?: Prisma.StringFieldUpdateOperationsInput | string
  audience_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audience_filter?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  send_mode?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  template_props?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  scheduled_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  sent_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  total_recipients?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sent_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  failed_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  resend_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_by?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type Email_campaignsListRelationFilter = {
  every?: Prisma.email_campaignsWhereInput
  some?: Prisma.email_campaignsWhereInput
  none?: Prisma.email_campaignsWhereInput
}

export type email_campaignsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type email_campaignsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  template_name?: Prisma.SortOrder
  subject?: Prisma.SortOrder
  audience_type?: Prisma.SortOrder
  audience_id?: Prisma.SortOrder
  audience_filter?: Prisma.SortOrder
  send_mode?: Prisma.SortOrder
  status?: Prisma.SortOrder
  template_props?: Prisma.SortOrder
  scheduled_at?: Prisma.SortOrder
  sent_at?: Prisma.SortOrder
  total_recipients?: Prisma.SortOrder
  sent_count?: Prisma.SortOrder
  failed_count?: Prisma.SortOrder
  resend_id?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type email_campaignsAvgOrderByAggregateInput = {
  total_recipients?: Prisma.SortOrder
  sent_count?: Prisma.SortOrder
  failed_count?: Prisma.SortOrder
}

export type email_campaignsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  template_name?: Prisma.SortOrder
  subject?: Prisma.SortOrder
  audience_type?: Prisma.SortOrder
  audience_id?: Prisma.SortOrder
  send_mode?: Prisma.SortOrder
  status?: Prisma.SortOrder
  scheduled_at?: Prisma.SortOrder
  sent_at?: Prisma.SortOrder
  total_recipients?: Prisma.SortOrder
  sent_count?: Prisma.SortOrder
  failed_count?: Prisma.SortOrder
  resend_id?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type email_campaignsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  template_name?: Prisma.SortOrder
  subject?: Prisma.SortOrder
  audience_type?: Prisma.SortOrder
  audience_id?: Prisma.SortOrder
  send_mode?: Prisma.SortOrder
  status?: Prisma.SortOrder
  scheduled_at?: Prisma.SortOrder
  sent_at?: Prisma.SortOrder
  total_recipients?: Prisma.SortOrder
  sent_count?: Prisma.SortOrder
  failed_count?: Prisma.SortOrder
  resend_id?: Prisma.SortOrder
  created_by?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type email_campaignsSumOrderByAggregateInput = {
  total_recipients?: Prisma.SortOrder
  sent_count?: Prisma.SortOrder
  failed_count?: Prisma.SortOrder
}

export type email_campaignsCreateNestedManyWithoutProfilesInput = {
  create?: Prisma.XOR<Prisma.email_campaignsCreateWithoutProfilesInput, Prisma.email_campaignsUncheckedCreateWithoutProfilesInput> | Prisma.email_campaignsCreateWithoutProfilesInput[] | Prisma.email_campaignsUncheckedCreateWithoutProfilesInput[]
  connectOrCreate?: Prisma.email_campaignsCreateOrConnectWithoutProfilesInput | Prisma.email_campaignsCreateOrConnectWithoutProfilesInput[]
  createMany?: Prisma.email_campaignsCreateManyProfilesInputEnvelope
  connect?: Prisma.email_campaignsWhereUniqueInput | Prisma.email_campaignsWhereUniqueInput[]
}

export type email_campaignsUncheckedCreateNestedManyWithoutProfilesInput = {
  create?: Prisma.XOR<Prisma.email_campaignsCreateWithoutProfilesInput, Prisma.email_campaignsUncheckedCreateWithoutProfilesInput> | Prisma.email_campaignsCreateWithoutProfilesInput[] | Prisma.email_campaignsUncheckedCreateWithoutProfilesInput[]
  connectOrCreate?: Prisma.email_campaignsCreateOrConnectWithoutProfilesInput | Prisma.email_campaignsCreateOrConnectWithoutProfilesInput[]
  createMany?: Prisma.email_campaignsCreateManyProfilesInputEnvelope
  connect?: Prisma.email_campaignsWhereUniqueInput | Prisma.email_campaignsWhereUniqueInput[]
}

export type email_campaignsUpdateManyWithoutProfilesNestedInput = {
  create?: Prisma.XOR<Prisma.email_campaignsCreateWithoutProfilesInput, Prisma.email_campaignsUncheckedCreateWithoutProfilesInput> | Prisma.email_campaignsCreateWithoutProfilesInput[] | Prisma.email_campaignsUncheckedCreateWithoutProfilesInput[]
  connectOrCreate?: Prisma.email_campaignsCreateOrConnectWithoutProfilesInput | Prisma.email_campaignsCreateOrConnectWithoutProfilesInput[]
  upsert?: Prisma.email_campaignsUpsertWithWhereUniqueWithoutProfilesInput | Prisma.email_campaignsUpsertWithWhereUniqueWithoutProfilesInput[]
  createMany?: Prisma.email_campaignsCreateManyProfilesInputEnvelope
  set?: Prisma.email_campaignsWhereUniqueInput | Prisma.email_campaignsWhereUniqueInput[]
  disconnect?: Prisma.email_campaignsWhereUniqueInput | Prisma.email_campaignsWhereUniqueInput[]
  delete?: Prisma.email_campaignsWhereUniqueInput | Prisma.email_campaignsWhereUniqueInput[]
  connect?: Prisma.email_campaignsWhereUniqueInput | Prisma.email_campaignsWhereUniqueInput[]
  update?: Prisma.email_campaignsUpdateWithWhereUniqueWithoutProfilesInput | Prisma.email_campaignsUpdateWithWhereUniqueWithoutProfilesInput[]
  updateMany?: Prisma.email_campaignsUpdateManyWithWhereWithoutProfilesInput | Prisma.email_campaignsUpdateManyWithWhereWithoutProfilesInput[]
  deleteMany?: Prisma.email_campaignsScalarWhereInput | Prisma.email_campaignsScalarWhereInput[]
}

export type email_campaignsUncheckedUpdateManyWithoutProfilesNestedInput = {
  create?: Prisma.XOR<Prisma.email_campaignsCreateWithoutProfilesInput, Prisma.email_campaignsUncheckedCreateWithoutProfilesInput> | Prisma.email_campaignsCreateWithoutProfilesInput[] | Prisma.email_campaignsUncheckedCreateWithoutProfilesInput[]
  connectOrCreate?: Prisma.email_campaignsCreateOrConnectWithoutProfilesInput | Prisma.email_campaignsCreateOrConnectWithoutProfilesInput[]
  upsert?: Prisma.email_campaignsUpsertWithWhereUniqueWithoutProfilesInput | Prisma.email_campaignsUpsertWithWhereUniqueWithoutProfilesInput[]
  createMany?: Prisma.email_campaignsCreateManyProfilesInputEnvelope
  set?: Prisma.email_campaignsWhereUniqueInput | Prisma.email_campaignsWhereUniqueInput[]
  disconnect?: Prisma.email_campaignsWhereUniqueInput | Prisma.email_campaignsWhereUniqueInput[]
  delete?: Prisma.email_campaignsWhereUniqueInput | Prisma.email_campaignsWhereUniqueInput[]
  connect?: Prisma.email_campaignsWhereUniqueInput | Prisma.email_campaignsWhereUniqueInput[]
  update?: Prisma.email_campaignsUpdateWithWhereUniqueWithoutProfilesInput | Prisma.email_campaignsUpdateWithWhereUniqueWithoutProfilesInput[]
  updateMany?: Prisma.email_campaignsUpdateManyWithWhereWithoutProfilesInput | Prisma.email_campaignsUpdateManyWithWhereWithoutProfilesInput[]
  deleteMany?: Prisma.email_campaignsScalarWhereInput | Prisma.email_campaignsScalarWhereInput[]
}

export type email_campaignsCreateWithoutProfilesInput = {
  id?: string
  name: string
  template_name: string
  subject: string
  audience_type: string
  audience_id?: string | null
  audience_filter?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  send_mode: string
  status?: string
  template_props?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  scheduled_at?: Date | string | null
  sent_at?: Date | string | null
  total_recipients?: number | null
  sent_count?: number | null
  failed_count?: number | null
  resend_id?: string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type email_campaignsUncheckedCreateWithoutProfilesInput = {
  id?: string
  name: string
  template_name: string
  subject: string
  audience_type: string
  audience_id?: string | null
  audience_filter?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  send_mode: string
  status?: string
  template_props?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  scheduled_at?: Date | string | null
  sent_at?: Date | string | null
  total_recipients?: number | null
  sent_count?: number | null
  failed_count?: number | null
  resend_id?: string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type email_campaignsCreateOrConnectWithoutProfilesInput = {
  where: Prisma.email_campaignsWhereUniqueInput
  create: Prisma.XOR<Prisma.email_campaignsCreateWithoutProfilesInput, Prisma.email_campaignsUncheckedCreateWithoutProfilesInput>
}

export type email_campaignsCreateManyProfilesInputEnvelope = {
  data: Prisma.email_campaignsCreateManyProfilesInput | Prisma.email_campaignsCreateManyProfilesInput[]
  skipDuplicates?: boolean
}

export type email_campaignsUpsertWithWhereUniqueWithoutProfilesInput = {
  where: Prisma.email_campaignsWhereUniqueInput
  update: Prisma.XOR<Prisma.email_campaignsUpdateWithoutProfilesInput, Prisma.email_campaignsUncheckedUpdateWithoutProfilesInput>
  create: Prisma.XOR<Prisma.email_campaignsCreateWithoutProfilesInput, Prisma.email_campaignsUncheckedCreateWithoutProfilesInput>
}

export type email_campaignsUpdateWithWhereUniqueWithoutProfilesInput = {
  where: Prisma.email_campaignsWhereUniqueInput
  data: Prisma.XOR<Prisma.email_campaignsUpdateWithoutProfilesInput, Prisma.email_campaignsUncheckedUpdateWithoutProfilesInput>
}

export type email_campaignsUpdateManyWithWhereWithoutProfilesInput = {
  where: Prisma.email_campaignsScalarWhereInput
  data: Prisma.XOR<Prisma.email_campaignsUpdateManyMutationInput, Prisma.email_campaignsUncheckedUpdateManyWithoutProfilesInput>
}

export type email_campaignsScalarWhereInput = {
  AND?: Prisma.email_campaignsScalarWhereInput | Prisma.email_campaignsScalarWhereInput[]
  OR?: Prisma.email_campaignsScalarWhereInput[]
  NOT?: Prisma.email_campaignsScalarWhereInput | Prisma.email_campaignsScalarWhereInput[]
  id?: Prisma.UuidFilter<"email_campaigns"> | string
  name?: Prisma.StringFilter<"email_campaigns"> | string
  template_name?: Prisma.StringFilter<"email_campaigns"> | string
  subject?: Prisma.StringFilter<"email_campaigns"> | string
  audience_type?: Prisma.StringFilter<"email_campaigns"> | string
  audience_id?: Prisma.StringNullableFilter<"email_campaigns"> | string | null
  audience_filter?: Prisma.JsonNullableFilter<"email_campaigns">
  send_mode?: Prisma.StringFilter<"email_campaigns"> | string
  status?: Prisma.StringFilter<"email_campaigns"> | string
  template_props?: Prisma.JsonNullableFilter<"email_campaigns">
  scheduled_at?: Prisma.DateTimeNullableFilter<"email_campaigns"> | Date | string | null
  sent_at?: Prisma.DateTimeNullableFilter<"email_campaigns"> | Date | string | null
  total_recipients?: Prisma.IntNullableFilter<"email_campaigns"> | number | null
  sent_count?: Prisma.IntNullableFilter<"email_campaigns"> | number | null
  failed_count?: Prisma.IntNullableFilter<"email_campaigns"> | number | null
  resend_id?: Prisma.StringNullableFilter<"email_campaigns"> | string | null
  created_by?: Prisma.UuidFilter<"email_campaigns"> | string
  created_at?: Prisma.DateTimeNullableFilter<"email_campaigns"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"email_campaigns"> | Date | string | null
}

export type email_campaignsCreateManyProfilesInput = {
  id?: string
  name: string
  template_name: string
  subject: string
  audience_type: string
  audience_id?: string | null
  audience_filter?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  send_mode: string
  status?: string
  template_props?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  scheduled_at?: Date | string | null
  sent_at?: Date | string | null
  total_recipients?: number | null
  sent_count?: number | null
  failed_count?: number | null
  resend_id?: string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type email_campaignsUpdateWithoutProfilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  template_name?: Prisma.StringFieldUpdateOperationsInput | string
  subject?: Prisma.StringFieldUpdateOperationsInput | string
  audience_type?: Prisma.StringFieldUpdateOperationsInput | string
  audience_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audience_filter?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  send_mode?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  template_props?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  scheduled_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  sent_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  total_recipients?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sent_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  failed_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  resend_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type email_campaignsUncheckedUpdateWithoutProfilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  template_name?: Prisma.StringFieldUpdateOperationsInput | string
  subject?: Prisma.StringFieldUpdateOperationsInput | string
  audience_type?: Prisma.StringFieldUpdateOperationsInput | string
  audience_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audience_filter?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  send_mode?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  template_props?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  scheduled_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  sent_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  total_recipients?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sent_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  failed_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  resend_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type email_campaignsUncheckedUpdateManyWithoutProfilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  template_name?: Prisma.StringFieldUpdateOperationsInput | string
  subject?: Prisma.StringFieldUpdateOperationsInput | string
  audience_type?: Prisma.StringFieldUpdateOperationsInput | string
  audience_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audience_filter?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  send_mode?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  template_props?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  scheduled_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  sent_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  total_recipients?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sent_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  failed_count?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  resend_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type email_campaignsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  template_name?: boolean
  subject?: boolean
  audience_type?: boolean
  audience_id?: boolean
  audience_filter?: boolean
  send_mode?: boolean
  status?: boolean
  template_props?: boolean
  scheduled_at?: boolean
  sent_at?: boolean
  total_recipients?: boolean
  sent_count?: boolean
  failed_count?: boolean
  resend_id?: boolean
  created_by?: boolean
  created_at?: boolean
  updated_at?: boolean
  profiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["email_campaigns"]>

export type email_campaignsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  template_name?: boolean
  subject?: boolean
  audience_type?: boolean
  audience_id?: boolean
  audience_filter?: boolean
  send_mode?: boolean
  status?: boolean
  template_props?: boolean
  scheduled_at?: boolean
  sent_at?: boolean
  total_recipients?: boolean
  sent_count?: boolean
  failed_count?: boolean
  resend_id?: boolean
  created_by?: boolean
  created_at?: boolean
  updated_at?: boolean
  profiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["email_campaigns"]>

export type email_campaignsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  template_name?: boolean
  subject?: boolean
  audience_type?: boolean
  audience_id?: boolean
  audience_filter?: boolean
  send_mode?: boolean
  status?: boolean
  template_props?: boolean
  scheduled_at?: boolean
  sent_at?: boolean
  total_recipients?: boolean
  sent_count?: boolean
  failed_count?: boolean
  resend_id?: boolean
  created_by?: boolean
  created_at?: boolean
  updated_at?: boolean
  profiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["email_campaigns"]>

export type email_campaignsSelectScalar = {
  id?: boolean
  name?: boolean
  template_name?: boolean
  subject?: boolean
  audience_type?: boolean
  audience_id?: boolean
  audience_filter?: boolean
  send_mode?: boolean
  status?: boolean
  template_props?: boolean
  scheduled_at?: boolean
  sent_at?: boolean
  total_recipients?: boolean
  sent_count?: boolean
  failed_count?: boolean
  resend_id?: boolean
  created_by?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type email_campaignsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "template_name" | "subject" | "audience_type" | "audience_id" | "audience_filter" | "send_mode" | "status" | "template_props" | "scheduled_at" | "sent_at" | "total_recipients" | "sent_count" | "failed_count" | "resend_id" | "created_by" | "created_at" | "updated_at", ExtArgs["result"]["email_campaigns"]>
export type email_campaignsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
}
export type email_campaignsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
}
export type email_campaignsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
}

export type $email_campaignsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "email_campaigns"
  objects: {
    profiles: Prisma.$profilesPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    template_name: string
    subject: string
    /**
     * 'resend_audience' → Resend Broadcasts API | 'db_segment' → Resend Batch API
     */
    audience_type: string
    /**
     * Resend audience UUID (only for resend_audience type)
     */
    audience_id: string | null
    /**
     * JSON filter object for DB-segment queries, e.g. { "role": "owner" }
     */
    audience_filter: runtime.JsonValue | null
    /**
     * 'broadcast' → Resend Broadcasts API | 'batch' → Resend Batch API
     */
    send_mode: string
    /**
     * 'draft' | 'scheduled' | 'sending' | 'sent' | 'failed' | 'cancelled'
     */
    status: string
    /**
     * Serialised template props used when rendering — stored so preview is reproducible
     */
    template_props: runtime.JsonValue | null
    scheduled_at: Date | null
    sent_at: Date | null
    total_recipients: number | null
    sent_count: number | null
    failed_count: number | null
    /**
     * Resend broadcast ID or first batch message ID for reference
     */
    resend_id: string | null
    created_by: string
    created_at: Date | null
    updated_at: Date | null
  }, ExtArgs["result"]["email_campaigns"]>
  composites: {}
}

export type email_campaignsGetPayload<S extends boolean | null | undefined | email_campaignsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$email_campaignsPayload, S>

export type email_campaignsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<email_campaignsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Email_campaignsCountAggregateInputType | true
  }

export interface email_campaignsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['email_campaigns'], meta: { name: 'email_campaigns' } }
  /**
   * Find zero or one Email_campaigns that matches the filter.
   * @param {email_campaignsFindUniqueArgs} args - Arguments to find a Email_campaigns
   * @example
   * // Get one Email_campaigns
   * const email_campaigns = await prisma.email_campaigns.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends email_campaignsFindUniqueArgs>(args: Prisma.SelectSubset<T, email_campaignsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__email_campaignsClient<runtime.Types.Result.GetResult<Prisma.$email_campaignsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Email_campaigns that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {email_campaignsFindUniqueOrThrowArgs} args - Arguments to find a Email_campaigns
   * @example
   * // Get one Email_campaigns
   * const email_campaigns = await prisma.email_campaigns.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends email_campaignsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, email_campaignsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__email_campaignsClient<runtime.Types.Result.GetResult<Prisma.$email_campaignsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Email_campaigns that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {email_campaignsFindFirstArgs} args - Arguments to find a Email_campaigns
   * @example
   * // Get one Email_campaigns
   * const email_campaigns = await prisma.email_campaigns.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends email_campaignsFindFirstArgs>(args?: Prisma.SelectSubset<T, email_campaignsFindFirstArgs<ExtArgs>>): Prisma.Prisma__email_campaignsClient<runtime.Types.Result.GetResult<Prisma.$email_campaignsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Email_campaigns that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {email_campaignsFindFirstOrThrowArgs} args - Arguments to find a Email_campaigns
   * @example
   * // Get one Email_campaigns
   * const email_campaigns = await prisma.email_campaigns.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends email_campaignsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, email_campaignsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__email_campaignsClient<runtime.Types.Result.GetResult<Prisma.$email_campaignsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Email_campaigns that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {email_campaignsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Email_campaigns
   * const email_campaigns = await prisma.email_campaigns.findMany()
   * 
   * // Get first 10 Email_campaigns
   * const email_campaigns = await prisma.email_campaigns.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const email_campaignsWithIdOnly = await prisma.email_campaigns.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends email_campaignsFindManyArgs>(args?: Prisma.SelectSubset<T, email_campaignsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$email_campaignsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Email_campaigns.
   * @param {email_campaignsCreateArgs} args - Arguments to create a Email_campaigns.
   * @example
   * // Create one Email_campaigns
   * const Email_campaigns = await prisma.email_campaigns.create({
   *   data: {
   *     // ... data to create a Email_campaigns
   *   }
   * })
   * 
   */
  create<T extends email_campaignsCreateArgs>(args: Prisma.SelectSubset<T, email_campaignsCreateArgs<ExtArgs>>): Prisma.Prisma__email_campaignsClient<runtime.Types.Result.GetResult<Prisma.$email_campaignsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Email_campaigns.
   * @param {email_campaignsCreateManyArgs} args - Arguments to create many Email_campaigns.
   * @example
   * // Create many Email_campaigns
   * const email_campaigns = await prisma.email_campaigns.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends email_campaignsCreateManyArgs>(args?: Prisma.SelectSubset<T, email_campaignsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Email_campaigns and returns the data saved in the database.
   * @param {email_campaignsCreateManyAndReturnArgs} args - Arguments to create many Email_campaigns.
   * @example
   * // Create many Email_campaigns
   * const email_campaigns = await prisma.email_campaigns.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Email_campaigns and only return the `id`
   * const email_campaignsWithIdOnly = await prisma.email_campaigns.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends email_campaignsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, email_campaignsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$email_campaignsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Email_campaigns.
   * @param {email_campaignsDeleteArgs} args - Arguments to delete one Email_campaigns.
   * @example
   * // Delete one Email_campaigns
   * const Email_campaigns = await prisma.email_campaigns.delete({
   *   where: {
   *     // ... filter to delete one Email_campaigns
   *   }
   * })
   * 
   */
  delete<T extends email_campaignsDeleteArgs>(args: Prisma.SelectSubset<T, email_campaignsDeleteArgs<ExtArgs>>): Prisma.Prisma__email_campaignsClient<runtime.Types.Result.GetResult<Prisma.$email_campaignsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Email_campaigns.
   * @param {email_campaignsUpdateArgs} args - Arguments to update one Email_campaigns.
   * @example
   * // Update one Email_campaigns
   * const email_campaigns = await prisma.email_campaigns.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends email_campaignsUpdateArgs>(args: Prisma.SelectSubset<T, email_campaignsUpdateArgs<ExtArgs>>): Prisma.Prisma__email_campaignsClient<runtime.Types.Result.GetResult<Prisma.$email_campaignsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Email_campaigns.
   * @param {email_campaignsDeleteManyArgs} args - Arguments to filter Email_campaigns to delete.
   * @example
   * // Delete a few Email_campaigns
   * const { count } = await prisma.email_campaigns.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends email_campaignsDeleteManyArgs>(args?: Prisma.SelectSubset<T, email_campaignsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Email_campaigns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {email_campaignsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Email_campaigns
   * const email_campaigns = await prisma.email_campaigns.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends email_campaignsUpdateManyArgs>(args: Prisma.SelectSubset<T, email_campaignsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Email_campaigns and returns the data updated in the database.
   * @param {email_campaignsUpdateManyAndReturnArgs} args - Arguments to update many Email_campaigns.
   * @example
   * // Update many Email_campaigns
   * const email_campaigns = await prisma.email_campaigns.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Email_campaigns and only return the `id`
   * const email_campaignsWithIdOnly = await prisma.email_campaigns.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends email_campaignsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, email_campaignsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$email_campaignsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Email_campaigns.
   * @param {email_campaignsUpsertArgs} args - Arguments to update or create a Email_campaigns.
   * @example
   * // Update or create a Email_campaigns
   * const email_campaigns = await prisma.email_campaigns.upsert({
   *   create: {
   *     // ... data to create a Email_campaigns
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Email_campaigns we want to update
   *   }
   * })
   */
  upsert<T extends email_campaignsUpsertArgs>(args: Prisma.SelectSubset<T, email_campaignsUpsertArgs<ExtArgs>>): Prisma.Prisma__email_campaignsClient<runtime.Types.Result.GetResult<Prisma.$email_campaignsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Email_campaigns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {email_campaignsCountArgs} args - Arguments to filter Email_campaigns to count.
   * @example
   * // Count the number of Email_campaigns
   * const count = await prisma.email_campaigns.count({
   *   where: {
   *     // ... the filter for the Email_campaigns we want to count
   *   }
   * })
  **/
  count<T extends email_campaignsCountArgs>(
    args?: Prisma.Subset<T, email_campaignsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Email_campaignsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Email_campaigns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Email_campaignsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Email_campaignsAggregateArgs>(args: Prisma.Subset<T, Email_campaignsAggregateArgs>): Prisma.PrismaPromise<GetEmail_campaignsAggregateType<T>>

  /**
   * Group by Email_campaigns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {email_campaignsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends email_campaignsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: email_campaignsGroupByArgs['orderBy'] }
      : { orderBy?: email_campaignsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, email_campaignsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEmail_campaignsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the email_campaigns model
 */
readonly fields: email_campaignsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for email_campaigns.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__email_campaignsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  profiles<T extends Prisma.profilesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.profilesDefaultArgs<ExtArgs>>): Prisma.Prisma__profilesClient<runtime.Types.Result.GetResult<Prisma.$profilesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the email_campaigns model
 */
export interface email_campaignsFieldRefs {
  readonly id: Prisma.FieldRef<"email_campaigns", 'String'>
  readonly name: Prisma.FieldRef<"email_campaigns", 'String'>
  readonly template_name: Prisma.FieldRef<"email_campaigns", 'String'>
  readonly subject: Prisma.FieldRef<"email_campaigns", 'String'>
  readonly audience_type: Prisma.FieldRef<"email_campaigns", 'String'>
  readonly audience_id: Prisma.FieldRef<"email_campaigns", 'String'>
  readonly audience_filter: Prisma.FieldRef<"email_campaigns", 'Json'>
  readonly send_mode: Prisma.FieldRef<"email_campaigns", 'String'>
  readonly status: Prisma.FieldRef<"email_campaigns", 'String'>
  readonly template_props: Prisma.FieldRef<"email_campaigns", 'Json'>
  readonly scheduled_at: Prisma.FieldRef<"email_campaigns", 'DateTime'>
  readonly sent_at: Prisma.FieldRef<"email_campaigns", 'DateTime'>
  readonly total_recipients: Prisma.FieldRef<"email_campaigns", 'Int'>
  readonly sent_count: Prisma.FieldRef<"email_campaigns", 'Int'>
  readonly failed_count: Prisma.FieldRef<"email_campaigns", 'Int'>
  readonly resend_id: Prisma.FieldRef<"email_campaigns", 'String'>
  readonly created_by: Prisma.FieldRef<"email_campaigns", 'String'>
  readonly created_at: Prisma.FieldRef<"email_campaigns", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"email_campaigns", 'DateTime'>
}
    

// Custom InputTypes
/**
 * email_campaigns findUnique
 */
export type email_campaignsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the email_campaigns
   */
  select?: Prisma.email_campaignsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the email_campaigns
   */
  omit?: Prisma.email_campaignsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.email_campaignsInclude<ExtArgs> | null
  /**
   * Filter, which email_campaigns to fetch.
   */
  where: Prisma.email_campaignsWhereUniqueInput
}

/**
 * email_campaigns findUniqueOrThrow
 */
export type email_campaignsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the email_campaigns
   */
  select?: Prisma.email_campaignsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the email_campaigns
   */
  omit?: Prisma.email_campaignsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.email_campaignsInclude<ExtArgs> | null
  /**
   * Filter, which email_campaigns to fetch.
   */
  where: Prisma.email_campaignsWhereUniqueInput
}

/**
 * email_campaigns findFirst
 */
export type email_campaignsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the email_campaigns
   */
  select?: Prisma.email_campaignsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the email_campaigns
   */
  omit?: Prisma.email_campaignsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.email_campaignsInclude<ExtArgs> | null
  /**
   * Filter, which email_campaigns to fetch.
   */
  where?: Prisma.email_campaignsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of email_campaigns to fetch.
   */
  orderBy?: Prisma.email_campaignsOrderByWithRelationInput | Prisma.email_campaignsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for email_campaigns.
   */
  cursor?: Prisma.email_campaignsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` email_campaigns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` email_campaigns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of email_campaigns.
   */
  distinct?: Prisma.Email_campaignsScalarFieldEnum | Prisma.Email_campaignsScalarFieldEnum[]
}

/**
 * email_campaigns findFirstOrThrow
 */
export type email_campaignsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the email_campaigns
   */
  select?: Prisma.email_campaignsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the email_campaigns
   */
  omit?: Prisma.email_campaignsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.email_campaignsInclude<ExtArgs> | null
  /**
   * Filter, which email_campaigns to fetch.
   */
  where?: Prisma.email_campaignsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of email_campaigns to fetch.
   */
  orderBy?: Prisma.email_campaignsOrderByWithRelationInput | Prisma.email_campaignsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for email_campaigns.
   */
  cursor?: Prisma.email_campaignsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` email_campaigns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` email_campaigns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of email_campaigns.
   */
  distinct?: Prisma.Email_campaignsScalarFieldEnum | Prisma.Email_campaignsScalarFieldEnum[]
}

/**
 * email_campaigns findMany
 */
export type email_campaignsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the email_campaigns
   */
  select?: Prisma.email_campaignsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the email_campaigns
   */
  omit?: Prisma.email_campaignsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.email_campaignsInclude<ExtArgs> | null
  /**
   * Filter, which email_campaigns to fetch.
   */
  where?: Prisma.email_campaignsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of email_campaigns to fetch.
   */
  orderBy?: Prisma.email_campaignsOrderByWithRelationInput | Prisma.email_campaignsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing email_campaigns.
   */
  cursor?: Prisma.email_campaignsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` email_campaigns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` email_campaigns.
   */
  skip?: number
  distinct?: Prisma.Email_campaignsScalarFieldEnum | Prisma.Email_campaignsScalarFieldEnum[]
}

/**
 * email_campaigns create
 */
export type email_campaignsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the email_campaigns
   */
  select?: Prisma.email_campaignsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the email_campaigns
   */
  omit?: Prisma.email_campaignsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.email_campaignsInclude<ExtArgs> | null
  /**
   * The data needed to create a email_campaigns.
   */
  data: Prisma.XOR<Prisma.email_campaignsCreateInput, Prisma.email_campaignsUncheckedCreateInput>
}

/**
 * email_campaigns createMany
 */
export type email_campaignsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many email_campaigns.
   */
  data: Prisma.email_campaignsCreateManyInput | Prisma.email_campaignsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * email_campaigns createManyAndReturn
 */
export type email_campaignsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the email_campaigns
   */
  select?: Prisma.email_campaignsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the email_campaigns
   */
  omit?: Prisma.email_campaignsOmit<ExtArgs> | null
  /**
   * The data used to create many email_campaigns.
   */
  data: Prisma.email_campaignsCreateManyInput | Prisma.email_campaignsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.email_campaignsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * email_campaigns update
 */
export type email_campaignsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the email_campaigns
   */
  select?: Prisma.email_campaignsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the email_campaigns
   */
  omit?: Prisma.email_campaignsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.email_campaignsInclude<ExtArgs> | null
  /**
   * The data needed to update a email_campaigns.
   */
  data: Prisma.XOR<Prisma.email_campaignsUpdateInput, Prisma.email_campaignsUncheckedUpdateInput>
  /**
   * Choose, which email_campaigns to update.
   */
  where: Prisma.email_campaignsWhereUniqueInput
}

/**
 * email_campaigns updateMany
 */
export type email_campaignsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update email_campaigns.
   */
  data: Prisma.XOR<Prisma.email_campaignsUpdateManyMutationInput, Prisma.email_campaignsUncheckedUpdateManyInput>
  /**
   * Filter which email_campaigns to update
   */
  where?: Prisma.email_campaignsWhereInput
  /**
   * Limit how many email_campaigns to update.
   */
  limit?: number
}

/**
 * email_campaigns updateManyAndReturn
 */
export type email_campaignsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the email_campaigns
   */
  select?: Prisma.email_campaignsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the email_campaigns
   */
  omit?: Prisma.email_campaignsOmit<ExtArgs> | null
  /**
   * The data used to update email_campaigns.
   */
  data: Prisma.XOR<Prisma.email_campaignsUpdateManyMutationInput, Prisma.email_campaignsUncheckedUpdateManyInput>
  /**
   * Filter which email_campaigns to update
   */
  where?: Prisma.email_campaignsWhereInput
  /**
   * Limit how many email_campaigns to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.email_campaignsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * email_campaigns upsert
 */
export type email_campaignsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the email_campaigns
   */
  select?: Prisma.email_campaignsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the email_campaigns
   */
  omit?: Prisma.email_campaignsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.email_campaignsInclude<ExtArgs> | null
  /**
   * The filter to search for the email_campaigns to update in case it exists.
   */
  where: Prisma.email_campaignsWhereUniqueInput
  /**
   * In case the email_campaigns found by the `where` argument doesn't exist, create a new email_campaigns with this data.
   */
  create: Prisma.XOR<Prisma.email_campaignsCreateInput, Prisma.email_campaignsUncheckedCreateInput>
  /**
   * In case the email_campaigns was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.email_campaignsUpdateInput, Prisma.email_campaignsUncheckedUpdateInput>
}

/**
 * email_campaigns delete
 */
export type email_campaignsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the email_campaigns
   */
  select?: Prisma.email_campaignsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the email_campaigns
   */
  omit?: Prisma.email_campaignsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.email_campaignsInclude<ExtArgs> | null
  /**
   * Filter which email_campaigns to delete.
   */
  where: Prisma.email_campaignsWhereUniqueInput
}

/**
 * email_campaigns deleteMany
 */
export type email_campaignsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which email_campaigns to delete
   */
  where?: Prisma.email_campaignsWhereInput
  /**
   * Limit how many email_campaigns to delete.
   */
  limit?: number
}

/**
 * email_campaigns without action
 */
export type email_campaignsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the email_campaigns
   */
  select?: Prisma.email_campaignsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the email_campaigns
   */
  omit?: Prisma.email_campaignsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.email_campaignsInclude<ExtArgs> | null
}
