
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `inquiries` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model inquiries
 * This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
 * This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info.
 */
export type inquiriesModel = runtime.Types.Result.DefaultSelection<Prisma.$inquiriesPayload>

export type AggregateInquiries = {
  _count: InquiriesCountAggregateOutputType | null
  _min: InquiriesMinAggregateOutputType | null
  _max: InquiriesMaxAggregateOutputType | null
}

export type InquiriesMinAggregateOutputType = {
  id: string | null
  property_id: string | null
  sender_id: string | null
  owner_id: string | null
  message: string | null
  status: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type InquiriesMaxAggregateOutputType = {
  id: string | null
  property_id: string | null
  sender_id: string | null
  owner_id: string | null
  message: string | null
  status: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type InquiriesCountAggregateOutputType = {
  id: number
  property_id: number
  sender_id: number
  owner_id: number
  message: number
  status: number
  created_at: number
  updated_at: number
  _all: number
}


export type InquiriesMinAggregateInputType = {
  id?: true
  property_id?: true
  sender_id?: true
  owner_id?: true
  message?: true
  status?: true
  created_at?: true
  updated_at?: true
}

export type InquiriesMaxAggregateInputType = {
  id?: true
  property_id?: true
  sender_id?: true
  owner_id?: true
  message?: true
  status?: true
  created_at?: true
  updated_at?: true
}

export type InquiriesCountAggregateInputType = {
  id?: true
  property_id?: true
  sender_id?: true
  owner_id?: true
  message?: true
  status?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type InquiriesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which inquiries to aggregate.
   */
  where?: Prisma.inquiriesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of inquiries to fetch.
   */
  orderBy?: Prisma.inquiriesOrderByWithRelationInput | Prisma.inquiriesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.inquiriesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` inquiries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` inquiries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned inquiries
  **/
  _count?: true | InquiriesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: InquiriesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: InquiriesMaxAggregateInputType
}

export type GetInquiriesAggregateType<T extends InquiriesAggregateArgs> = {
      [P in keyof T & keyof AggregateInquiries]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateInquiries[P]>
    : Prisma.GetScalarType<T[P], AggregateInquiries[P]>
}




export type inquiriesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.inquiriesWhereInput
  orderBy?: Prisma.inquiriesOrderByWithAggregationInput | Prisma.inquiriesOrderByWithAggregationInput[]
  by: Prisma.InquiriesScalarFieldEnum[] | Prisma.InquiriesScalarFieldEnum
  having?: Prisma.inquiriesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: InquiriesCountAggregateInputType | true
  _min?: InquiriesMinAggregateInputType
  _max?: InquiriesMaxAggregateInputType
}

export type InquiriesGroupByOutputType = {
  id: string
  property_id: string
  sender_id: string
  owner_id: string
  message: string
  status: string
  created_at: Date | null
  updated_at: Date | null
  _count: InquiriesCountAggregateOutputType | null
  _min: InquiriesMinAggregateOutputType | null
  _max: InquiriesMaxAggregateOutputType | null
}

type GetInquiriesGroupByPayload<T extends inquiriesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<InquiriesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof InquiriesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], InquiriesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], InquiriesGroupByOutputType[P]>
      }
    >
  >



export type inquiriesWhereInput = {
  AND?: Prisma.inquiriesWhereInput | Prisma.inquiriesWhereInput[]
  OR?: Prisma.inquiriesWhereInput[]
  NOT?: Prisma.inquiriesWhereInput | Prisma.inquiriesWhereInput[]
  id?: Prisma.UuidFilter<"inquiries"> | string
  property_id?: Prisma.UuidFilter<"inquiries"> | string
  sender_id?: Prisma.UuidFilter<"inquiries"> | string
  owner_id?: Prisma.UuidFilter<"inquiries"> | string
  message?: Prisma.StringFilter<"inquiries"> | string
  status?: Prisma.StringFilter<"inquiries"> | string
  created_at?: Prisma.DateTimeNullableFilter<"inquiries"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"inquiries"> | Date | string | null
  profiles_inquiries_owner_idToprofiles?: Prisma.XOR<Prisma.ProfilesScalarRelationFilter, Prisma.profilesWhereInput>
  properties?: Prisma.XOR<Prisma.PropertiesScalarRelationFilter, Prisma.propertiesWhereInput>
  profiles_inquiries_sender_idToprofiles?: Prisma.XOR<Prisma.ProfilesScalarRelationFilter, Prisma.profilesWhereInput>
}

export type inquiriesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  property_id?: Prisma.SortOrder
  sender_id?: Prisma.SortOrder
  owner_id?: Prisma.SortOrder
  message?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  profiles_inquiries_owner_idToprofiles?: Prisma.profilesOrderByWithRelationInput
  properties?: Prisma.propertiesOrderByWithRelationInput
  profiles_inquiries_sender_idToprofiles?: Prisma.profilesOrderByWithRelationInput
}

export type inquiriesWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.inquiriesWhereInput | Prisma.inquiriesWhereInput[]
  OR?: Prisma.inquiriesWhereInput[]
  NOT?: Prisma.inquiriesWhereInput | Prisma.inquiriesWhereInput[]
  property_id?: Prisma.UuidFilter<"inquiries"> | string
  sender_id?: Prisma.UuidFilter<"inquiries"> | string
  owner_id?: Prisma.UuidFilter<"inquiries"> | string
  message?: Prisma.StringFilter<"inquiries"> | string
  status?: Prisma.StringFilter<"inquiries"> | string
  created_at?: Prisma.DateTimeNullableFilter<"inquiries"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"inquiries"> | Date | string | null
  profiles_inquiries_owner_idToprofiles?: Prisma.XOR<Prisma.ProfilesScalarRelationFilter, Prisma.profilesWhereInput>
  properties?: Prisma.XOR<Prisma.PropertiesScalarRelationFilter, Prisma.propertiesWhereInput>
  profiles_inquiries_sender_idToprofiles?: Prisma.XOR<Prisma.ProfilesScalarRelationFilter, Prisma.profilesWhereInput>
}, "id">

export type inquiriesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  property_id?: Prisma.SortOrder
  sender_id?: Prisma.SortOrder
  owner_id?: Prisma.SortOrder
  message?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.inquiriesCountOrderByAggregateInput
  _max?: Prisma.inquiriesMaxOrderByAggregateInput
  _min?: Prisma.inquiriesMinOrderByAggregateInput
}

export type inquiriesScalarWhereWithAggregatesInput = {
  AND?: Prisma.inquiriesScalarWhereWithAggregatesInput | Prisma.inquiriesScalarWhereWithAggregatesInput[]
  OR?: Prisma.inquiriesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.inquiriesScalarWhereWithAggregatesInput | Prisma.inquiriesScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"inquiries"> | string
  property_id?: Prisma.UuidWithAggregatesFilter<"inquiries"> | string
  sender_id?: Prisma.UuidWithAggregatesFilter<"inquiries"> | string
  owner_id?: Prisma.UuidWithAggregatesFilter<"inquiries"> | string
  message?: Prisma.StringWithAggregatesFilter<"inquiries"> | string
  status?: Prisma.StringWithAggregatesFilter<"inquiries"> | string
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"inquiries"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"inquiries"> | Date | string | null
}

export type inquiriesCreateInput = {
  id?: string
  message: string
  status?: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
  profiles_inquiries_owner_idToprofiles: Prisma.profilesCreateNestedOneWithoutInquiries_inquiries_owner_idToprofilesInput
  properties: Prisma.propertiesCreateNestedOneWithoutInquiriesInput
  profiles_inquiries_sender_idToprofiles: Prisma.profilesCreateNestedOneWithoutInquiries_inquiries_sender_idToprofilesInput
}

export type inquiriesUncheckedCreateInput = {
  id?: string
  property_id: string
  sender_id: string
  owner_id: string
  message: string
  status?: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type inquiriesUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  profiles_inquiries_owner_idToprofiles?: Prisma.profilesUpdateOneRequiredWithoutInquiries_inquiries_owner_idToprofilesNestedInput
  properties?: Prisma.propertiesUpdateOneRequiredWithoutInquiriesNestedInput
  profiles_inquiries_sender_idToprofiles?: Prisma.profilesUpdateOneRequiredWithoutInquiries_inquiries_sender_idToprofilesNestedInput
}

export type inquiriesUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  property_id?: Prisma.StringFieldUpdateOperationsInput | string
  sender_id?: Prisma.StringFieldUpdateOperationsInput | string
  owner_id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type inquiriesCreateManyInput = {
  id?: string
  property_id: string
  sender_id: string
  owner_id: string
  message: string
  status?: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type inquiriesUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type inquiriesUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  property_id?: Prisma.StringFieldUpdateOperationsInput | string
  sender_id?: Prisma.StringFieldUpdateOperationsInput | string
  owner_id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type inquiriesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  property_id?: Prisma.SortOrder
  sender_id?: Prisma.SortOrder
  owner_id?: Prisma.SortOrder
  message?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type inquiriesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  property_id?: Prisma.SortOrder
  sender_id?: Prisma.SortOrder
  owner_id?: Prisma.SortOrder
  message?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type inquiriesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  property_id?: Prisma.SortOrder
  sender_id?: Prisma.SortOrder
  owner_id?: Prisma.SortOrder
  message?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type InquiriesListRelationFilter = {
  every?: Prisma.inquiriesWhereInput
  some?: Prisma.inquiriesWhereInput
  none?: Prisma.inquiriesWhereInput
}

export type inquiriesOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type inquiriesCreateNestedManyWithoutProfiles_inquiries_owner_idToprofilesInput = {
  create?: Prisma.XOR<Prisma.inquiriesCreateWithoutProfiles_inquiries_owner_idToprofilesInput, Prisma.inquiriesUncheckedCreateWithoutProfiles_inquiries_owner_idToprofilesInput> | Prisma.inquiriesCreateWithoutProfiles_inquiries_owner_idToprofilesInput[] | Prisma.inquiriesUncheckedCreateWithoutProfiles_inquiries_owner_idToprofilesInput[]
  connectOrCreate?: Prisma.inquiriesCreateOrConnectWithoutProfiles_inquiries_owner_idToprofilesInput | Prisma.inquiriesCreateOrConnectWithoutProfiles_inquiries_owner_idToprofilesInput[]
  createMany?: Prisma.inquiriesCreateManyProfiles_inquiries_owner_idToprofilesInputEnvelope
  connect?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
}

export type inquiriesCreateNestedManyWithoutProfiles_inquiries_sender_idToprofilesInput = {
  create?: Prisma.XOR<Prisma.inquiriesCreateWithoutProfiles_inquiries_sender_idToprofilesInput, Prisma.inquiriesUncheckedCreateWithoutProfiles_inquiries_sender_idToprofilesInput> | Prisma.inquiriesCreateWithoutProfiles_inquiries_sender_idToprofilesInput[] | Prisma.inquiriesUncheckedCreateWithoutProfiles_inquiries_sender_idToprofilesInput[]
  connectOrCreate?: Prisma.inquiriesCreateOrConnectWithoutProfiles_inquiries_sender_idToprofilesInput | Prisma.inquiriesCreateOrConnectWithoutProfiles_inquiries_sender_idToprofilesInput[]
  createMany?: Prisma.inquiriesCreateManyProfiles_inquiries_sender_idToprofilesInputEnvelope
  connect?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
}

export type inquiriesUncheckedCreateNestedManyWithoutProfiles_inquiries_owner_idToprofilesInput = {
  create?: Prisma.XOR<Prisma.inquiriesCreateWithoutProfiles_inquiries_owner_idToprofilesInput, Prisma.inquiriesUncheckedCreateWithoutProfiles_inquiries_owner_idToprofilesInput> | Prisma.inquiriesCreateWithoutProfiles_inquiries_owner_idToprofilesInput[] | Prisma.inquiriesUncheckedCreateWithoutProfiles_inquiries_owner_idToprofilesInput[]
  connectOrCreate?: Prisma.inquiriesCreateOrConnectWithoutProfiles_inquiries_owner_idToprofilesInput | Prisma.inquiriesCreateOrConnectWithoutProfiles_inquiries_owner_idToprofilesInput[]
  createMany?: Prisma.inquiriesCreateManyProfiles_inquiries_owner_idToprofilesInputEnvelope
  connect?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
}

export type inquiriesUncheckedCreateNestedManyWithoutProfiles_inquiries_sender_idToprofilesInput = {
  create?: Prisma.XOR<Prisma.inquiriesCreateWithoutProfiles_inquiries_sender_idToprofilesInput, Prisma.inquiriesUncheckedCreateWithoutProfiles_inquiries_sender_idToprofilesInput> | Prisma.inquiriesCreateWithoutProfiles_inquiries_sender_idToprofilesInput[] | Prisma.inquiriesUncheckedCreateWithoutProfiles_inquiries_sender_idToprofilesInput[]
  connectOrCreate?: Prisma.inquiriesCreateOrConnectWithoutProfiles_inquiries_sender_idToprofilesInput | Prisma.inquiriesCreateOrConnectWithoutProfiles_inquiries_sender_idToprofilesInput[]
  createMany?: Prisma.inquiriesCreateManyProfiles_inquiries_sender_idToprofilesInputEnvelope
  connect?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
}

export type inquiriesUpdateManyWithoutProfiles_inquiries_owner_idToprofilesNestedInput = {
  create?: Prisma.XOR<Prisma.inquiriesCreateWithoutProfiles_inquiries_owner_idToprofilesInput, Prisma.inquiriesUncheckedCreateWithoutProfiles_inquiries_owner_idToprofilesInput> | Prisma.inquiriesCreateWithoutProfiles_inquiries_owner_idToprofilesInput[] | Prisma.inquiriesUncheckedCreateWithoutProfiles_inquiries_owner_idToprofilesInput[]
  connectOrCreate?: Prisma.inquiriesCreateOrConnectWithoutProfiles_inquiries_owner_idToprofilesInput | Prisma.inquiriesCreateOrConnectWithoutProfiles_inquiries_owner_idToprofilesInput[]
  upsert?: Prisma.inquiriesUpsertWithWhereUniqueWithoutProfiles_inquiries_owner_idToprofilesInput | Prisma.inquiriesUpsertWithWhereUniqueWithoutProfiles_inquiries_owner_idToprofilesInput[]
  createMany?: Prisma.inquiriesCreateManyProfiles_inquiries_owner_idToprofilesInputEnvelope
  set?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
  disconnect?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
  delete?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
  connect?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
  update?: Prisma.inquiriesUpdateWithWhereUniqueWithoutProfiles_inquiries_owner_idToprofilesInput | Prisma.inquiriesUpdateWithWhereUniqueWithoutProfiles_inquiries_owner_idToprofilesInput[]
  updateMany?: Prisma.inquiriesUpdateManyWithWhereWithoutProfiles_inquiries_owner_idToprofilesInput | Prisma.inquiriesUpdateManyWithWhereWithoutProfiles_inquiries_owner_idToprofilesInput[]
  deleteMany?: Prisma.inquiriesScalarWhereInput | Prisma.inquiriesScalarWhereInput[]
}

export type inquiriesUpdateManyWithoutProfiles_inquiries_sender_idToprofilesNestedInput = {
  create?: Prisma.XOR<Prisma.inquiriesCreateWithoutProfiles_inquiries_sender_idToprofilesInput, Prisma.inquiriesUncheckedCreateWithoutProfiles_inquiries_sender_idToprofilesInput> | Prisma.inquiriesCreateWithoutProfiles_inquiries_sender_idToprofilesInput[] | Prisma.inquiriesUncheckedCreateWithoutProfiles_inquiries_sender_idToprofilesInput[]
  connectOrCreate?: Prisma.inquiriesCreateOrConnectWithoutProfiles_inquiries_sender_idToprofilesInput | Prisma.inquiriesCreateOrConnectWithoutProfiles_inquiries_sender_idToprofilesInput[]
  upsert?: Prisma.inquiriesUpsertWithWhereUniqueWithoutProfiles_inquiries_sender_idToprofilesInput | Prisma.inquiriesUpsertWithWhereUniqueWithoutProfiles_inquiries_sender_idToprofilesInput[]
  createMany?: Prisma.inquiriesCreateManyProfiles_inquiries_sender_idToprofilesInputEnvelope
  set?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
  disconnect?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
  delete?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
  connect?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
  update?: Prisma.inquiriesUpdateWithWhereUniqueWithoutProfiles_inquiries_sender_idToprofilesInput | Prisma.inquiriesUpdateWithWhereUniqueWithoutProfiles_inquiries_sender_idToprofilesInput[]
  updateMany?: Prisma.inquiriesUpdateManyWithWhereWithoutProfiles_inquiries_sender_idToprofilesInput | Prisma.inquiriesUpdateManyWithWhereWithoutProfiles_inquiries_sender_idToprofilesInput[]
  deleteMany?: Prisma.inquiriesScalarWhereInput | Prisma.inquiriesScalarWhereInput[]
}

export type inquiriesUncheckedUpdateManyWithoutProfiles_inquiries_owner_idToprofilesNestedInput = {
  create?: Prisma.XOR<Prisma.inquiriesCreateWithoutProfiles_inquiries_owner_idToprofilesInput, Prisma.inquiriesUncheckedCreateWithoutProfiles_inquiries_owner_idToprofilesInput> | Prisma.inquiriesCreateWithoutProfiles_inquiries_owner_idToprofilesInput[] | Prisma.inquiriesUncheckedCreateWithoutProfiles_inquiries_owner_idToprofilesInput[]
  connectOrCreate?: Prisma.inquiriesCreateOrConnectWithoutProfiles_inquiries_owner_idToprofilesInput | Prisma.inquiriesCreateOrConnectWithoutProfiles_inquiries_owner_idToprofilesInput[]
  upsert?: Prisma.inquiriesUpsertWithWhereUniqueWithoutProfiles_inquiries_owner_idToprofilesInput | Prisma.inquiriesUpsertWithWhereUniqueWithoutProfiles_inquiries_owner_idToprofilesInput[]
  createMany?: Prisma.inquiriesCreateManyProfiles_inquiries_owner_idToprofilesInputEnvelope
  set?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
  disconnect?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
  delete?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
  connect?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
  update?: Prisma.inquiriesUpdateWithWhereUniqueWithoutProfiles_inquiries_owner_idToprofilesInput | Prisma.inquiriesUpdateWithWhereUniqueWithoutProfiles_inquiries_owner_idToprofilesInput[]
  updateMany?: Prisma.inquiriesUpdateManyWithWhereWithoutProfiles_inquiries_owner_idToprofilesInput | Prisma.inquiriesUpdateManyWithWhereWithoutProfiles_inquiries_owner_idToprofilesInput[]
  deleteMany?: Prisma.inquiriesScalarWhereInput | Prisma.inquiriesScalarWhereInput[]
}

export type inquiriesUncheckedUpdateManyWithoutProfiles_inquiries_sender_idToprofilesNestedInput = {
  create?: Prisma.XOR<Prisma.inquiriesCreateWithoutProfiles_inquiries_sender_idToprofilesInput, Prisma.inquiriesUncheckedCreateWithoutProfiles_inquiries_sender_idToprofilesInput> | Prisma.inquiriesCreateWithoutProfiles_inquiries_sender_idToprofilesInput[] | Prisma.inquiriesUncheckedCreateWithoutProfiles_inquiries_sender_idToprofilesInput[]
  connectOrCreate?: Prisma.inquiriesCreateOrConnectWithoutProfiles_inquiries_sender_idToprofilesInput | Prisma.inquiriesCreateOrConnectWithoutProfiles_inquiries_sender_idToprofilesInput[]
  upsert?: Prisma.inquiriesUpsertWithWhereUniqueWithoutProfiles_inquiries_sender_idToprofilesInput | Prisma.inquiriesUpsertWithWhereUniqueWithoutProfiles_inquiries_sender_idToprofilesInput[]
  createMany?: Prisma.inquiriesCreateManyProfiles_inquiries_sender_idToprofilesInputEnvelope
  set?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
  disconnect?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
  delete?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
  connect?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
  update?: Prisma.inquiriesUpdateWithWhereUniqueWithoutProfiles_inquiries_sender_idToprofilesInput | Prisma.inquiriesUpdateWithWhereUniqueWithoutProfiles_inquiries_sender_idToprofilesInput[]
  updateMany?: Prisma.inquiriesUpdateManyWithWhereWithoutProfiles_inquiries_sender_idToprofilesInput | Prisma.inquiriesUpdateManyWithWhereWithoutProfiles_inquiries_sender_idToprofilesInput[]
  deleteMany?: Prisma.inquiriesScalarWhereInput | Prisma.inquiriesScalarWhereInput[]
}

export type inquiriesCreateNestedManyWithoutPropertiesInput = {
  create?: Prisma.XOR<Prisma.inquiriesCreateWithoutPropertiesInput, Prisma.inquiriesUncheckedCreateWithoutPropertiesInput> | Prisma.inquiriesCreateWithoutPropertiesInput[] | Prisma.inquiriesUncheckedCreateWithoutPropertiesInput[]
  connectOrCreate?: Prisma.inquiriesCreateOrConnectWithoutPropertiesInput | Prisma.inquiriesCreateOrConnectWithoutPropertiesInput[]
  createMany?: Prisma.inquiriesCreateManyPropertiesInputEnvelope
  connect?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
}

export type inquiriesUncheckedCreateNestedManyWithoutPropertiesInput = {
  create?: Prisma.XOR<Prisma.inquiriesCreateWithoutPropertiesInput, Prisma.inquiriesUncheckedCreateWithoutPropertiesInput> | Prisma.inquiriesCreateWithoutPropertiesInput[] | Prisma.inquiriesUncheckedCreateWithoutPropertiesInput[]
  connectOrCreate?: Prisma.inquiriesCreateOrConnectWithoutPropertiesInput | Prisma.inquiriesCreateOrConnectWithoutPropertiesInput[]
  createMany?: Prisma.inquiriesCreateManyPropertiesInputEnvelope
  connect?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
}

export type inquiriesUpdateManyWithoutPropertiesNestedInput = {
  create?: Prisma.XOR<Prisma.inquiriesCreateWithoutPropertiesInput, Prisma.inquiriesUncheckedCreateWithoutPropertiesInput> | Prisma.inquiriesCreateWithoutPropertiesInput[] | Prisma.inquiriesUncheckedCreateWithoutPropertiesInput[]
  connectOrCreate?: Prisma.inquiriesCreateOrConnectWithoutPropertiesInput | Prisma.inquiriesCreateOrConnectWithoutPropertiesInput[]
  upsert?: Prisma.inquiriesUpsertWithWhereUniqueWithoutPropertiesInput | Prisma.inquiriesUpsertWithWhereUniqueWithoutPropertiesInput[]
  createMany?: Prisma.inquiriesCreateManyPropertiesInputEnvelope
  set?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
  disconnect?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
  delete?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
  connect?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
  update?: Prisma.inquiriesUpdateWithWhereUniqueWithoutPropertiesInput | Prisma.inquiriesUpdateWithWhereUniqueWithoutPropertiesInput[]
  updateMany?: Prisma.inquiriesUpdateManyWithWhereWithoutPropertiesInput | Prisma.inquiriesUpdateManyWithWhereWithoutPropertiesInput[]
  deleteMany?: Prisma.inquiriesScalarWhereInput | Prisma.inquiriesScalarWhereInput[]
}

export type inquiriesUncheckedUpdateManyWithoutPropertiesNestedInput = {
  create?: Prisma.XOR<Prisma.inquiriesCreateWithoutPropertiesInput, Prisma.inquiriesUncheckedCreateWithoutPropertiesInput> | Prisma.inquiriesCreateWithoutPropertiesInput[] | Prisma.inquiriesUncheckedCreateWithoutPropertiesInput[]
  connectOrCreate?: Prisma.inquiriesCreateOrConnectWithoutPropertiesInput | Prisma.inquiriesCreateOrConnectWithoutPropertiesInput[]
  upsert?: Prisma.inquiriesUpsertWithWhereUniqueWithoutPropertiesInput | Prisma.inquiriesUpsertWithWhereUniqueWithoutPropertiesInput[]
  createMany?: Prisma.inquiriesCreateManyPropertiesInputEnvelope
  set?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
  disconnect?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
  delete?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
  connect?: Prisma.inquiriesWhereUniqueInput | Prisma.inquiriesWhereUniqueInput[]
  update?: Prisma.inquiriesUpdateWithWhereUniqueWithoutPropertiesInput | Prisma.inquiriesUpdateWithWhereUniqueWithoutPropertiesInput[]
  updateMany?: Prisma.inquiriesUpdateManyWithWhereWithoutPropertiesInput | Prisma.inquiriesUpdateManyWithWhereWithoutPropertiesInput[]
  deleteMany?: Prisma.inquiriesScalarWhereInput | Prisma.inquiriesScalarWhereInput[]
}

export type inquiriesCreateWithoutProfiles_inquiries_owner_idToprofilesInput = {
  id?: string
  message: string
  status?: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
  properties: Prisma.propertiesCreateNestedOneWithoutInquiriesInput
  profiles_inquiries_sender_idToprofiles: Prisma.profilesCreateNestedOneWithoutInquiries_inquiries_sender_idToprofilesInput
}

export type inquiriesUncheckedCreateWithoutProfiles_inquiries_owner_idToprofilesInput = {
  id?: string
  property_id: string
  sender_id: string
  message: string
  status?: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type inquiriesCreateOrConnectWithoutProfiles_inquiries_owner_idToprofilesInput = {
  where: Prisma.inquiriesWhereUniqueInput
  create: Prisma.XOR<Prisma.inquiriesCreateWithoutProfiles_inquiries_owner_idToprofilesInput, Prisma.inquiriesUncheckedCreateWithoutProfiles_inquiries_owner_idToprofilesInput>
}

export type inquiriesCreateManyProfiles_inquiries_owner_idToprofilesInputEnvelope = {
  data: Prisma.inquiriesCreateManyProfiles_inquiries_owner_idToprofilesInput | Prisma.inquiriesCreateManyProfiles_inquiries_owner_idToprofilesInput[]
  skipDuplicates?: boolean
}

export type inquiriesCreateWithoutProfiles_inquiries_sender_idToprofilesInput = {
  id?: string
  message: string
  status?: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
  profiles_inquiries_owner_idToprofiles: Prisma.profilesCreateNestedOneWithoutInquiries_inquiries_owner_idToprofilesInput
  properties: Prisma.propertiesCreateNestedOneWithoutInquiriesInput
}

export type inquiriesUncheckedCreateWithoutProfiles_inquiries_sender_idToprofilesInput = {
  id?: string
  property_id: string
  owner_id: string
  message: string
  status?: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type inquiriesCreateOrConnectWithoutProfiles_inquiries_sender_idToprofilesInput = {
  where: Prisma.inquiriesWhereUniqueInput
  create: Prisma.XOR<Prisma.inquiriesCreateWithoutProfiles_inquiries_sender_idToprofilesInput, Prisma.inquiriesUncheckedCreateWithoutProfiles_inquiries_sender_idToprofilesInput>
}

export type inquiriesCreateManyProfiles_inquiries_sender_idToprofilesInputEnvelope = {
  data: Prisma.inquiriesCreateManyProfiles_inquiries_sender_idToprofilesInput | Prisma.inquiriesCreateManyProfiles_inquiries_sender_idToprofilesInput[]
  skipDuplicates?: boolean
}

export type inquiriesUpsertWithWhereUniqueWithoutProfiles_inquiries_owner_idToprofilesInput = {
  where: Prisma.inquiriesWhereUniqueInput
  update: Prisma.XOR<Prisma.inquiriesUpdateWithoutProfiles_inquiries_owner_idToprofilesInput, Prisma.inquiriesUncheckedUpdateWithoutProfiles_inquiries_owner_idToprofilesInput>
  create: Prisma.XOR<Prisma.inquiriesCreateWithoutProfiles_inquiries_owner_idToprofilesInput, Prisma.inquiriesUncheckedCreateWithoutProfiles_inquiries_owner_idToprofilesInput>
}

export type inquiriesUpdateWithWhereUniqueWithoutProfiles_inquiries_owner_idToprofilesInput = {
  where: Prisma.inquiriesWhereUniqueInput
  data: Prisma.XOR<Prisma.inquiriesUpdateWithoutProfiles_inquiries_owner_idToprofilesInput, Prisma.inquiriesUncheckedUpdateWithoutProfiles_inquiries_owner_idToprofilesInput>
}

export type inquiriesUpdateManyWithWhereWithoutProfiles_inquiries_owner_idToprofilesInput = {
  where: Prisma.inquiriesScalarWhereInput
  data: Prisma.XOR<Prisma.inquiriesUpdateManyMutationInput, Prisma.inquiriesUncheckedUpdateManyWithoutProfiles_inquiries_owner_idToprofilesInput>
}

export type inquiriesScalarWhereInput = {
  AND?: Prisma.inquiriesScalarWhereInput | Prisma.inquiriesScalarWhereInput[]
  OR?: Prisma.inquiriesScalarWhereInput[]
  NOT?: Prisma.inquiriesScalarWhereInput | Prisma.inquiriesScalarWhereInput[]
  id?: Prisma.UuidFilter<"inquiries"> | string
  property_id?: Prisma.UuidFilter<"inquiries"> | string
  sender_id?: Prisma.UuidFilter<"inquiries"> | string
  owner_id?: Prisma.UuidFilter<"inquiries"> | string
  message?: Prisma.StringFilter<"inquiries"> | string
  status?: Prisma.StringFilter<"inquiries"> | string
  created_at?: Prisma.DateTimeNullableFilter<"inquiries"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"inquiries"> | Date | string | null
}

export type inquiriesUpsertWithWhereUniqueWithoutProfiles_inquiries_sender_idToprofilesInput = {
  where: Prisma.inquiriesWhereUniqueInput
  update: Prisma.XOR<Prisma.inquiriesUpdateWithoutProfiles_inquiries_sender_idToprofilesInput, Prisma.inquiriesUncheckedUpdateWithoutProfiles_inquiries_sender_idToprofilesInput>
  create: Prisma.XOR<Prisma.inquiriesCreateWithoutProfiles_inquiries_sender_idToprofilesInput, Prisma.inquiriesUncheckedCreateWithoutProfiles_inquiries_sender_idToprofilesInput>
}

export type inquiriesUpdateWithWhereUniqueWithoutProfiles_inquiries_sender_idToprofilesInput = {
  where: Prisma.inquiriesWhereUniqueInput
  data: Prisma.XOR<Prisma.inquiriesUpdateWithoutProfiles_inquiries_sender_idToprofilesInput, Prisma.inquiriesUncheckedUpdateWithoutProfiles_inquiries_sender_idToprofilesInput>
}

export type inquiriesUpdateManyWithWhereWithoutProfiles_inquiries_sender_idToprofilesInput = {
  where: Prisma.inquiriesScalarWhereInput
  data: Prisma.XOR<Prisma.inquiriesUpdateManyMutationInput, Prisma.inquiriesUncheckedUpdateManyWithoutProfiles_inquiries_sender_idToprofilesInput>
}

export type inquiriesCreateWithoutPropertiesInput = {
  id?: string
  message: string
  status?: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
  profiles_inquiries_owner_idToprofiles: Prisma.profilesCreateNestedOneWithoutInquiries_inquiries_owner_idToprofilesInput
  profiles_inquiries_sender_idToprofiles: Prisma.profilesCreateNestedOneWithoutInquiries_inquiries_sender_idToprofilesInput
}

export type inquiriesUncheckedCreateWithoutPropertiesInput = {
  id?: string
  sender_id: string
  owner_id: string
  message: string
  status?: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type inquiriesCreateOrConnectWithoutPropertiesInput = {
  where: Prisma.inquiriesWhereUniqueInput
  create: Prisma.XOR<Prisma.inquiriesCreateWithoutPropertiesInput, Prisma.inquiriesUncheckedCreateWithoutPropertiesInput>
}

export type inquiriesCreateManyPropertiesInputEnvelope = {
  data: Prisma.inquiriesCreateManyPropertiesInput | Prisma.inquiriesCreateManyPropertiesInput[]
  skipDuplicates?: boolean
}

export type inquiriesUpsertWithWhereUniqueWithoutPropertiesInput = {
  where: Prisma.inquiriesWhereUniqueInput
  update: Prisma.XOR<Prisma.inquiriesUpdateWithoutPropertiesInput, Prisma.inquiriesUncheckedUpdateWithoutPropertiesInput>
  create: Prisma.XOR<Prisma.inquiriesCreateWithoutPropertiesInput, Prisma.inquiriesUncheckedCreateWithoutPropertiesInput>
}

export type inquiriesUpdateWithWhereUniqueWithoutPropertiesInput = {
  where: Prisma.inquiriesWhereUniqueInput
  data: Prisma.XOR<Prisma.inquiriesUpdateWithoutPropertiesInput, Prisma.inquiriesUncheckedUpdateWithoutPropertiesInput>
}

export type inquiriesUpdateManyWithWhereWithoutPropertiesInput = {
  where: Prisma.inquiriesScalarWhereInput
  data: Prisma.XOR<Prisma.inquiriesUpdateManyMutationInput, Prisma.inquiriesUncheckedUpdateManyWithoutPropertiesInput>
}

export type inquiriesCreateManyProfiles_inquiries_owner_idToprofilesInput = {
  id?: string
  property_id: string
  sender_id: string
  message: string
  status?: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type inquiriesCreateManyProfiles_inquiries_sender_idToprofilesInput = {
  id?: string
  property_id: string
  owner_id: string
  message: string
  status?: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type inquiriesUpdateWithoutProfiles_inquiries_owner_idToprofilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  properties?: Prisma.propertiesUpdateOneRequiredWithoutInquiriesNestedInput
  profiles_inquiries_sender_idToprofiles?: Prisma.profilesUpdateOneRequiredWithoutInquiries_inquiries_sender_idToprofilesNestedInput
}

export type inquiriesUncheckedUpdateWithoutProfiles_inquiries_owner_idToprofilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  property_id?: Prisma.StringFieldUpdateOperationsInput | string
  sender_id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type inquiriesUncheckedUpdateManyWithoutProfiles_inquiries_owner_idToprofilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  property_id?: Prisma.StringFieldUpdateOperationsInput | string
  sender_id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type inquiriesUpdateWithoutProfiles_inquiries_sender_idToprofilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  profiles_inquiries_owner_idToprofiles?: Prisma.profilesUpdateOneRequiredWithoutInquiries_inquiries_owner_idToprofilesNestedInput
  properties?: Prisma.propertiesUpdateOneRequiredWithoutInquiriesNestedInput
}

export type inquiriesUncheckedUpdateWithoutProfiles_inquiries_sender_idToprofilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  property_id?: Prisma.StringFieldUpdateOperationsInput | string
  owner_id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type inquiriesUncheckedUpdateManyWithoutProfiles_inquiries_sender_idToprofilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  property_id?: Prisma.StringFieldUpdateOperationsInput | string
  owner_id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type inquiriesCreateManyPropertiesInput = {
  id?: string
  sender_id: string
  owner_id: string
  message: string
  status?: string
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type inquiriesUpdateWithoutPropertiesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  profiles_inquiries_owner_idToprofiles?: Prisma.profilesUpdateOneRequiredWithoutInquiries_inquiries_owner_idToprofilesNestedInput
  profiles_inquiries_sender_idToprofiles?: Prisma.profilesUpdateOneRequiredWithoutInquiries_inquiries_sender_idToprofilesNestedInput
}

export type inquiriesUncheckedUpdateWithoutPropertiesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sender_id?: Prisma.StringFieldUpdateOperationsInput | string
  owner_id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type inquiriesUncheckedUpdateManyWithoutPropertiesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sender_id?: Prisma.StringFieldUpdateOperationsInput | string
  owner_id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type inquiriesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  property_id?: boolean
  sender_id?: boolean
  owner_id?: boolean
  message?: boolean
  status?: boolean
  created_at?: boolean
  updated_at?: boolean
  profiles_inquiries_owner_idToprofiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
  properties?: boolean | Prisma.propertiesDefaultArgs<ExtArgs>
  profiles_inquiries_sender_idToprofiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["inquiries"]>

export type inquiriesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  property_id?: boolean
  sender_id?: boolean
  owner_id?: boolean
  message?: boolean
  status?: boolean
  created_at?: boolean
  updated_at?: boolean
  profiles_inquiries_owner_idToprofiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
  properties?: boolean | Prisma.propertiesDefaultArgs<ExtArgs>
  profiles_inquiries_sender_idToprofiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["inquiries"]>

export type inquiriesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  property_id?: boolean
  sender_id?: boolean
  owner_id?: boolean
  message?: boolean
  status?: boolean
  created_at?: boolean
  updated_at?: boolean
  profiles_inquiries_owner_idToprofiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
  properties?: boolean | Prisma.propertiesDefaultArgs<ExtArgs>
  profiles_inquiries_sender_idToprofiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["inquiries"]>

export type inquiriesSelectScalar = {
  id?: boolean
  property_id?: boolean
  sender_id?: boolean
  owner_id?: boolean
  message?: boolean
  status?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type inquiriesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "property_id" | "sender_id" | "owner_id" | "message" | "status" | "created_at" | "updated_at", ExtArgs["result"]["inquiries"]>
export type inquiriesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profiles_inquiries_owner_idToprofiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
  properties?: boolean | Prisma.propertiesDefaultArgs<ExtArgs>
  profiles_inquiries_sender_idToprofiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
}
export type inquiriesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profiles_inquiries_owner_idToprofiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
  properties?: boolean | Prisma.propertiesDefaultArgs<ExtArgs>
  profiles_inquiries_sender_idToprofiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
}
export type inquiriesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profiles_inquiries_owner_idToprofiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
  properties?: boolean | Prisma.propertiesDefaultArgs<ExtArgs>
  profiles_inquiries_sender_idToprofiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
}

export type $inquiriesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "inquiries"
  objects: {
    profiles_inquiries_owner_idToprofiles: Prisma.$profilesPayload<ExtArgs>
    properties: Prisma.$propertiesPayload<ExtArgs>
    profiles_inquiries_sender_idToprofiles: Prisma.$profilesPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    property_id: string
    sender_id: string
    owner_id: string
    message: string
    status: string
    created_at: Date | null
    updated_at: Date | null
  }, ExtArgs["result"]["inquiries"]>
  composites: {}
}

export type inquiriesGetPayload<S extends boolean | null | undefined | inquiriesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$inquiriesPayload, S>

export type inquiriesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<inquiriesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: InquiriesCountAggregateInputType | true
  }

export interface inquiriesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['inquiries'], meta: { name: 'inquiries' } }
  /**
   * Find zero or one Inquiries that matches the filter.
   * @param {inquiriesFindUniqueArgs} args - Arguments to find a Inquiries
   * @example
   * // Get one Inquiries
   * const inquiries = await prisma.inquiries.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends inquiriesFindUniqueArgs>(args: Prisma.SelectSubset<T, inquiriesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__inquiriesClient<runtime.Types.Result.GetResult<Prisma.$inquiriesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Inquiries that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {inquiriesFindUniqueOrThrowArgs} args - Arguments to find a Inquiries
   * @example
   * // Get one Inquiries
   * const inquiries = await prisma.inquiries.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends inquiriesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, inquiriesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__inquiriesClient<runtime.Types.Result.GetResult<Prisma.$inquiriesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Inquiries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {inquiriesFindFirstArgs} args - Arguments to find a Inquiries
   * @example
   * // Get one Inquiries
   * const inquiries = await prisma.inquiries.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends inquiriesFindFirstArgs>(args?: Prisma.SelectSubset<T, inquiriesFindFirstArgs<ExtArgs>>): Prisma.Prisma__inquiriesClient<runtime.Types.Result.GetResult<Prisma.$inquiriesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Inquiries that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {inquiriesFindFirstOrThrowArgs} args - Arguments to find a Inquiries
   * @example
   * // Get one Inquiries
   * const inquiries = await prisma.inquiries.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends inquiriesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, inquiriesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__inquiriesClient<runtime.Types.Result.GetResult<Prisma.$inquiriesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Inquiries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {inquiriesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Inquiries
   * const inquiries = await prisma.inquiries.findMany()
   * 
   * // Get first 10 Inquiries
   * const inquiries = await prisma.inquiries.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const inquiriesWithIdOnly = await prisma.inquiries.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends inquiriesFindManyArgs>(args?: Prisma.SelectSubset<T, inquiriesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$inquiriesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Inquiries.
   * @param {inquiriesCreateArgs} args - Arguments to create a Inquiries.
   * @example
   * // Create one Inquiries
   * const Inquiries = await prisma.inquiries.create({
   *   data: {
   *     // ... data to create a Inquiries
   *   }
   * })
   * 
   */
  create<T extends inquiriesCreateArgs>(args: Prisma.SelectSubset<T, inquiriesCreateArgs<ExtArgs>>): Prisma.Prisma__inquiriesClient<runtime.Types.Result.GetResult<Prisma.$inquiriesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Inquiries.
   * @param {inquiriesCreateManyArgs} args - Arguments to create many Inquiries.
   * @example
   * // Create many Inquiries
   * const inquiries = await prisma.inquiries.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends inquiriesCreateManyArgs>(args?: Prisma.SelectSubset<T, inquiriesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Inquiries and returns the data saved in the database.
   * @param {inquiriesCreateManyAndReturnArgs} args - Arguments to create many Inquiries.
   * @example
   * // Create many Inquiries
   * const inquiries = await prisma.inquiries.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Inquiries and only return the `id`
   * const inquiriesWithIdOnly = await prisma.inquiries.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends inquiriesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, inquiriesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$inquiriesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Inquiries.
   * @param {inquiriesDeleteArgs} args - Arguments to delete one Inquiries.
   * @example
   * // Delete one Inquiries
   * const Inquiries = await prisma.inquiries.delete({
   *   where: {
   *     // ... filter to delete one Inquiries
   *   }
   * })
   * 
   */
  delete<T extends inquiriesDeleteArgs>(args: Prisma.SelectSubset<T, inquiriesDeleteArgs<ExtArgs>>): Prisma.Prisma__inquiriesClient<runtime.Types.Result.GetResult<Prisma.$inquiriesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Inquiries.
   * @param {inquiriesUpdateArgs} args - Arguments to update one Inquiries.
   * @example
   * // Update one Inquiries
   * const inquiries = await prisma.inquiries.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends inquiriesUpdateArgs>(args: Prisma.SelectSubset<T, inquiriesUpdateArgs<ExtArgs>>): Prisma.Prisma__inquiriesClient<runtime.Types.Result.GetResult<Prisma.$inquiriesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Inquiries.
   * @param {inquiriesDeleteManyArgs} args - Arguments to filter Inquiries to delete.
   * @example
   * // Delete a few Inquiries
   * const { count } = await prisma.inquiries.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends inquiriesDeleteManyArgs>(args?: Prisma.SelectSubset<T, inquiriesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Inquiries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {inquiriesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Inquiries
   * const inquiries = await prisma.inquiries.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends inquiriesUpdateManyArgs>(args: Prisma.SelectSubset<T, inquiriesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Inquiries and returns the data updated in the database.
   * @param {inquiriesUpdateManyAndReturnArgs} args - Arguments to update many Inquiries.
   * @example
   * // Update many Inquiries
   * const inquiries = await prisma.inquiries.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Inquiries and only return the `id`
   * const inquiriesWithIdOnly = await prisma.inquiries.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends inquiriesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, inquiriesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$inquiriesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Inquiries.
   * @param {inquiriesUpsertArgs} args - Arguments to update or create a Inquiries.
   * @example
   * // Update or create a Inquiries
   * const inquiries = await prisma.inquiries.upsert({
   *   create: {
   *     // ... data to create a Inquiries
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Inquiries we want to update
   *   }
   * })
   */
  upsert<T extends inquiriesUpsertArgs>(args: Prisma.SelectSubset<T, inquiriesUpsertArgs<ExtArgs>>): Prisma.Prisma__inquiriesClient<runtime.Types.Result.GetResult<Prisma.$inquiriesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Inquiries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {inquiriesCountArgs} args - Arguments to filter Inquiries to count.
   * @example
   * // Count the number of Inquiries
   * const count = await prisma.inquiries.count({
   *   where: {
   *     // ... the filter for the Inquiries we want to count
   *   }
   * })
  **/
  count<T extends inquiriesCountArgs>(
    args?: Prisma.Subset<T, inquiriesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], InquiriesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Inquiries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InquiriesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends InquiriesAggregateArgs>(args: Prisma.Subset<T, InquiriesAggregateArgs>): Prisma.PrismaPromise<GetInquiriesAggregateType<T>>

  /**
   * Group by Inquiries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {inquiriesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends inquiriesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: inquiriesGroupByArgs['orderBy'] }
      : { orderBy?: inquiriesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, inquiriesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetInquiriesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the inquiries model
 */
readonly fields: inquiriesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for inquiries.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__inquiriesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  profiles_inquiries_owner_idToprofiles<T extends Prisma.profilesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.profilesDefaultArgs<ExtArgs>>): Prisma.Prisma__profilesClient<runtime.Types.Result.GetResult<Prisma.$profilesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  properties<T extends Prisma.propertiesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.propertiesDefaultArgs<ExtArgs>>): Prisma.Prisma__propertiesClient<runtime.Types.Result.GetResult<Prisma.$propertiesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  profiles_inquiries_sender_idToprofiles<T extends Prisma.profilesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.profilesDefaultArgs<ExtArgs>>): Prisma.Prisma__profilesClient<runtime.Types.Result.GetResult<Prisma.$profilesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the inquiries model
 */
export interface inquiriesFieldRefs {
  readonly id: Prisma.FieldRef<"inquiries", 'String'>
  readonly property_id: Prisma.FieldRef<"inquiries", 'String'>
  readonly sender_id: Prisma.FieldRef<"inquiries", 'String'>
  readonly owner_id: Prisma.FieldRef<"inquiries", 'String'>
  readonly message: Prisma.FieldRef<"inquiries", 'String'>
  readonly status: Prisma.FieldRef<"inquiries", 'String'>
  readonly created_at: Prisma.FieldRef<"inquiries", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"inquiries", 'DateTime'>
}
    

// Custom InputTypes
/**
 * inquiries findUnique
 */
export type inquiriesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inquiries
   */
  select?: Prisma.inquiriesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the inquiries
   */
  omit?: Prisma.inquiriesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inquiriesInclude<ExtArgs> | null
  /**
   * Filter, which inquiries to fetch.
   */
  where: Prisma.inquiriesWhereUniqueInput
}

/**
 * inquiries findUniqueOrThrow
 */
export type inquiriesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inquiries
   */
  select?: Prisma.inquiriesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the inquiries
   */
  omit?: Prisma.inquiriesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inquiriesInclude<ExtArgs> | null
  /**
   * Filter, which inquiries to fetch.
   */
  where: Prisma.inquiriesWhereUniqueInput
}

/**
 * inquiries findFirst
 */
export type inquiriesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inquiries
   */
  select?: Prisma.inquiriesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the inquiries
   */
  omit?: Prisma.inquiriesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inquiriesInclude<ExtArgs> | null
  /**
   * Filter, which inquiries to fetch.
   */
  where?: Prisma.inquiriesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of inquiries to fetch.
   */
  orderBy?: Prisma.inquiriesOrderByWithRelationInput | Prisma.inquiriesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for inquiries.
   */
  cursor?: Prisma.inquiriesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` inquiries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` inquiries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of inquiries.
   */
  distinct?: Prisma.InquiriesScalarFieldEnum | Prisma.InquiriesScalarFieldEnum[]
}

/**
 * inquiries findFirstOrThrow
 */
export type inquiriesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inquiries
   */
  select?: Prisma.inquiriesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the inquiries
   */
  omit?: Prisma.inquiriesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inquiriesInclude<ExtArgs> | null
  /**
   * Filter, which inquiries to fetch.
   */
  where?: Prisma.inquiriesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of inquiries to fetch.
   */
  orderBy?: Prisma.inquiriesOrderByWithRelationInput | Prisma.inquiriesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for inquiries.
   */
  cursor?: Prisma.inquiriesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` inquiries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` inquiries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of inquiries.
   */
  distinct?: Prisma.InquiriesScalarFieldEnum | Prisma.InquiriesScalarFieldEnum[]
}

/**
 * inquiries findMany
 */
export type inquiriesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inquiries
   */
  select?: Prisma.inquiriesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the inquiries
   */
  omit?: Prisma.inquiriesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inquiriesInclude<ExtArgs> | null
  /**
   * Filter, which inquiries to fetch.
   */
  where?: Prisma.inquiriesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of inquiries to fetch.
   */
  orderBy?: Prisma.inquiriesOrderByWithRelationInput | Prisma.inquiriesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing inquiries.
   */
  cursor?: Prisma.inquiriesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` inquiries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` inquiries.
   */
  skip?: number
  distinct?: Prisma.InquiriesScalarFieldEnum | Prisma.InquiriesScalarFieldEnum[]
}

/**
 * inquiries create
 */
export type inquiriesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inquiries
   */
  select?: Prisma.inquiriesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the inquiries
   */
  omit?: Prisma.inquiriesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inquiriesInclude<ExtArgs> | null
  /**
   * The data needed to create a inquiries.
   */
  data: Prisma.XOR<Prisma.inquiriesCreateInput, Prisma.inquiriesUncheckedCreateInput>
}

/**
 * inquiries createMany
 */
export type inquiriesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many inquiries.
   */
  data: Prisma.inquiriesCreateManyInput | Prisma.inquiriesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * inquiries createManyAndReturn
 */
export type inquiriesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inquiries
   */
  select?: Prisma.inquiriesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the inquiries
   */
  omit?: Prisma.inquiriesOmit<ExtArgs> | null
  /**
   * The data used to create many inquiries.
   */
  data: Prisma.inquiriesCreateManyInput | Prisma.inquiriesCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inquiriesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * inquiries update
 */
export type inquiriesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inquiries
   */
  select?: Prisma.inquiriesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the inquiries
   */
  omit?: Prisma.inquiriesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inquiriesInclude<ExtArgs> | null
  /**
   * The data needed to update a inquiries.
   */
  data: Prisma.XOR<Prisma.inquiriesUpdateInput, Prisma.inquiriesUncheckedUpdateInput>
  /**
   * Choose, which inquiries to update.
   */
  where: Prisma.inquiriesWhereUniqueInput
}

/**
 * inquiries updateMany
 */
export type inquiriesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update inquiries.
   */
  data: Prisma.XOR<Prisma.inquiriesUpdateManyMutationInput, Prisma.inquiriesUncheckedUpdateManyInput>
  /**
   * Filter which inquiries to update
   */
  where?: Prisma.inquiriesWhereInput
  /**
   * Limit how many inquiries to update.
   */
  limit?: number
}

/**
 * inquiries updateManyAndReturn
 */
export type inquiriesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inquiries
   */
  select?: Prisma.inquiriesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the inquiries
   */
  omit?: Prisma.inquiriesOmit<ExtArgs> | null
  /**
   * The data used to update inquiries.
   */
  data: Prisma.XOR<Prisma.inquiriesUpdateManyMutationInput, Prisma.inquiriesUncheckedUpdateManyInput>
  /**
   * Filter which inquiries to update
   */
  where?: Prisma.inquiriesWhereInput
  /**
   * Limit how many inquiries to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inquiriesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * inquiries upsert
 */
export type inquiriesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inquiries
   */
  select?: Prisma.inquiriesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the inquiries
   */
  omit?: Prisma.inquiriesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inquiriesInclude<ExtArgs> | null
  /**
   * The filter to search for the inquiries to update in case it exists.
   */
  where: Prisma.inquiriesWhereUniqueInput
  /**
   * In case the inquiries found by the `where` argument doesn't exist, create a new inquiries with this data.
   */
  create: Prisma.XOR<Prisma.inquiriesCreateInput, Prisma.inquiriesUncheckedCreateInput>
  /**
   * In case the inquiries was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.inquiriesUpdateInput, Prisma.inquiriesUncheckedUpdateInput>
}

/**
 * inquiries delete
 */
export type inquiriesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inquiries
   */
  select?: Prisma.inquiriesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the inquiries
   */
  omit?: Prisma.inquiriesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inquiriesInclude<ExtArgs> | null
  /**
   * Filter which inquiries to delete.
   */
  where: Prisma.inquiriesWhereUniqueInput
}

/**
 * inquiries deleteMany
 */
export type inquiriesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which inquiries to delete
   */
  where?: Prisma.inquiriesWhereInput
  /**
   * Limit how many inquiries to delete.
   */
  limit?: number
}

/**
 * inquiries without action
 */
export type inquiriesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the inquiries
   */
  select?: Prisma.inquiriesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the inquiries
   */
  omit?: Prisma.inquiriesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.inquiriesInclude<ExtArgs> | null
}
