
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `kyc_requests` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model kyc_requests
 * This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
 * This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info.
 */
export type kyc_requestsModel = runtime.Types.Result.DefaultSelection<Prisma.$kyc_requestsPayload>

export type AggregateKyc_requests = {
  _count: Kyc_requestsCountAggregateOutputType | null
  _min: Kyc_requestsMinAggregateOutputType | null
  _max: Kyc_requestsMaxAggregateOutputType | null
}

export type Kyc_requestsMinAggregateOutputType = {
  id: string | null
  user_id: string | null
  user_type: string | null
  status: string | null
  kyc_provider: string | null
  kyc_reference_id: string | null
  submitted_at: Date | null
  approved_at: Date | null
  rejected_at: Date | null
  rejection_reason: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Kyc_requestsMaxAggregateOutputType = {
  id: string | null
  user_id: string | null
  user_type: string | null
  status: string | null
  kyc_provider: string | null
  kyc_reference_id: string | null
  submitted_at: Date | null
  approved_at: Date | null
  rejected_at: Date | null
  rejection_reason: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type Kyc_requestsCountAggregateOutputType = {
  id: number
  user_id: number
  user_type: number
  status: number
  kyc_provider: number
  kyc_reference_id: number
  documents: number
  submitted_at: number
  approved_at: number
  rejected_at: number
  rejection_reason: number
  created_at: number
  updated_at: number
  _all: number
}


export type Kyc_requestsMinAggregateInputType = {
  id?: true
  user_id?: true
  user_type?: true
  status?: true
  kyc_provider?: true
  kyc_reference_id?: true
  submitted_at?: true
  approved_at?: true
  rejected_at?: true
  rejection_reason?: true
  created_at?: true
  updated_at?: true
}

export type Kyc_requestsMaxAggregateInputType = {
  id?: true
  user_id?: true
  user_type?: true
  status?: true
  kyc_provider?: true
  kyc_reference_id?: true
  submitted_at?: true
  approved_at?: true
  rejected_at?: true
  rejection_reason?: true
  created_at?: true
  updated_at?: true
}

export type Kyc_requestsCountAggregateInputType = {
  id?: true
  user_id?: true
  user_type?: true
  status?: true
  kyc_provider?: true
  kyc_reference_id?: true
  documents?: true
  submitted_at?: true
  approved_at?: true
  rejected_at?: true
  rejection_reason?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type Kyc_requestsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which kyc_requests to aggregate.
   */
  where?: Prisma.kyc_requestsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of kyc_requests to fetch.
   */
  orderBy?: Prisma.kyc_requestsOrderByWithRelationInput | Prisma.kyc_requestsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.kyc_requestsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` kyc_requests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` kyc_requests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned kyc_requests
  **/
  _count?: true | Kyc_requestsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Kyc_requestsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Kyc_requestsMaxAggregateInputType
}

export type GetKyc_requestsAggregateType<T extends Kyc_requestsAggregateArgs> = {
      [P in keyof T & keyof AggregateKyc_requests]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateKyc_requests[P]>
    : Prisma.GetScalarType<T[P], AggregateKyc_requests[P]>
}




export type kyc_requestsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.kyc_requestsWhereInput
  orderBy?: Prisma.kyc_requestsOrderByWithAggregationInput | Prisma.kyc_requestsOrderByWithAggregationInput[]
  by: Prisma.Kyc_requestsScalarFieldEnum[] | Prisma.Kyc_requestsScalarFieldEnum
  having?: Prisma.kyc_requestsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Kyc_requestsCountAggregateInputType | true
  _min?: Kyc_requestsMinAggregateInputType
  _max?: Kyc_requestsMaxAggregateInputType
}

export type Kyc_requestsGroupByOutputType = {
  id: string
  user_id: string
  user_type: string
  status: string | null
  kyc_provider: string
  kyc_reference_id: string | null
  documents: runtime.JsonValue | null
  submitted_at: Date | null
  approved_at: Date | null
  rejected_at: Date | null
  rejection_reason: string | null
  created_at: Date | null
  updated_at: Date | null
  _count: Kyc_requestsCountAggregateOutputType | null
  _min: Kyc_requestsMinAggregateOutputType | null
  _max: Kyc_requestsMaxAggregateOutputType | null
}

type GetKyc_requestsGroupByPayload<T extends kyc_requestsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Kyc_requestsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Kyc_requestsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Kyc_requestsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Kyc_requestsGroupByOutputType[P]>
      }
    >
  >



export type kyc_requestsWhereInput = {
  AND?: Prisma.kyc_requestsWhereInput | Prisma.kyc_requestsWhereInput[]
  OR?: Prisma.kyc_requestsWhereInput[]
  NOT?: Prisma.kyc_requestsWhereInput | Prisma.kyc_requestsWhereInput[]
  id?: Prisma.UuidFilter<"kyc_requests"> | string
  user_id?: Prisma.UuidFilter<"kyc_requests"> | string
  user_type?: Prisma.StringFilter<"kyc_requests"> | string
  status?: Prisma.StringNullableFilter<"kyc_requests"> | string | null
  kyc_provider?: Prisma.StringFilter<"kyc_requests"> | string
  kyc_reference_id?: Prisma.StringNullableFilter<"kyc_requests"> | string | null
  documents?: Prisma.JsonNullableFilter<"kyc_requests">
  submitted_at?: Prisma.DateTimeNullableFilter<"kyc_requests"> | Date | string | null
  approved_at?: Prisma.DateTimeNullableFilter<"kyc_requests"> | Date | string | null
  rejected_at?: Prisma.DateTimeNullableFilter<"kyc_requests"> | Date | string | null
  rejection_reason?: Prisma.StringNullableFilter<"kyc_requests"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"kyc_requests"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"kyc_requests"> | Date | string | null
  profiles?: Prisma.XOR<Prisma.ProfilesScalarRelationFilter, Prisma.profilesWhereInput>
}

export type kyc_requestsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  user_type?: Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  kyc_provider?: Prisma.SortOrder
  kyc_reference_id?: Prisma.SortOrderInput | Prisma.SortOrder
  documents?: Prisma.SortOrderInput | Prisma.SortOrder
  submitted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  approved_at?: Prisma.SortOrderInput | Prisma.SortOrder
  rejected_at?: Prisma.SortOrderInput | Prisma.SortOrder
  rejection_reason?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  profiles?: Prisma.profilesOrderByWithRelationInput
}

export type kyc_requestsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.kyc_requestsWhereInput | Prisma.kyc_requestsWhereInput[]
  OR?: Prisma.kyc_requestsWhereInput[]
  NOT?: Prisma.kyc_requestsWhereInput | Prisma.kyc_requestsWhereInput[]
  user_id?: Prisma.UuidFilter<"kyc_requests"> | string
  user_type?: Prisma.StringFilter<"kyc_requests"> | string
  status?: Prisma.StringNullableFilter<"kyc_requests"> | string | null
  kyc_provider?: Prisma.StringFilter<"kyc_requests"> | string
  kyc_reference_id?: Prisma.StringNullableFilter<"kyc_requests"> | string | null
  documents?: Prisma.JsonNullableFilter<"kyc_requests">
  submitted_at?: Prisma.DateTimeNullableFilter<"kyc_requests"> | Date | string | null
  approved_at?: Prisma.DateTimeNullableFilter<"kyc_requests"> | Date | string | null
  rejected_at?: Prisma.DateTimeNullableFilter<"kyc_requests"> | Date | string | null
  rejection_reason?: Prisma.StringNullableFilter<"kyc_requests"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"kyc_requests"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"kyc_requests"> | Date | string | null
  profiles?: Prisma.XOR<Prisma.ProfilesScalarRelationFilter, Prisma.profilesWhereInput>
}, "id">

export type kyc_requestsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  user_type?: Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  kyc_provider?: Prisma.SortOrder
  kyc_reference_id?: Prisma.SortOrderInput | Prisma.SortOrder
  documents?: Prisma.SortOrderInput | Prisma.SortOrder
  submitted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  approved_at?: Prisma.SortOrderInput | Prisma.SortOrder
  rejected_at?: Prisma.SortOrderInput | Prisma.SortOrder
  rejection_reason?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.kyc_requestsCountOrderByAggregateInput
  _max?: Prisma.kyc_requestsMaxOrderByAggregateInput
  _min?: Prisma.kyc_requestsMinOrderByAggregateInput
}

export type kyc_requestsScalarWhereWithAggregatesInput = {
  AND?: Prisma.kyc_requestsScalarWhereWithAggregatesInput | Prisma.kyc_requestsScalarWhereWithAggregatesInput[]
  OR?: Prisma.kyc_requestsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.kyc_requestsScalarWhereWithAggregatesInput | Prisma.kyc_requestsScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"kyc_requests"> | string
  user_id?: Prisma.UuidWithAggregatesFilter<"kyc_requests"> | string
  user_type?: Prisma.StringWithAggregatesFilter<"kyc_requests"> | string
  status?: Prisma.StringNullableWithAggregatesFilter<"kyc_requests"> | string | null
  kyc_provider?: Prisma.StringWithAggregatesFilter<"kyc_requests"> | string
  kyc_reference_id?: Prisma.StringNullableWithAggregatesFilter<"kyc_requests"> | string | null
  documents?: Prisma.JsonNullableWithAggregatesFilter<"kyc_requests">
  submitted_at?: Prisma.DateTimeNullableWithAggregatesFilter<"kyc_requests"> | Date | string | null
  approved_at?: Prisma.DateTimeNullableWithAggregatesFilter<"kyc_requests"> | Date | string | null
  rejected_at?: Prisma.DateTimeNullableWithAggregatesFilter<"kyc_requests"> | Date | string | null
  rejection_reason?: Prisma.StringNullableWithAggregatesFilter<"kyc_requests"> | string | null
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"kyc_requests"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"kyc_requests"> | Date | string | null
}

export type kyc_requestsCreateInput = {
  id?: string
  user_type: string
  status?: string | null
  kyc_provider: string
  kyc_reference_id?: string | null
  documents?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submitted_at?: Date | string | null
  approved_at?: Date | string | null
  rejected_at?: Date | string | null
  rejection_reason?: string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
  profiles: Prisma.profilesCreateNestedOneWithoutKyc_requestsInput
}

export type kyc_requestsUncheckedCreateInput = {
  id?: string
  user_id: string
  user_type: string
  status?: string | null
  kyc_provider: string
  kyc_reference_id?: string | null
  documents?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submitted_at?: Date | string | null
  approved_at?: Date | string | null
  rejected_at?: Date | string | null
  rejection_reason?: string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type kyc_requestsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kyc_provider?: Prisma.StringFieldUpdateOperationsInput | string
  kyc_reference_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  documents?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submitted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approved_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejected_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejection_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  profiles?: Prisma.profilesUpdateOneRequiredWithoutKyc_requestsNestedInput
}

export type kyc_requestsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kyc_provider?: Prisma.StringFieldUpdateOperationsInput | string
  kyc_reference_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  documents?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submitted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approved_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejected_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejection_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type kyc_requestsCreateManyInput = {
  id?: string
  user_id: string
  user_type: string
  status?: string | null
  kyc_provider: string
  kyc_reference_id?: string | null
  documents?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submitted_at?: Date | string | null
  approved_at?: Date | string | null
  rejected_at?: Date | string | null
  rejection_reason?: string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type kyc_requestsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kyc_provider?: Prisma.StringFieldUpdateOperationsInput | string
  kyc_reference_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  documents?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submitted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approved_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejected_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejection_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type kyc_requestsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kyc_provider?: Prisma.StringFieldUpdateOperationsInput | string
  kyc_reference_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  documents?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submitted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approved_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejected_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejection_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type kyc_requestsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  user_type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  kyc_provider?: Prisma.SortOrder
  kyc_reference_id?: Prisma.SortOrder
  documents?: Prisma.SortOrder
  submitted_at?: Prisma.SortOrder
  approved_at?: Prisma.SortOrder
  rejected_at?: Prisma.SortOrder
  rejection_reason?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type kyc_requestsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  user_type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  kyc_provider?: Prisma.SortOrder
  kyc_reference_id?: Prisma.SortOrder
  submitted_at?: Prisma.SortOrder
  approved_at?: Prisma.SortOrder
  rejected_at?: Prisma.SortOrder
  rejection_reason?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type kyc_requestsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  user_type?: Prisma.SortOrder
  status?: Prisma.SortOrder
  kyc_provider?: Prisma.SortOrder
  kyc_reference_id?: Prisma.SortOrder
  submitted_at?: Prisma.SortOrder
  approved_at?: Prisma.SortOrder
  rejected_at?: Prisma.SortOrder
  rejection_reason?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type Kyc_requestsListRelationFilter = {
  every?: Prisma.kyc_requestsWhereInput
  some?: Prisma.kyc_requestsWhereInput
  none?: Prisma.kyc_requestsWhereInput
}

export type kyc_requestsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type kyc_requestsCreateNestedManyWithoutProfilesInput = {
  create?: Prisma.XOR<Prisma.kyc_requestsCreateWithoutProfilesInput, Prisma.kyc_requestsUncheckedCreateWithoutProfilesInput> | Prisma.kyc_requestsCreateWithoutProfilesInput[] | Prisma.kyc_requestsUncheckedCreateWithoutProfilesInput[]
  connectOrCreate?: Prisma.kyc_requestsCreateOrConnectWithoutProfilesInput | Prisma.kyc_requestsCreateOrConnectWithoutProfilesInput[]
  createMany?: Prisma.kyc_requestsCreateManyProfilesInputEnvelope
  connect?: Prisma.kyc_requestsWhereUniqueInput | Prisma.kyc_requestsWhereUniqueInput[]
}

export type kyc_requestsUncheckedCreateNestedManyWithoutProfilesInput = {
  create?: Prisma.XOR<Prisma.kyc_requestsCreateWithoutProfilesInput, Prisma.kyc_requestsUncheckedCreateWithoutProfilesInput> | Prisma.kyc_requestsCreateWithoutProfilesInput[] | Prisma.kyc_requestsUncheckedCreateWithoutProfilesInput[]
  connectOrCreate?: Prisma.kyc_requestsCreateOrConnectWithoutProfilesInput | Prisma.kyc_requestsCreateOrConnectWithoutProfilesInput[]
  createMany?: Prisma.kyc_requestsCreateManyProfilesInputEnvelope
  connect?: Prisma.kyc_requestsWhereUniqueInput | Prisma.kyc_requestsWhereUniqueInput[]
}

export type kyc_requestsUpdateManyWithoutProfilesNestedInput = {
  create?: Prisma.XOR<Prisma.kyc_requestsCreateWithoutProfilesInput, Prisma.kyc_requestsUncheckedCreateWithoutProfilesInput> | Prisma.kyc_requestsCreateWithoutProfilesInput[] | Prisma.kyc_requestsUncheckedCreateWithoutProfilesInput[]
  connectOrCreate?: Prisma.kyc_requestsCreateOrConnectWithoutProfilesInput | Prisma.kyc_requestsCreateOrConnectWithoutProfilesInput[]
  upsert?: Prisma.kyc_requestsUpsertWithWhereUniqueWithoutProfilesInput | Prisma.kyc_requestsUpsertWithWhereUniqueWithoutProfilesInput[]
  createMany?: Prisma.kyc_requestsCreateManyProfilesInputEnvelope
  set?: Prisma.kyc_requestsWhereUniqueInput | Prisma.kyc_requestsWhereUniqueInput[]
  disconnect?: Prisma.kyc_requestsWhereUniqueInput | Prisma.kyc_requestsWhereUniqueInput[]
  delete?: Prisma.kyc_requestsWhereUniqueInput | Prisma.kyc_requestsWhereUniqueInput[]
  connect?: Prisma.kyc_requestsWhereUniqueInput | Prisma.kyc_requestsWhereUniqueInput[]
  update?: Prisma.kyc_requestsUpdateWithWhereUniqueWithoutProfilesInput | Prisma.kyc_requestsUpdateWithWhereUniqueWithoutProfilesInput[]
  updateMany?: Prisma.kyc_requestsUpdateManyWithWhereWithoutProfilesInput | Prisma.kyc_requestsUpdateManyWithWhereWithoutProfilesInput[]
  deleteMany?: Prisma.kyc_requestsScalarWhereInput | Prisma.kyc_requestsScalarWhereInput[]
}

export type kyc_requestsUncheckedUpdateManyWithoutProfilesNestedInput = {
  create?: Prisma.XOR<Prisma.kyc_requestsCreateWithoutProfilesInput, Prisma.kyc_requestsUncheckedCreateWithoutProfilesInput> | Prisma.kyc_requestsCreateWithoutProfilesInput[] | Prisma.kyc_requestsUncheckedCreateWithoutProfilesInput[]
  connectOrCreate?: Prisma.kyc_requestsCreateOrConnectWithoutProfilesInput | Prisma.kyc_requestsCreateOrConnectWithoutProfilesInput[]
  upsert?: Prisma.kyc_requestsUpsertWithWhereUniqueWithoutProfilesInput | Prisma.kyc_requestsUpsertWithWhereUniqueWithoutProfilesInput[]
  createMany?: Prisma.kyc_requestsCreateManyProfilesInputEnvelope
  set?: Prisma.kyc_requestsWhereUniqueInput | Prisma.kyc_requestsWhereUniqueInput[]
  disconnect?: Prisma.kyc_requestsWhereUniqueInput | Prisma.kyc_requestsWhereUniqueInput[]
  delete?: Prisma.kyc_requestsWhereUniqueInput | Prisma.kyc_requestsWhereUniqueInput[]
  connect?: Prisma.kyc_requestsWhereUniqueInput | Prisma.kyc_requestsWhereUniqueInput[]
  update?: Prisma.kyc_requestsUpdateWithWhereUniqueWithoutProfilesInput | Prisma.kyc_requestsUpdateWithWhereUniqueWithoutProfilesInput[]
  updateMany?: Prisma.kyc_requestsUpdateManyWithWhereWithoutProfilesInput | Prisma.kyc_requestsUpdateManyWithWhereWithoutProfilesInput[]
  deleteMany?: Prisma.kyc_requestsScalarWhereInput | Prisma.kyc_requestsScalarWhereInput[]
}

export type kyc_requestsCreateWithoutProfilesInput = {
  id?: string
  user_type: string
  status?: string | null
  kyc_provider: string
  kyc_reference_id?: string | null
  documents?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submitted_at?: Date | string | null
  approved_at?: Date | string | null
  rejected_at?: Date | string | null
  rejection_reason?: string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type kyc_requestsUncheckedCreateWithoutProfilesInput = {
  id?: string
  user_type: string
  status?: string | null
  kyc_provider: string
  kyc_reference_id?: string | null
  documents?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submitted_at?: Date | string | null
  approved_at?: Date | string | null
  rejected_at?: Date | string | null
  rejection_reason?: string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type kyc_requestsCreateOrConnectWithoutProfilesInput = {
  where: Prisma.kyc_requestsWhereUniqueInput
  create: Prisma.XOR<Prisma.kyc_requestsCreateWithoutProfilesInput, Prisma.kyc_requestsUncheckedCreateWithoutProfilesInput>
}

export type kyc_requestsCreateManyProfilesInputEnvelope = {
  data: Prisma.kyc_requestsCreateManyProfilesInput | Prisma.kyc_requestsCreateManyProfilesInput[]
  skipDuplicates?: boolean
}

export type kyc_requestsUpsertWithWhereUniqueWithoutProfilesInput = {
  where: Prisma.kyc_requestsWhereUniqueInput
  update: Prisma.XOR<Prisma.kyc_requestsUpdateWithoutProfilesInput, Prisma.kyc_requestsUncheckedUpdateWithoutProfilesInput>
  create: Prisma.XOR<Prisma.kyc_requestsCreateWithoutProfilesInput, Prisma.kyc_requestsUncheckedCreateWithoutProfilesInput>
}

export type kyc_requestsUpdateWithWhereUniqueWithoutProfilesInput = {
  where: Prisma.kyc_requestsWhereUniqueInput
  data: Prisma.XOR<Prisma.kyc_requestsUpdateWithoutProfilesInput, Prisma.kyc_requestsUncheckedUpdateWithoutProfilesInput>
}

export type kyc_requestsUpdateManyWithWhereWithoutProfilesInput = {
  where: Prisma.kyc_requestsScalarWhereInput
  data: Prisma.XOR<Prisma.kyc_requestsUpdateManyMutationInput, Prisma.kyc_requestsUncheckedUpdateManyWithoutProfilesInput>
}

export type kyc_requestsScalarWhereInput = {
  AND?: Prisma.kyc_requestsScalarWhereInput | Prisma.kyc_requestsScalarWhereInput[]
  OR?: Prisma.kyc_requestsScalarWhereInput[]
  NOT?: Prisma.kyc_requestsScalarWhereInput | Prisma.kyc_requestsScalarWhereInput[]
  id?: Prisma.UuidFilter<"kyc_requests"> | string
  user_id?: Prisma.UuidFilter<"kyc_requests"> | string
  user_type?: Prisma.StringFilter<"kyc_requests"> | string
  status?: Prisma.StringNullableFilter<"kyc_requests"> | string | null
  kyc_provider?: Prisma.StringFilter<"kyc_requests"> | string
  kyc_reference_id?: Prisma.StringNullableFilter<"kyc_requests"> | string | null
  documents?: Prisma.JsonNullableFilter<"kyc_requests">
  submitted_at?: Prisma.DateTimeNullableFilter<"kyc_requests"> | Date | string | null
  approved_at?: Prisma.DateTimeNullableFilter<"kyc_requests"> | Date | string | null
  rejected_at?: Prisma.DateTimeNullableFilter<"kyc_requests"> | Date | string | null
  rejection_reason?: Prisma.StringNullableFilter<"kyc_requests"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"kyc_requests"> | Date | string | null
  updated_at?: Prisma.DateTimeNullableFilter<"kyc_requests"> | Date | string | null
}

export type kyc_requestsCreateManyProfilesInput = {
  id?: string
  user_type: string
  status?: string | null
  kyc_provider: string
  kyc_reference_id?: string | null
  documents?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submitted_at?: Date | string | null
  approved_at?: Date | string | null
  rejected_at?: Date | string | null
  rejection_reason?: string | null
  created_at?: Date | string | null
  updated_at?: Date | string | null
}

export type kyc_requestsUpdateWithoutProfilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kyc_provider?: Prisma.StringFieldUpdateOperationsInput | string
  kyc_reference_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  documents?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submitted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approved_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejected_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejection_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type kyc_requestsUncheckedUpdateWithoutProfilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kyc_provider?: Prisma.StringFieldUpdateOperationsInput | string
  kyc_reference_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  documents?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submitted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approved_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejected_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejection_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type kyc_requestsUncheckedUpdateManyWithoutProfilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  user_type?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  kyc_provider?: Prisma.StringFieldUpdateOperationsInput | string
  kyc_reference_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  documents?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  submitted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  approved_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejected_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejection_reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type kyc_requestsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  user_type?: boolean
  status?: boolean
  kyc_provider?: boolean
  kyc_reference_id?: boolean
  documents?: boolean
  submitted_at?: boolean
  approved_at?: boolean
  rejected_at?: boolean
  rejection_reason?: boolean
  created_at?: boolean
  updated_at?: boolean
  profiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kyc_requests"]>

export type kyc_requestsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  user_type?: boolean
  status?: boolean
  kyc_provider?: boolean
  kyc_reference_id?: boolean
  documents?: boolean
  submitted_at?: boolean
  approved_at?: boolean
  rejected_at?: boolean
  rejection_reason?: boolean
  created_at?: boolean
  updated_at?: boolean
  profiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kyc_requests"]>

export type kyc_requestsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  user_id?: boolean
  user_type?: boolean
  status?: boolean
  kyc_provider?: boolean
  kyc_reference_id?: boolean
  documents?: boolean
  submitted_at?: boolean
  approved_at?: boolean
  rejected_at?: boolean
  rejection_reason?: boolean
  created_at?: boolean
  updated_at?: boolean
  profiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kyc_requests"]>

export type kyc_requestsSelectScalar = {
  id?: boolean
  user_id?: boolean
  user_type?: boolean
  status?: boolean
  kyc_provider?: boolean
  kyc_reference_id?: boolean
  documents?: boolean
  submitted_at?: boolean
  approved_at?: boolean
  rejected_at?: boolean
  rejection_reason?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type kyc_requestsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "user_id" | "user_type" | "status" | "kyc_provider" | "kyc_reference_id" | "documents" | "submitted_at" | "approved_at" | "rejected_at" | "rejection_reason" | "created_at" | "updated_at", ExtArgs["result"]["kyc_requests"]>
export type kyc_requestsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
}
export type kyc_requestsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
}
export type kyc_requestsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  profiles?: boolean | Prisma.profilesDefaultArgs<ExtArgs>
}

export type $kyc_requestsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "kyc_requests"
  objects: {
    profiles: Prisma.$profilesPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    user_id: string
    user_type: string
    status: string | null
    kyc_provider: string
    kyc_reference_id: string | null
    documents: runtime.JsonValue | null
    submitted_at: Date | null
    approved_at: Date | null
    rejected_at: Date | null
    rejection_reason: string | null
    created_at: Date | null
    updated_at: Date | null
  }, ExtArgs["result"]["kyc_requests"]>
  composites: {}
}

export type kyc_requestsGetPayload<S extends boolean | null | undefined | kyc_requestsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$kyc_requestsPayload, S>

export type kyc_requestsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<kyc_requestsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Kyc_requestsCountAggregateInputType | true
  }

export interface kyc_requestsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['kyc_requests'], meta: { name: 'kyc_requests' } }
  /**
   * Find zero or one Kyc_requests that matches the filter.
   * @param {kyc_requestsFindUniqueArgs} args - Arguments to find a Kyc_requests
   * @example
   * // Get one Kyc_requests
   * const kyc_requests = await prisma.kyc_requests.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends kyc_requestsFindUniqueArgs>(args: Prisma.SelectSubset<T, kyc_requestsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__kyc_requestsClient<runtime.Types.Result.GetResult<Prisma.$kyc_requestsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Kyc_requests that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {kyc_requestsFindUniqueOrThrowArgs} args - Arguments to find a Kyc_requests
   * @example
   * // Get one Kyc_requests
   * const kyc_requests = await prisma.kyc_requests.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends kyc_requestsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, kyc_requestsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__kyc_requestsClient<runtime.Types.Result.GetResult<Prisma.$kyc_requestsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Kyc_requests that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {kyc_requestsFindFirstArgs} args - Arguments to find a Kyc_requests
   * @example
   * // Get one Kyc_requests
   * const kyc_requests = await prisma.kyc_requests.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends kyc_requestsFindFirstArgs>(args?: Prisma.SelectSubset<T, kyc_requestsFindFirstArgs<ExtArgs>>): Prisma.Prisma__kyc_requestsClient<runtime.Types.Result.GetResult<Prisma.$kyc_requestsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Kyc_requests that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {kyc_requestsFindFirstOrThrowArgs} args - Arguments to find a Kyc_requests
   * @example
   * // Get one Kyc_requests
   * const kyc_requests = await prisma.kyc_requests.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends kyc_requestsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, kyc_requestsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__kyc_requestsClient<runtime.Types.Result.GetResult<Prisma.$kyc_requestsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Kyc_requests that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {kyc_requestsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Kyc_requests
   * const kyc_requests = await prisma.kyc_requests.findMany()
   * 
   * // Get first 10 Kyc_requests
   * const kyc_requests = await prisma.kyc_requests.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const kyc_requestsWithIdOnly = await prisma.kyc_requests.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends kyc_requestsFindManyArgs>(args?: Prisma.SelectSubset<T, kyc_requestsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$kyc_requestsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Kyc_requests.
   * @param {kyc_requestsCreateArgs} args - Arguments to create a Kyc_requests.
   * @example
   * // Create one Kyc_requests
   * const Kyc_requests = await prisma.kyc_requests.create({
   *   data: {
   *     // ... data to create a Kyc_requests
   *   }
   * })
   * 
   */
  create<T extends kyc_requestsCreateArgs>(args: Prisma.SelectSubset<T, kyc_requestsCreateArgs<ExtArgs>>): Prisma.Prisma__kyc_requestsClient<runtime.Types.Result.GetResult<Prisma.$kyc_requestsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Kyc_requests.
   * @param {kyc_requestsCreateManyArgs} args - Arguments to create many Kyc_requests.
   * @example
   * // Create many Kyc_requests
   * const kyc_requests = await prisma.kyc_requests.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends kyc_requestsCreateManyArgs>(args?: Prisma.SelectSubset<T, kyc_requestsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Kyc_requests and returns the data saved in the database.
   * @param {kyc_requestsCreateManyAndReturnArgs} args - Arguments to create many Kyc_requests.
   * @example
   * // Create many Kyc_requests
   * const kyc_requests = await prisma.kyc_requests.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Kyc_requests and only return the `id`
   * const kyc_requestsWithIdOnly = await prisma.kyc_requests.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends kyc_requestsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, kyc_requestsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$kyc_requestsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Kyc_requests.
   * @param {kyc_requestsDeleteArgs} args - Arguments to delete one Kyc_requests.
   * @example
   * // Delete one Kyc_requests
   * const Kyc_requests = await prisma.kyc_requests.delete({
   *   where: {
   *     // ... filter to delete one Kyc_requests
   *   }
   * })
   * 
   */
  delete<T extends kyc_requestsDeleteArgs>(args: Prisma.SelectSubset<T, kyc_requestsDeleteArgs<ExtArgs>>): Prisma.Prisma__kyc_requestsClient<runtime.Types.Result.GetResult<Prisma.$kyc_requestsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Kyc_requests.
   * @param {kyc_requestsUpdateArgs} args - Arguments to update one Kyc_requests.
   * @example
   * // Update one Kyc_requests
   * const kyc_requests = await prisma.kyc_requests.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends kyc_requestsUpdateArgs>(args: Prisma.SelectSubset<T, kyc_requestsUpdateArgs<ExtArgs>>): Prisma.Prisma__kyc_requestsClient<runtime.Types.Result.GetResult<Prisma.$kyc_requestsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Kyc_requests.
   * @param {kyc_requestsDeleteManyArgs} args - Arguments to filter Kyc_requests to delete.
   * @example
   * // Delete a few Kyc_requests
   * const { count } = await prisma.kyc_requests.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends kyc_requestsDeleteManyArgs>(args?: Prisma.SelectSubset<T, kyc_requestsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Kyc_requests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {kyc_requestsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Kyc_requests
   * const kyc_requests = await prisma.kyc_requests.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends kyc_requestsUpdateManyArgs>(args: Prisma.SelectSubset<T, kyc_requestsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Kyc_requests and returns the data updated in the database.
   * @param {kyc_requestsUpdateManyAndReturnArgs} args - Arguments to update many Kyc_requests.
   * @example
   * // Update many Kyc_requests
   * const kyc_requests = await prisma.kyc_requests.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Kyc_requests and only return the `id`
   * const kyc_requestsWithIdOnly = await prisma.kyc_requests.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends kyc_requestsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, kyc_requestsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$kyc_requestsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Kyc_requests.
   * @param {kyc_requestsUpsertArgs} args - Arguments to update or create a Kyc_requests.
   * @example
   * // Update or create a Kyc_requests
   * const kyc_requests = await prisma.kyc_requests.upsert({
   *   create: {
   *     // ... data to create a Kyc_requests
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Kyc_requests we want to update
   *   }
   * })
   */
  upsert<T extends kyc_requestsUpsertArgs>(args: Prisma.SelectSubset<T, kyc_requestsUpsertArgs<ExtArgs>>): Prisma.Prisma__kyc_requestsClient<runtime.Types.Result.GetResult<Prisma.$kyc_requestsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Kyc_requests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {kyc_requestsCountArgs} args - Arguments to filter Kyc_requests to count.
   * @example
   * // Count the number of Kyc_requests
   * const count = await prisma.kyc_requests.count({
   *   where: {
   *     // ... the filter for the Kyc_requests we want to count
   *   }
   * })
  **/
  count<T extends kyc_requestsCountArgs>(
    args?: Prisma.Subset<T, kyc_requestsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Kyc_requestsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Kyc_requests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Kyc_requestsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Kyc_requestsAggregateArgs>(args: Prisma.Subset<T, Kyc_requestsAggregateArgs>): Prisma.PrismaPromise<GetKyc_requestsAggregateType<T>>

  /**
   * Group by Kyc_requests.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {kyc_requestsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends kyc_requestsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: kyc_requestsGroupByArgs['orderBy'] }
      : { orderBy?: kyc_requestsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, kyc_requestsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetKyc_requestsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the kyc_requests model
 */
readonly fields: kyc_requestsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for kyc_requests.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__kyc_requestsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  profiles<T extends Prisma.profilesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.profilesDefaultArgs<ExtArgs>>): Prisma.Prisma__profilesClient<runtime.Types.Result.GetResult<Prisma.$profilesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the kyc_requests model
 */
export interface kyc_requestsFieldRefs {
  readonly id: Prisma.FieldRef<"kyc_requests", 'String'>
  readonly user_id: Prisma.FieldRef<"kyc_requests", 'String'>
  readonly user_type: Prisma.FieldRef<"kyc_requests", 'String'>
  readonly status: Prisma.FieldRef<"kyc_requests", 'String'>
  readonly kyc_provider: Prisma.FieldRef<"kyc_requests", 'String'>
  readonly kyc_reference_id: Prisma.FieldRef<"kyc_requests", 'String'>
  readonly documents: Prisma.FieldRef<"kyc_requests", 'Json'>
  readonly submitted_at: Prisma.FieldRef<"kyc_requests", 'DateTime'>
  readonly approved_at: Prisma.FieldRef<"kyc_requests", 'DateTime'>
  readonly rejected_at: Prisma.FieldRef<"kyc_requests", 'DateTime'>
  readonly rejection_reason: Prisma.FieldRef<"kyc_requests", 'String'>
  readonly created_at: Prisma.FieldRef<"kyc_requests", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"kyc_requests", 'DateTime'>
}
    

// Custom InputTypes
/**
 * kyc_requests findUnique
 */
export type kyc_requestsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the kyc_requests
   */
  select?: Prisma.kyc_requestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the kyc_requests
   */
  omit?: Prisma.kyc_requestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.kyc_requestsInclude<ExtArgs> | null
  /**
   * Filter, which kyc_requests to fetch.
   */
  where: Prisma.kyc_requestsWhereUniqueInput
}

/**
 * kyc_requests findUniqueOrThrow
 */
export type kyc_requestsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the kyc_requests
   */
  select?: Prisma.kyc_requestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the kyc_requests
   */
  omit?: Prisma.kyc_requestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.kyc_requestsInclude<ExtArgs> | null
  /**
   * Filter, which kyc_requests to fetch.
   */
  where: Prisma.kyc_requestsWhereUniqueInput
}

/**
 * kyc_requests findFirst
 */
export type kyc_requestsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the kyc_requests
   */
  select?: Prisma.kyc_requestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the kyc_requests
   */
  omit?: Prisma.kyc_requestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.kyc_requestsInclude<ExtArgs> | null
  /**
   * Filter, which kyc_requests to fetch.
   */
  where?: Prisma.kyc_requestsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of kyc_requests to fetch.
   */
  orderBy?: Prisma.kyc_requestsOrderByWithRelationInput | Prisma.kyc_requestsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for kyc_requests.
   */
  cursor?: Prisma.kyc_requestsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` kyc_requests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` kyc_requests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of kyc_requests.
   */
  distinct?: Prisma.Kyc_requestsScalarFieldEnum | Prisma.Kyc_requestsScalarFieldEnum[]
}

/**
 * kyc_requests findFirstOrThrow
 */
export type kyc_requestsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the kyc_requests
   */
  select?: Prisma.kyc_requestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the kyc_requests
   */
  omit?: Prisma.kyc_requestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.kyc_requestsInclude<ExtArgs> | null
  /**
   * Filter, which kyc_requests to fetch.
   */
  where?: Prisma.kyc_requestsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of kyc_requests to fetch.
   */
  orderBy?: Prisma.kyc_requestsOrderByWithRelationInput | Prisma.kyc_requestsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for kyc_requests.
   */
  cursor?: Prisma.kyc_requestsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` kyc_requests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` kyc_requests.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of kyc_requests.
   */
  distinct?: Prisma.Kyc_requestsScalarFieldEnum | Prisma.Kyc_requestsScalarFieldEnum[]
}

/**
 * kyc_requests findMany
 */
export type kyc_requestsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the kyc_requests
   */
  select?: Prisma.kyc_requestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the kyc_requests
   */
  omit?: Prisma.kyc_requestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.kyc_requestsInclude<ExtArgs> | null
  /**
   * Filter, which kyc_requests to fetch.
   */
  where?: Prisma.kyc_requestsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of kyc_requests to fetch.
   */
  orderBy?: Prisma.kyc_requestsOrderByWithRelationInput | Prisma.kyc_requestsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing kyc_requests.
   */
  cursor?: Prisma.kyc_requestsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` kyc_requests from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` kyc_requests.
   */
  skip?: number
  distinct?: Prisma.Kyc_requestsScalarFieldEnum | Prisma.Kyc_requestsScalarFieldEnum[]
}

/**
 * kyc_requests create
 */
export type kyc_requestsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the kyc_requests
   */
  select?: Prisma.kyc_requestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the kyc_requests
   */
  omit?: Prisma.kyc_requestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.kyc_requestsInclude<ExtArgs> | null
  /**
   * The data needed to create a kyc_requests.
   */
  data: Prisma.XOR<Prisma.kyc_requestsCreateInput, Prisma.kyc_requestsUncheckedCreateInput>
}

/**
 * kyc_requests createMany
 */
export type kyc_requestsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many kyc_requests.
   */
  data: Prisma.kyc_requestsCreateManyInput | Prisma.kyc_requestsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * kyc_requests createManyAndReturn
 */
export type kyc_requestsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the kyc_requests
   */
  select?: Prisma.kyc_requestsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the kyc_requests
   */
  omit?: Prisma.kyc_requestsOmit<ExtArgs> | null
  /**
   * The data used to create many kyc_requests.
   */
  data: Prisma.kyc_requestsCreateManyInput | Prisma.kyc_requestsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.kyc_requestsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * kyc_requests update
 */
export type kyc_requestsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the kyc_requests
   */
  select?: Prisma.kyc_requestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the kyc_requests
   */
  omit?: Prisma.kyc_requestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.kyc_requestsInclude<ExtArgs> | null
  /**
   * The data needed to update a kyc_requests.
   */
  data: Prisma.XOR<Prisma.kyc_requestsUpdateInput, Prisma.kyc_requestsUncheckedUpdateInput>
  /**
   * Choose, which kyc_requests to update.
   */
  where: Prisma.kyc_requestsWhereUniqueInput
}

/**
 * kyc_requests updateMany
 */
export type kyc_requestsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update kyc_requests.
   */
  data: Prisma.XOR<Prisma.kyc_requestsUpdateManyMutationInput, Prisma.kyc_requestsUncheckedUpdateManyInput>
  /**
   * Filter which kyc_requests to update
   */
  where?: Prisma.kyc_requestsWhereInput
  /**
   * Limit how many kyc_requests to update.
   */
  limit?: number
}

/**
 * kyc_requests updateManyAndReturn
 */
export type kyc_requestsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the kyc_requests
   */
  select?: Prisma.kyc_requestsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the kyc_requests
   */
  omit?: Prisma.kyc_requestsOmit<ExtArgs> | null
  /**
   * The data used to update kyc_requests.
   */
  data: Prisma.XOR<Prisma.kyc_requestsUpdateManyMutationInput, Prisma.kyc_requestsUncheckedUpdateManyInput>
  /**
   * Filter which kyc_requests to update
   */
  where?: Prisma.kyc_requestsWhereInput
  /**
   * Limit how many kyc_requests to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.kyc_requestsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * kyc_requests upsert
 */
export type kyc_requestsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the kyc_requests
   */
  select?: Prisma.kyc_requestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the kyc_requests
   */
  omit?: Prisma.kyc_requestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.kyc_requestsInclude<ExtArgs> | null
  /**
   * The filter to search for the kyc_requests to update in case it exists.
   */
  where: Prisma.kyc_requestsWhereUniqueInput
  /**
   * In case the kyc_requests found by the `where` argument doesn't exist, create a new kyc_requests with this data.
   */
  create: Prisma.XOR<Prisma.kyc_requestsCreateInput, Prisma.kyc_requestsUncheckedCreateInput>
  /**
   * In case the kyc_requests was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.kyc_requestsUpdateInput, Prisma.kyc_requestsUncheckedUpdateInput>
}

/**
 * kyc_requests delete
 */
export type kyc_requestsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the kyc_requests
   */
  select?: Prisma.kyc_requestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the kyc_requests
   */
  omit?: Prisma.kyc_requestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.kyc_requestsInclude<ExtArgs> | null
  /**
   * Filter which kyc_requests to delete.
   */
  where: Prisma.kyc_requestsWhereUniqueInput
}

/**
 * kyc_requests deleteMany
 */
export type kyc_requestsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which kyc_requests to delete
   */
  where?: Prisma.kyc_requestsWhereInput
  /**
   * Limit how many kyc_requests to delete.
   */
  limit?: number
}

/**
 * kyc_requests without action
 */
export type kyc_requestsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the kyc_requests
   */
  select?: Prisma.kyc_requestsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the kyc_requests
   */
  omit?: Prisma.kyc_requestsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.kyc_requestsInclude<ExtArgs> | null
}
