
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `poll_submission_answers` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model poll_submission_answers
 * Individual answers for each question within a submission.
 */
export type poll_submission_answersModel = runtime.Types.Result.DefaultSelection<Prisma.$poll_submission_answersPayload>

export type AggregatePoll_submission_answers = {
  _count: Poll_submission_answersCountAggregateOutputType | null
  _min: Poll_submission_answersMinAggregateOutputType | null
  _max: Poll_submission_answersMaxAggregateOutputType | null
}

export type Poll_submission_answersMinAggregateOutputType = {
  id: string | null
  submission_id: string | null
  question_key: string | null
  created_at: Date | null
}

export type Poll_submission_answersMaxAggregateOutputType = {
  id: string | null
  submission_id: string | null
  question_key: string | null
  created_at: Date | null
}

export type Poll_submission_answersCountAggregateOutputType = {
  id: number
  submission_id: number
  question_key: number
  answer: number
  created_at: number
  _all: number
}


export type Poll_submission_answersMinAggregateInputType = {
  id?: true
  submission_id?: true
  question_key?: true
  created_at?: true
}

export type Poll_submission_answersMaxAggregateInputType = {
  id?: true
  submission_id?: true
  question_key?: true
  created_at?: true
}

export type Poll_submission_answersCountAggregateInputType = {
  id?: true
  submission_id?: true
  question_key?: true
  answer?: true
  created_at?: true
  _all?: true
}

export type Poll_submission_answersAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which poll_submission_answers to aggregate.
   */
  where?: Prisma.poll_submission_answersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of poll_submission_answers to fetch.
   */
  orderBy?: Prisma.poll_submission_answersOrderByWithRelationInput | Prisma.poll_submission_answersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.poll_submission_answersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` poll_submission_answers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` poll_submission_answers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned poll_submission_answers
  **/
  _count?: true | Poll_submission_answersCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Poll_submission_answersMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Poll_submission_answersMaxAggregateInputType
}

export type GetPoll_submission_answersAggregateType<T extends Poll_submission_answersAggregateArgs> = {
      [P in keyof T & keyof AggregatePoll_submission_answers]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePoll_submission_answers[P]>
    : Prisma.GetScalarType<T[P], AggregatePoll_submission_answers[P]>
}




export type poll_submission_answersGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.poll_submission_answersWhereInput
  orderBy?: Prisma.poll_submission_answersOrderByWithAggregationInput | Prisma.poll_submission_answersOrderByWithAggregationInput[]
  by: Prisma.Poll_submission_answersScalarFieldEnum[] | Prisma.Poll_submission_answersScalarFieldEnum
  having?: Prisma.poll_submission_answersScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Poll_submission_answersCountAggregateInputType | true
  _min?: Poll_submission_answersMinAggregateInputType
  _max?: Poll_submission_answersMaxAggregateInputType
}

export type Poll_submission_answersGroupByOutputType = {
  id: string
  submission_id: string
  question_key: string
  answer: runtime.JsonValue
  created_at: Date
  _count: Poll_submission_answersCountAggregateOutputType | null
  _min: Poll_submission_answersMinAggregateOutputType | null
  _max: Poll_submission_answersMaxAggregateOutputType | null
}

type GetPoll_submission_answersGroupByPayload<T extends poll_submission_answersGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Poll_submission_answersGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Poll_submission_answersGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Poll_submission_answersGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Poll_submission_answersGroupByOutputType[P]>
      }
    >
  >



export type poll_submission_answersWhereInput = {
  AND?: Prisma.poll_submission_answersWhereInput | Prisma.poll_submission_answersWhereInput[]
  OR?: Prisma.poll_submission_answersWhereInput[]
  NOT?: Prisma.poll_submission_answersWhereInput | Prisma.poll_submission_answersWhereInput[]
  id?: Prisma.UuidFilter<"poll_submission_answers"> | string
  submission_id?: Prisma.UuidFilter<"poll_submission_answers"> | string
  question_key?: Prisma.StringFilter<"poll_submission_answers"> | string
  answer?: Prisma.JsonFilter<"poll_submission_answers">
  created_at?: Prisma.DateTimeFilter<"poll_submission_answers"> | Date | string
  submission?: Prisma.XOR<Prisma.Poll_submissionsScalarRelationFilter, Prisma.poll_submissionsWhereInput>
}

export type poll_submission_answersOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  submission_id?: Prisma.SortOrder
  question_key?: Prisma.SortOrder
  answer?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  submission?: Prisma.poll_submissionsOrderByWithRelationInput
}

export type poll_submission_answersWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  submission_id_question_key?: Prisma.poll_submission_answersSubmission_idQuestion_keyCompoundUniqueInput
  AND?: Prisma.poll_submission_answersWhereInput | Prisma.poll_submission_answersWhereInput[]
  OR?: Prisma.poll_submission_answersWhereInput[]
  NOT?: Prisma.poll_submission_answersWhereInput | Prisma.poll_submission_answersWhereInput[]
  submission_id?: Prisma.UuidFilter<"poll_submission_answers"> | string
  question_key?: Prisma.StringFilter<"poll_submission_answers"> | string
  answer?: Prisma.JsonFilter<"poll_submission_answers">
  created_at?: Prisma.DateTimeFilter<"poll_submission_answers"> | Date | string
  submission?: Prisma.XOR<Prisma.Poll_submissionsScalarRelationFilter, Prisma.poll_submissionsWhereInput>
}, "id" | "submission_id_question_key">

export type poll_submission_answersOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  submission_id?: Prisma.SortOrder
  question_key?: Prisma.SortOrder
  answer?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.poll_submission_answersCountOrderByAggregateInput
  _max?: Prisma.poll_submission_answersMaxOrderByAggregateInput
  _min?: Prisma.poll_submission_answersMinOrderByAggregateInput
}

export type poll_submission_answersScalarWhereWithAggregatesInput = {
  AND?: Prisma.poll_submission_answersScalarWhereWithAggregatesInput | Prisma.poll_submission_answersScalarWhereWithAggregatesInput[]
  OR?: Prisma.poll_submission_answersScalarWhereWithAggregatesInput[]
  NOT?: Prisma.poll_submission_answersScalarWhereWithAggregatesInput | Prisma.poll_submission_answersScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"poll_submission_answers"> | string
  submission_id?: Prisma.UuidWithAggregatesFilter<"poll_submission_answers"> | string
  question_key?: Prisma.StringWithAggregatesFilter<"poll_submission_answers"> | string
  answer?: Prisma.JsonWithAggregatesFilter<"poll_submission_answers">
  created_at?: Prisma.DateTimeWithAggregatesFilter<"poll_submission_answers"> | Date | string
}

export type poll_submission_answersCreateInput = {
  id?: string
  question_key: string
  answer: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  submission: Prisma.poll_submissionsCreateNestedOneWithoutAnswersInput
}

export type poll_submission_answersUncheckedCreateInput = {
  id?: string
  submission_id: string
  question_key: string
  answer: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
}

export type poll_submission_answersUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  question_key?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  submission?: Prisma.poll_submissionsUpdateOneRequiredWithoutAnswersNestedInput
}

export type poll_submission_answersUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  submission_id?: Prisma.StringFieldUpdateOperationsInput | string
  question_key?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type poll_submission_answersCreateManyInput = {
  id?: string
  submission_id: string
  question_key: string
  answer: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
}

export type poll_submission_answersUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  question_key?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type poll_submission_answersUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  submission_id?: Prisma.StringFieldUpdateOperationsInput | string
  question_key?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Poll_submission_answersListRelationFilter = {
  every?: Prisma.poll_submission_answersWhereInput
  some?: Prisma.poll_submission_answersWhereInput
  none?: Prisma.poll_submission_answersWhereInput
}

export type poll_submission_answersOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type poll_submission_answersSubmission_idQuestion_keyCompoundUniqueInput = {
  submission_id: string
  question_key: string
}

export type poll_submission_answersCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  submission_id?: Prisma.SortOrder
  question_key?: Prisma.SortOrder
  answer?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type poll_submission_answersMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  submission_id?: Prisma.SortOrder
  question_key?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type poll_submission_answersMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  submission_id?: Prisma.SortOrder
  question_key?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type poll_submission_answersCreateNestedManyWithoutSubmissionInput = {
  create?: Prisma.XOR<Prisma.poll_submission_answersCreateWithoutSubmissionInput, Prisma.poll_submission_answersUncheckedCreateWithoutSubmissionInput> | Prisma.poll_submission_answersCreateWithoutSubmissionInput[] | Prisma.poll_submission_answersUncheckedCreateWithoutSubmissionInput[]
  connectOrCreate?: Prisma.poll_submission_answersCreateOrConnectWithoutSubmissionInput | Prisma.poll_submission_answersCreateOrConnectWithoutSubmissionInput[]
  createMany?: Prisma.poll_submission_answersCreateManySubmissionInputEnvelope
  connect?: Prisma.poll_submission_answersWhereUniqueInput | Prisma.poll_submission_answersWhereUniqueInput[]
}

export type poll_submission_answersUncheckedCreateNestedManyWithoutSubmissionInput = {
  create?: Prisma.XOR<Prisma.poll_submission_answersCreateWithoutSubmissionInput, Prisma.poll_submission_answersUncheckedCreateWithoutSubmissionInput> | Prisma.poll_submission_answersCreateWithoutSubmissionInput[] | Prisma.poll_submission_answersUncheckedCreateWithoutSubmissionInput[]
  connectOrCreate?: Prisma.poll_submission_answersCreateOrConnectWithoutSubmissionInput | Prisma.poll_submission_answersCreateOrConnectWithoutSubmissionInput[]
  createMany?: Prisma.poll_submission_answersCreateManySubmissionInputEnvelope
  connect?: Prisma.poll_submission_answersWhereUniqueInput | Prisma.poll_submission_answersWhereUniqueInput[]
}

export type poll_submission_answersUpdateManyWithoutSubmissionNestedInput = {
  create?: Prisma.XOR<Prisma.poll_submission_answersCreateWithoutSubmissionInput, Prisma.poll_submission_answersUncheckedCreateWithoutSubmissionInput> | Prisma.poll_submission_answersCreateWithoutSubmissionInput[] | Prisma.poll_submission_answersUncheckedCreateWithoutSubmissionInput[]
  connectOrCreate?: Prisma.poll_submission_answersCreateOrConnectWithoutSubmissionInput | Prisma.poll_submission_answersCreateOrConnectWithoutSubmissionInput[]
  upsert?: Prisma.poll_submission_answersUpsertWithWhereUniqueWithoutSubmissionInput | Prisma.poll_submission_answersUpsertWithWhereUniqueWithoutSubmissionInput[]
  createMany?: Prisma.poll_submission_answersCreateManySubmissionInputEnvelope
  set?: Prisma.poll_submission_answersWhereUniqueInput | Prisma.poll_submission_answersWhereUniqueInput[]
  disconnect?: Prisma.poll_submission_answersWhereUniqueInput | Prisma.poll_submission_answersWhereUniqueInput[]
  delete?: Prisma.poll_submission_answersWhereUniqueInput | Prisma.poll_submission_answersWhereUniqueInput[]
  connect?: Prisma.poll_submission_answersWhereUniqueInput | Prisma.poll_submission_answersWhereUniqueInput[]
  update?: Prisma.poll_submission_answersUpdateWithWhereUniqueWithoutSubmissionInput | Prisma.poll_submission_answersUpdateWithWhereUniqueWithoutSubmissionInput[]
  updateMany?: Prisma.poll_submission_answersUpdateManyWithWhereWithoutSubmissionInput | Prisma.poll_submission_answersUpdateManyWithWhereWithoutSubmissionInput[]
  deleteMany?: Prisma.poll_submission_answersScalarWhereInput | Prisma.poll_submission_answersScalarWhereInput[]
}

export type poll_submission_answersUncheckedUpdateManyWithoutSubmissionNestedInput = {
  create?: Prisma.XOR<Prisma.poll_submission_answersCreateWithoutSubmissionInput, Prisma.poll_submission_answersUncheckedCreateWithoutSubmissionInput> | Prisma.poll_submission_answersCreateWithoutSubmissionInput[] | Prisma.poll_submission_answersUncheckedCreateWithoutSubmissionInput[]
  connectOrCreate?: Prisma.poll_submission_answersCreateOrConnectWithoutSubmissionInput | Prisma.poll_submission_answersCreateOrConnectWithoutSubmissionInput[]
  upsert?: Prisma.poll_submission_answersUpsertWithWhereUniqueWithoutSubmissionInput | Prisma.poll_submission_answersUpsertWithWhereUniqueWithoutSubmissionInput[]
  createMany?: Prisma.poll_submission_answersCreateManySubmissionInputEnvelope
  set?: Prisma.poll_submission_answersWhereUniqueInput | Prisma.poll_submission_answersWhereUniqueInput[]
  disconnect?: Prisma.poll_submission_answersWhereUniqueInput | Prisma.poll_submission_answersWhereUniqueInput[]
  delete?: Prisma.poll_submission_answersWhereUniqueInput | Prisma.poll_submission_answersWhereUniqueInput[]
  connect?: Prisma.poll_submission_answersWhereUniqueInput | Prisma.poll_submission_answersWhereUniqueInput[]
  update?: Prisma.poll_submission_answersUpdateWithWhereUniqueWithoutSubmissionInput | Prisma.poll_submission_answersUpdateWithWhereUniqueWithoutSubmissionInput[]
  updateMany?: Prisma.poll_submission_answersUpdateManyWithWhereWithoutSubmissionInput | Prisma.poll_submission_answersUpdateManyWithWhereWithoutSubmissionInput[]
  deleteMany?: Prisma.poll_submission_answersScalarWhereInput | Prisma.poll_submission_answersScalarWhereInput[]
}

export type poll_submission_answersCreateWithoutSubmissionInput = {
  id?: string
  question_key: string
  answer: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
}

export type poll_submission_answersUncheckedCreateWithoutSubmissionInput = {
  id?: string
  question_key: string
  answer: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
}

export type poll_submission_answersCreateOrConnectWithoutSubmissionInput = {
  where: Prisma.poll_submission_answersWhereUniqueInput
  create: Prisma.XOR<Prisma.poll_submission_answersCreateWithoutSubmissionInput, Prisma.poll_submission_answersUncheckedCreateWithoutSubmissionInput>
}

export type poll_submission_answersCreateManySubmissionInputEnvelope = {
  data: Prisma.poll_submission_answersCreateManySubmissionInput | Prisma.poll_submission_answersCreateManySubmissionInput[]
  skipDuplicates?: boolean
}

export type poll_submission_answersUpsertWithWhereUniqueWithoutSubmissionInput = {
  where: Prisma.poll_submission_answersWhereUniqueInput
  update: Prisma.XOR<Prisma.poll_submission_answersUpdateWithoutSubmissionInput, Prisma.poll_submission_answersUncheckedUpdateWithoutSubmissionInput>
  create: Prisma.XOR<Prisma.poll_submission_answersCreateWithoutSubmissionInput, Prisma.poll_submission_answersUncheckedCreateWithoutSubmissionInput>
}

export type poll_submission_answersUpdateWithWhereUniqueWithoutSubmissionInput = {
  where: Prisma.poll_submission_answersWhereUniqueInput
  data: Prisma.XOR<Prisma.poll_submission_answersUpdateWithoutSubmissionInput, Prisma.poll_submission_answersUncheckedUpdateWithoutSubmissionInput>
}

export type poll_submission_answersUpdateManyWithWhereWithoutSubmissionInput = {
  where: Prisma.poll_submission_answersScalarWhereInput
  data: Prisma.XOR<Prisma.poll_submission_answersUpdateManyMutationInput, Prisma.poll_submission_answersUncheckedUpdateManyWithoutSubmissionInput>
}

export type poll_submission_answersScalarWhereInput = {
  AND?: Prisma.poll_submission_answersScalarWhereInput | Prisma.poll_submission_answersScalarWhereInput[]
  OR?: Prisma.poll_submission_answersScalarWhereInput[]
  NOT?: Prisma.poll_submission_answersScalarWhereInput | Prisma.poll_submission_answersScalarWhereInput[]
  id?: Prisma.UuidFilter<"poll_submission_answers"> | string
  submission_id?: Prisma.UuidFilter<"poll_submission_answers"> | string
  question_key?: Prisma.StringFilter<"poll_submission_answers"> | string
  answer?: Prisma.JsonFilter<"poll_submission_answers">
  created_at?: Prisma.DateTimeFilter<"poll_submission_answers"> | Date | string
}

export type poll_submission_answersCreateManySubmissionInput = {
  id?: string
  question_key: string
  answer: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
}

export type poll_submission_answersUpdateWithoutSubmissionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  question_key?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type poll_submission_answersUncheckedUpdateWithoutSubmissionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  question_key?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type poll_submission_answersUncheckedUpdateManyWithoutSubmissionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  question_key?: Prisma.StringFieldUpdateOperationsInput | string
  answer?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type poll_submission_answersSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  submission_id?: boolean
  question_key?: boolean
  answer?: boolean
  created_at?: boolean
  submission?: boolean | Prisma.poll_submissionsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["poll_submission_answers"]>

export type poll_submission_answersSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  submission_id?: boolean
  question_key?: boolean
  answer?: boolean
  created_at?: boolean
  submission?: boolean | Prisma.poll_submissionsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["poll_submission_answers"]>

export type poll_submission_answersSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  submission_id?: boolean
  question_key?: boolean
  answer?: boolean
  created_at?: boolean
  submission?: boolean | Prisma.poll_submissionsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["poll_submission_answers"]>

export type poll_submission_answersSelectScalar = {
  id?: boolean
  submission_id?: boolean
  question_key?: boolean
  answer?: boolean
  created_at?: boolean
}

export type poll_submission_answersOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "submission_id" | "question_key" | "answer" | "created_at", ExtArgs["result"]["poll_submission_answers"]>
export type poll_submission_answersInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  submission?: boolean | Prisma.poll_submissionsDefaultArgs<ExtArgs>
}
export type poll_submission_answersIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  submission?: boolean | Prisma.poll_submissionsDefaultArgs<ExtArgs>
}
export type poll_submission_answersIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  submission?: boolean | Prisma.poll_submissionsDefaultArgs<ExtArgs>
}

export type $poll_submission_answersPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "poll_submission_answers"
  objects: {
    submission: Prisma.$poll_submissionsPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    submission_id: string
    question_key: string
    answer: runtime.JsonValue
    created_at: Date
  }, ExtArgs["result"]["poll_submission_answers"]>
  composites: {}
}

export type poll_submission_answersGetPayload<S extends boolean | null | undefined | poll_submission_answersDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$poll_submission_answersPayload, S>

export type poll_submission_answersCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<poll_submission_answersFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Poll_submission_answersCountAggregateInputType | true
  }

export interface poll_submission_answersDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['poll_submission_answers'], meta: { name: 'poll_submission_answers' } }
  /**
   * Find zero or one Poll_submission_answers that matches the filter.
   * @param {poll_submission_answersFindUniqueArgs} args - Arguments to find a Poll_submission_answers
   * @example
   * // Get one Poll_submission_answers
   * const poll_submission_answers = await prisma.poll_submission_answers.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends poll_submission_answersFindUniqueArgs>(args: Prisma.SelectSubset<T, poll_submission_answersFindUniqueArgs<ExtArgs>>): Prisma.Prisma__poll_submission_answersClient<runtime.Types.Result.GetResult<Prisma.$poll_submission_answersPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Poll_submission_answers that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {poll_submission_answersFindUniqueOrThrowArgs} args - Arguments to find a Poll_submission_answers
   * @example
   * // Get one Poll_submission_answers
   * const poll_submission_answers = await prisma.poll_submission_answers.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends poll_submission_answersFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, poll_submission_answersFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__poll_submission_answersClient<runtime.Types.Result.GetResult<Prisma.$poll_submission_answersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Poll_submission_answers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {poll_submission_answersFindFirstArgs} args - Arguments to find a Poll_submission_answers
   * @example
   * // Get one Poll_submission_answers
   * const poll_submission_answers = await prisma.poll_submission_answers.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends poll_submission_answersFindFirstArgs>(args?: Prisma.SelectSubset<T, poll_submission_answersFindFirstArgs<ExtArgs>>): Prisma.Prisma__poll_submission_answersClient<runtime.Types.Result.GetResult<Prisma.$poll_submission_answersPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Poll_submission_answers that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {poll_submission_answersFindFirstOrThrowArgs} args - Arguments to find a Poll_submission_answers
   * @example
   * // Get one Poll_submission_answers
   * const poll_submission_answers = await prisma.poll_submission_answers.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends poll_submission_answersFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, poll_submission_answersFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__poll_submission_answersClient<runtime.Types.Result.GetResult<Prisma.$poll_submission_answersPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Poll_submission_answers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {poll_submission_answersFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Poll_submission_answers
   * const poll_submission_answers = await prisma.poll_submission_answers.findMany()
   * 
   * // Get first 10 Poll_submission_answers
   * const poll_submission_answers = await prisma.poll_submission_answers.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const poll_submission_answersWithIdOnly = await prisma.poll_submission_answers.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends poll_submission_answersFindManyArgs>(args?: Prisma.SelectSubset<T, poll_submission_answersFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$poll_submission_answersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Poll_submission_answers.
   * @param {poll_submission_answersCreateArgs} args - Arguments to create a Poll_submission_answers.
   * @example
   * // Create one Poll_submission_answers
   * const Poll_submission_answers = await prisma.poll_submission_answers.create({
   *   data: {
   *     // ... data to create a Poll_submission_answers
   *   }
   * })
   * 
   */
  create<T extends poll_submission_answersCreateArgs>(args: Prisma.SelectSubset<T, poll_submission_answersCreateArgs<ExtArgs>>): Prisma.Prisma__poll_submission_answersClient<runtime.Types.Result.GetResult<Prisma.$poll_submission_answersPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Poll_submission_answers.
   * @param {poll_submission_answersCreateManyArgs} args - Arguments to create many Poll_submission_answers.
   * @example
   * // Create many Poll_submission_answers
   * const poll_submission_answers = await prisma.poll_submission_answers.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends poll_submission_answersCreateManyArgs>(args?: Prisma.SelectSubset<T, poll_submission_answersCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Poll_submission_answers and returns the data saved in the database.
   * @param {poll_submission_answersCreateManyAndReturnArgs} args - Arguments to create many Poll_submission_answers.
   * @example
   * // Create many Poll_submission_answers
   * const poll_submission_answers = await prisma.poll_submission_answers.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Poll_submission_answers and only return the `id`
   * const poll_submission_answersWithIdOnly = await prisma.poll_submission_answers.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends poll_submission_answersCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, poll_submission_answersCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$poll_submission_answersPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Poll_submission_answers.
   * @param {poll_submission_answersDeleteArgs} args - Arguments to delete one Poll_submission_answers.
   * @example
   * // Delete one Poll_submission_answers
   * const Poll_submission_answers = await prisma.poll_submission_answers.delete({
   *   where: {
   *     // ... filter to delete one Poll_submission_answers
   *   }
   * })
   * 
   */
  delete<T extends poll_submission_answersDeleteArgs>(args: Prisma.SelectSubset<T, poll_submission_answersDeleteArgs<ExtArgs>>): Prisma.Prisma__poll_submission_answersClient<runtime.Types.Result.GetResult<Prisma.$poll_submission_answersPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Poll_submission_answers.
   * @param {poll_submission_answersUpdateArgs} args - Arguments to update one Poll_submission_answers.
   * @example
   * // Update one Poll_submission_answers
   * const poll_submission_answers = await prisma.poll_submission_answers.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends poll_submission_answersUpdateArgs>(args: Prisma.SelectSubset<T, poll_submission_answersUpdateArgs<ExtArgs>>): Prisma.Prisma__poll_submission_answersClient<runtime.Types.Result.GetResult<Prisma.$poll_submission_answersPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Poll_submission_answers.
   * @param {poll_submission_answersDeleteManyArgs} args - Arguments to filter Poll_submission_answers to delete.
   * @example
   * // Delete a few Poll_submission_answers
   * const { count } = await prisma.poll_submission_answers.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends poll_submission_answersDeleteManyArgs>(args?: Prisma.SelectSubset<T, poll_submission_answersDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Poll_submission_answers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {poll_submission_answersUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Poll_submission_answers
   * const poll_submission_answers = await prisma.poll_submission_answers.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends poll_submission_answersUpdateManyArgs>(args: Prisma.SelectSubset<T, poll_submission_answersUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Poll_submission_answers and returns the data updated in the database.
   * @param {poll_submission_answersUpdateManyAndReturnArgs} args - Arguments to update many Poll_submission_answers.
   * @example
   * // Update many Poll_submission_answers
   * const poll_submission_answers = await prisma.poll_submission_answers.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Poll_submission_answers and only return the `id`
   * const poll_submission_answersWithIdOnly = await prisma.poll_submission_answers.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends poll_submission_answersUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, poll_submission_answersUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$poll_submission_answersPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Poll_submission_answers.
   * @param {poll_submission_answersUpsertArgs} args - Arguments to update or create a Poll_submission_answers.
   * @example
   * // Update or create a Poll_submission_answers
   * const poll_submission_answers = await prisma.poll_submission_answers.upsert({
   *   create: {
   *     // ... data to create a Poll_submission_answers
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Poll_submission_answers we want to update
   *   }
   * })
   */
  upsert<T extends poll_submission_answersUpsertArgs>(args: Prisma.SelectSubset<T, poll_submission_answersUpsertArgs<ExtArgs>>): Prisma.Prisma__poll_submission_answersClient<runtime.Types.Result.GetResult<Prisma.$poll_submission_answersPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Poll_submission_answers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {poll_submission_answersCountArgs} args - Arguments to filter Poll_submission_answers to count.
   * @example
   * // Count the number of Poll_submission_answers
   * const count = await prisma.poll_submission_answers.count({
   *   where: {
   *     // ... the filter for the Poll_submission_answers we want to count
   *   }
   * })
  **/
  count<T extends poll_submission_answersCountArgs>(
    args?: Prisma.Subset<T, poll_submission_answersCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Poll_submission_answersCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Poll_submission_answers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Poll_submission_answersAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Poll_submission_answersAggregateArgs>(args: Prisma.Subset<T, Poll_submission_answersAggregateArgs>): Prisma.PrismaPromise<GetPoll_submission_answersAggregateType<T>>

  /**
   * Group by Poll_submission_answers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {poll_submission_answersGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends poll_submission_answersGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: poll_submission_answersGroupByArgs['orderBy'] }
      : { orderBy?: poll_submission_answersGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, poll_submission_answersGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPoll_submission_answersGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the poll_submission_answers model
 */
readonly fields: poll_submission_answersFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for poll_submission_answers.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__poll_submission_answersClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  submission<T extends Prisma.poll_submissionsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.poll_submissionsDefaultArgs<ExtArgs>>): Prisma.Prisma__poll_submissionsClient<runtime.Types.Result.GetResult<Prisma.$poll_submissionsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the poll_submission_answers model
 */
export interface poll_submission_answersFieldRefs {
  readonly id: Prisma.FieldRef<"poll_submission_answers", 'String'>
  readonly submission_id: Prisma.FieldRef<"poll_submission_answers", 'String'>
  readonly question_key: Prisma.FieldRef<"poll_submission_answers", 'String'>
  readonly answer: Prisma.FieldRef<"poll_submission_answers", 'Json'>
  readonly created_at: Prisma.FieldRef<"poll_submission_answers", 'DateTime'>
}
    

// Custom InputTypes
/**
 * poll_submission_answers findUnique
 */
export type poll_submission_answersFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the poll_submission_answers
   */
  select?: Prisma.poll_submission_answersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the poll_submission_answers
   */
  omit?: Prisma.poll_submission_answersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.poll_submission_answersInclude<ExtArgs> | null
  /**
   * Filter, which poll_submission_answers to fetch.
   */
  where: Prisma.poll_submission_answersWhereUniqueInput
}

/**
 * poll_submission_answers findUniqueOrThrow
 */
export type poll_submission_answersFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the poll_submission_answers
   */
  select?: Prisma.poll_submission_answersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the poll_submission_answers
   */
  omit?: Prisma.poll_submission_answersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.poll_submission_answersInclude<ExtArgs> | null
  /**
   * Filter, which poll_submission_answers to fetch.
   */
  where: Prisma.poll_submission_answersWhereUniqueInput
}

/**
 * poll_submission_answers findFirst
 */
export type poll_submission_answersFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the poll_submission_answers
   */
  select?: Prisma.poll_submission_answersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the poll_submission_answers
   */
  omit?: Prisma.poll_submission_answersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.poll_submission_answersInclude<ExtArgs> | null
  /**
   * Filter, which poll_submission_answers to fetch.
   */
  where?: Prisma.poll_submission_answersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of poll_submission_answers to fetch.
   */
  orderBy?: Prisma.poll_submission_answersOrderByWithRelationInput | Prisma.poll_submission_answersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for poll_submission_answers.
   */
  cursor?: Prisma.poll_submission_answersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` poll_submission_answers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` poll_submission_answers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of poll_submission_answers.
   */
  distinct?: Prisma.Poll_submission_answersScalarFieldEnum | Prisma.Poll_submission_answersScalarFieldEnum[]
}

/**
 * poll_submission_answers findFirstOrThrow
 */
export type poll_submission_answersFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the poll_submission_answers
   */
  select?: Prisma.poll_submission_answersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the poll_submission_answers
   */
  omit?: Prisma.poll_submission_answersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.poll_submission_answersInclude<ExtArgs> | null
  /**
   * Filter, which poll_submission_answers to fetch.
   */
  where?: Prisma.poll_submission_answersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of poll_submission_answers to fetch.
   */
  orderBy?: Prisma.poll_submission_answersOrderByWithRelationInput | Prisma.poll_submission_answersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for poll_submission_answers.
   */
  cursor?: Prisma.poll_submission_answersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` poll_submission_answers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` poll_submission_answers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of poll_submission_answers.
   */
  distinct?: Prisma.Poll_submission_answersScalarFieldEnum | Prisma.Poll_submission_answersScalarFieldEnum[]
}

/**
 * poll_submission_answers findMany
 */
export type poll_submission_answersFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the poll_submission_answers
   */
  select?: Prisma.poll_submission_answersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the poll_submission_answers
   */
  omit?: Prisma.poll_submission_answersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.poll_submission_answersInclude<ExtArgs> | null
  /**
   * Filter, which poll_submission_answers to fetch.
   */
  where?: Prisma.poll_submission_answersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of poll_submission_answers to fetch.
   */
  orderBy?: Prisma.poll_submission_answersOrderByWithRelationInput | Prisma.poll_submission_answersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing poll_submission_answers.
   */
  cursor?: Prisma.poll_submission_answersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` poll_submission_answers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` poll_submission_answers.
   */
  skip?: number
  distinct?: Prisma.Poll_submission_answersScalarFieldEnum | Prisma.Poll_submission_answersScalarFieldEnum[]
}

/**
 * poll_submission_answers create
 */
export type poll_submission_answersCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the poll_submission_answers
   */
  select?: Prisma.poll_submission_answersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the poll_submission_answers
   */
  omit?: Prisma.poll_submission_answersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.poll_submission_answersInclude<ExtArgs> | null
  /**
   * The data needed to create a poll_submission_answers.
   */
  data: Prisma.XOR<Prisma.poll_submission_answersCreateInput, Prisma.poll_submission_answersUncheckedCreateInput>
}

/**
 * poll_submission_answers createMany
 */
export type poll_submission_answersCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many poll_submission_answers.
   */
  data: Prisma.poll_submission_answersCreateManyInput | Prisma.poll_submission_answersCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * poll_submission_answers createManyAndReturn
 */
export type poll_submission_answersCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the poll_submission_answers
   */
  select?: Prisma.poll_submission_answersSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the poll_submission_answers
   */
  omit?: Prisma.poll_submission_answersOmit<ExtArgs> | null
  /**
   * The data used to create many poll_submission_answers.
   */
  data: Prisma.poll_submission_answersCreateManyInput | Prisma.poll_submission_answersCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.poll_submission_answersIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * poll_submission_answers update
 */
export type poll_submission_answersUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the poll_submission_answers
   */
  select?: Prisma.poll_submission_answersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the poll_submission_answers
   */
  omit?: Prisma.poll_submission_answersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.poll_submission_answersInclude<ExtArgs> | null
  /**
   * The data needed to update a poll_submission_answers.
   */
  data: Prisma.XOR<Prisma.poll_submission_answersUpdateInput, Prisma.poll_submission_answersUncheckedUpdateInput>
  /**
   * Choose, which poll_submission_answers to update.
   */
  where: Prisma.poll_submission_answersWhereUniqueInput
}

/**
 * poll_submission_answers updateMany
 */
export type poll_submission_answersUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update poll_submission_answers.
   */
  data: Prisma.XOR<Prisma.poll_submission_answersUpdateManyMutationInput, Prisma.poll_submission_answersUncheckedUpdateManyInput>
  /**
   * Filter which poll_submission_answers to update
   */
  where?: Prisma.poll_submission_answersWhereInput
  /**
   * Limit how many poll_submission_answers to update.
   */
  limit?: number
}

/**
 * poll_submission_answers updateManyAndReturn
 */
export type poll_submission_answersUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the poll_submission_answers
   */
  select?: Prisma.poll_submission_answersSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the poll_submission_answers
   */
  omit?: Prisma.poll_submission_answersOmit<ExtArgs> | null
  /**
   * The data used to update poll_submission_answers.
   */
  data: Prisma.XOR<Prisma.poll_submission_answersUpdateManyMutationInput, Prisma.poll_submission_answersUncheckedUpdateManyInput>
  /**
   * Filter which poll_submission_answers to update
   */
  where?: Prisma.poll_submission_answersWhereInput
  /**
   * Limit how many poll_submission_answers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.poll_submission_answersIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * poll_submission_answers upsert
 */
export type poll_submission_answersUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the poll_submission_answers
   */
  select?: Prisma.poll_submission_answersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the poll_submission_answers
   */
  omit?: Prisma.poll_submission_answersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.poll_submission_answersInclude<ExtArgs> | null
  /**
   * The filter to search for the poll_submission_answers to update in case it exists.
   */
  where: Prisma.poll_submission_answersWhereUniqueInput
  /**
   * In case the poll_submission_answers found by the `where` argument doesn't exist, create a new poll_submission_answers with this data.
   */
  create: Prisma.XOR<Prisma.poll_submission_answersCreateInput, Prisma.poll_submission_answersUncheckedCreateInput>
  /**
   * In case the poll_submission_answers was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.poll_submission_answersUpdateInput, Prisma.poll_submission_answersUncheckedUpdateInput>
}

/**
 * poll_submission_answers delete
 */
export type poll_submission_answersDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the poll_submission_answers
   */
  select?: Prisma.poll_submission_answersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the poll_submission_answers
   */
  omit?: Prisma.poll_submission_answersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.poll_submission_answersInclude<ExtArgs> | null
  /**
   * Filter which poll_submission_answers to delete.
   */
  where: Prisma.poll_submission_answersWhereUniqueInput
}

/**
 * poll_submission_answers deleteMany
 */
export type poll_submission_answersDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which poll_submission_answers to delete
   */
  where?: Prisma.poll_submission_answersWhereInput
  /**
   * Limit how many poll_submission_answers to delete.
   */
  limit?: number
}

/**
 * poll_submission_answers without action
 */
export type poll_submission_answersDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the poll_submission_answers
   */
  select?: Prisma.poll_submission_answersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the poll_submission_answers
   */
  omit?: Prisma.poll_submission_answersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.poll_submission_answersInclude<ExtArgs> | null
}
