
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `property_media` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model property_media
 * This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
 * This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info.
 */
export type property_mediaModel = runtime.Types.Result.DefaultSelection<Prisma.$property_mediaPayload>

export type AggregateProperty_media = {
  _count: Property_mediaCountAggregateOutputType | null
  _avg: Property_mediaAvgAggregateOutputType | null
  _sum: Property_mediaSumAggregateOutputType | null
  _min: Property_mediaMinAggregateOutputType | null
  _max: Property_mediaMaxAggregateOutputType | null
}

export type Property_mediaAvgAggregateOutputType = {
  display_order: number | null
}

export type Property_mediaSumAggregateOutputType = {
  display_order: number | null
}

export type Property_mediaMinAggregateOutputType = {
  id: string | null
  property_id: string | null
  media_type: string | null
  media_url: string | null
  file_name: string | null
  display_order: number | null
  is_featured: boolean | null
  created_at: Date | null
}

export type Property_mediaMaxAggregateOutputType = {
  id: string | null
  property_id: string | null
  media_type: string | null
  media_url: string | null
  file_name: string | null
  display_order: number | null
  is_featured: boolean | null
  created_at: Date | null
}

export type Property_mediaCountAggregateOutputType = {
  id: number
  property_id: number
  media_type: number
  media_url: number
  file_name: number
  display_order: number
  is_featured: number
  created_at: number
  _all: number
}


export type Property_mediaAvgAggregateInputType = {
  display_order?: true
}

export type Property_mediaSumAggregateInputType = {
  display_order?: true
}

export type Property_mediaMinAggregateInputType = {
  id?: true
  property_id?: true
  media_type?: true
  media_url?: true
  file_name?: true
  display_order?: true
  is_featured?: true
  created_at?: true
}

export type Property_mediaMaxAggregateInputType = {
  id?: true
  property_id?: true
  media_type?: true
  media_url?: true
  file_name?: true
  display_order?: true
  is_featured?: true
  created_at?: true
}

export type Property_mediaCountAggregateInputType = {
  id?: true
  property_id?: true
  media_type?: true
  media_url?: true
  file_name?: true
  display_order?: true
  is_featured?: true
  created_at?: true
  _all?: true
}

export type Property_mediaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which property_media to aggregate.
   */
  where?: Prisma.property_mediaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of property_medias to fetch.
   */
  orderBy?: Prisma.property_mediaOrderByWithRelationInput | Prisma.property_mediaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.property_mediaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` property_medias from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` property_medias.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned property_medias
  **/
  _count?: true | Property_mediaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Property_mediaAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Property_mediaSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Property_mediaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Property_mediaMaxAggregateInputType
}

export type GetProperty_mediaAggregateType<T extends Property_mediaAggregateArgs> = {
      [P in keyof T & keyof AggregateProperty_media]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProperty_media[P]>
    : Prisma.GetScalarType<T[P], AggregateProperty_media[P]>
}




export type property_mediaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.property_mediaWhereInput
  orderBy?: Prisma.property_mediaOrderByWithAggregationInput | Prisma.property_mediaOrderByWithAggregationInput[]
  by: Prisma.Property_mediaScalarFieldEnum[] | Prisma.Property_mediaScalarFieldEnum
  having?: Prisma.property_mediaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Property_mediaCountAggregateInputType | true
  _avg?: Property_mediaAvgAggregateInputType
  _sum?: Property_mediaSumAggregateInputType
  _min?: Property_mediaMinAggregateInputType
  _max?: Property_mediaMaxAggregateInputType
}

export type Property_mediaGroupByOutputType = {
  id: string
  property_id: string
  media_type: string
  media_url: string
  file_name: string
  display_order: number | null
  is_featured: boolean | null
  created_at: Date | null
  _count: Property_mediaCountAggregateOutputType | null
  _avg: Property_mediaAvgAggregateOutputType | null
  _sum: Property_mediaSumAggregateOutputType | null
  _min: Property_mediaMinAggregateOutputType | null
  _max: Property_mediaMaxAggregateOutputType | null
}

type GetProperty_mediaGroupByPayload<T extends property_mediaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Property_mediaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Property_mediaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Property_mediaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Property_mediaGroupByOutputType[P]>
      }
    >
  >



export type property_mediaWhereInput = {
  AND?: Prisma.property_mediaWhereInput | Prisma.property_mediaWhereInput[]
  OR?: Prisma.property_mediaWhereInput[]
  NOT?: Prisma.property_mediaWhereInput | Prisma.property_mediaWhereInput[]
  id?: Prisma.UuidFilter<"property_media"> | string
  property_id?: Prisma.UuidFilter<"property_media"> | string
  media_type?: Prisma.StringFilter<"property_media"> | string
  media_url?: Prisma.StringFilter<"property_media"> | string
  file_name?: Prisma.StringFilter<"property_media"> | string
  display_order?: Prisma.IntNullableFilter<"property_media"> | number | null
  is_featured?: Prisma.BoolNullableFilter<"property_media"> | boolean | null
  created_at?: Prisma.DateTimeNullableFilter<"property_media"> | Date | string | null
  properties?: Prisma.XOR<Prisma.PropertiesScalarRelationFilter, Prisma.propertiesWhereInput>
}

export type property_mediaOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  property_id?: Prisma.SortOrder
  media_type?: Prisma.SortOrder
  media_url?: Prisma.SortOrder
  file_name?: Prisma.SortOrder
  display_order?: Prisma.SortOrderInput | Prisma.SortOrder
  is_featured?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  properties?: Prisma.propertiesOrderByWithRelationInput
}

export type property_mediaWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.property_mediaWhereInput | Prisma.property_mediaWhereInput[]
  OR?: Prisma.property_mediaWhereInput[]
  NOT?: Prisma.property_mediaWhereInput | Prisma.property_mediaWhereInput[]
  property_id?: Prisma.UuidFilter<"property_media"> | string
  media_type?: Prisma.StringFilter<"property_media"> | string
  media_url?: Prisma.StringFilter<"property_media"> | string
  file_name?: Prisma.StringFilter<"property_media"> | string
  display_order?: Prisma.IntNullableFilter<"property_media"> | number | null
  is_featured?: Prisma.BoolNullableFilter<"property_media"> | boolean | null
  created_at?: Prisma.DateTimeNullableFilter<"property_media"> | Date | string | null
  properties?: Prisma.XOR<Prisma.PropertiesScalarRelationFilter, Prisma.propertiesWhereInput>
}, "id">

export type property_mediaOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  property_id?: Prisma.SortOrder
  media_type?: Prisma.SortOrder
  media_url?: Prisma.SortOrder
  file_name?: Prisma.SortOrder
  display_order?: Prisma.SortOrderInput | Prisma.SortOrder
  is_featured?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.property_mediaCountOrderByAggregateInput
  _avg?: Prisma.property_mediaAvgOrderByAggregateInput
  _max?: Prisma.property_mediaMaxOrderByAggregateInput
  _min?: Prisma.property_mediaMinOrderByAggregateInput
  _sum?: Prisma.property_mediaSumOrderByAggregateInput
}

export type property_mediaScalarWhereWithAggregatesInput = {
  AND?: Prisma.property_mediaScalarWhereWithAggregatesInput | Prisma.property_mediaScalarWhereWithAggregatesInput[]
  OR?: Prisma.property_mediaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.property_mediaScalarWhereWithAggregatesInput | Prisma.property_mediaScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"property_media"> | string
  property_id?: Prisma.UuidWithAggregatesFilter<"property_media"> | string
  media_type?: Prisma.StringWithAggregatesFilter<"property_media"> | string
  media_url?: Prisma.StringWithAggregatesFilter<"property_media"> | string
  file_name?: Prisma.StringWithAggregatesFilter<"property_media"> | string
  display_order?: Prisma.IntNullableWithAggregatesFilter<"property_media"> | number | null
  is_featured?: Prisma.BoolNullableWithAggregatesFilter<"property_media"> | boolean | null
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"property_media"> | Date | string | null
}

export type property_mediaCreateInput = {
  id?: string
  media_type: string
  media_url: string
  file_name: string
  display_order?: number | null
  is_featured?: boolean | null
  created_at?: Date | string | null
  properties: Prisma.propertiesCreateNestedOneWithoutProperty_mediaInput
}

export type property_mediaUncheckedCreateInput = {
  id?: string
  property_id: string
  media_type: string
  media_url: string
  file_name: string
  display_order?: number | null
  is_featured?: boolean | null
  created_at?: Date | string | null
}

export type property_mediaUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  media_type?: Prisma.StringFieldUpdateOperationsInput | string
  media_url?: Prisma.StringFieldUpdateOperationsInput | string
  file_name?: Prisma.StringFieldUpdateOperationsInput | string
  display_order?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_featured?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  properties?: Prisma.propertiesUpdateOneRequiredWithoutProperty_mediaNestedInput
}

export type property_mediaUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  property_id?: Prisma.StringFieldUpdateOperationsInput | string
  media_type?: Prisma.StringFieldUpdateOperationsInput | string
  media_url?: Prisma.StringFieldUpdateOperationsInput | string
  file_name?: Prisma.StringFieldUpdateOperationsInput | string
  display_order?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_featured?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type property_mediaCreateManyInput = {
  id?: string
  property_id: string
  media_type: string
  media_url: string
  file_name: string
  display_order?: number | null
  is_featured?: boolean | null
  created_at?: Date | string | null
}

export type property_mediaUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  media_type?: Prisma.StringFieldUpdateOperationsInput | string
  media_url?: Prisma.StringFieldUpdateOperationsInput | string
  file_name?: Prisma.StringFieldUpdateOperationsInput | string
  display_order?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_featured?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type property_mediaUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  property_id?: Prisma.StringFieldUpdateOperationsInput | string
  media_type?: Prisma.StringFieldUpdateOperationsInput | string
  media_url?: Prisma.StringFieldUpdateOperationsInput | string
  file_name?: Prisma.StringFieldUpdateOperationsInput | string
  display_order?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_featured?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type Property_mediaListRelationFilter = {
  every?: Prisma.property_mediaWhereInput
  some?: Prisma.property_mediaWhereInput
  none?: Prisma.property_mediaWhereInput
}

export type property_mediaOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type property_mediaCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  property_id?: Prisma.SortOrder
  media_type?: Prisma.SortOrder
  media_url?: Prisma.SortOrder
  file_name?: Prisma.SortOrder
  display_order?: Prisma.SortOrder
  is_featured?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type property_mediaAvgOrderByAggregateInput = {
  display_order?: Prisma.SortOrder
}

export type property_mediaMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  property_id?: Prisma.SortOrder
  media_type?: Prisma.SortOrder
  media_url?: Prisma.SortOrder
  file_name?: Prisma.SortOrder
  display_order?: Prisma.SortOrder
  is_featured?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type property_mediaMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  property_id?: Prisma.SortOrder
  media_type?: Prisma.SortOrder
  media_url?: Prisma.SortOrder
  file_name?: Prisma.SortOrder
  display_order?: Prisma.SortOrder
  is_featured?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type property_mediaSumOrderByAggregateInput = {
  display_order?: Prisma.SortOrder
}

export type property_mediaCreateNestedManyWithoutPropertiesInput = {
  create?: Prisma.XOR<Prisma.property_mediaCreateWithoutPropertiesInput, Prisma.property_mediaUncheckedCreateWithoutPropertiesInput> | Prisma.property_mediaCreateWithoutPropertiesInput[] | Prisma.property_mediaUncheckedCreateWithoutPropertiesInput[]
  connectOrCreate?: Prisma.property_mediaCreateOrConnectWithoutPropertiesInput | Prisma.property_mediaCreateOrConnectWithoutPropertiesInput[]
  createMany?: Prisma.property_mediaCreateManyPropertiesInputEnvelope
  connect?: Prisma.property_mediaWhereUniqueInput | Prisma.property_mediaWhereUniqueInput[]
}

export type property_mediaUncheckedCreateNestedManyWithoutPropertiesInput = {
  create?: Prisma.XOR<Prisma.property_mediaCreateWithoutPropertiesInput, Prisma.property_mediaUncheckedCreateWithoutPropertiesInput> | Prisma.property_mediaCreateWithoutPropertiesInput[] | Prisma.property_mediaUncheckedCreateWithoutPropertiesInput[]
  connectOrCreate?: Prisma.property_mediaCreateOrConnectWithoutPropertiesInput | Prisma.property_mediaCreateOrConnectWithoutPropertiesInput[]
  createMany?: Prisma.property_mediaCreateManyPropertiesInputEnvelope
  connect?: Prisma.property_mediaWhereUniqueInput | Prisma.property_mediaWhereUniqueInput[]
}

export type property_mediaUpdateManyWithoutPropertiesNestedInput = {
  create?: Prisma.XOR<Prisma.property_mediaCreateWithoutPropertiesInput, Prisma.property_mediaUncheckedCreateWithoutPropertiesInput> | Prisma.property_mediaCreateWithoutPropertiesInput[] | Prisma.property_mediaUncheckedCreateWithoutPropertiesInput[]
  connectOrCreate?: Prisma.property_mediaCreateOrConnectWithoutPropertiesInput | Prisma.property_mediaCreateOrConnectWithoutPropertiesInput[]
  upsert?: Prisma.property_mediaUpsertWithWhereUniqueWithoutPropertiesInput | Prisma.property_mediaUpsertWithWhereUniqueWithoutPropertiesInput[]
  createMany?: Prisma.property_mediaCreateManyPropertiesInputEnvelope
  set?: Prisma.property_mediaWhereUniqueInput | Prisma.property_mediaWhereUniqueInput[]
  disconnect?: Prisma.property_mediaWhereUniqueInput | Prisma.property_mediaWhereUniqueInput[]
  delete?: Prisma.property_mediaWhereUniqueInput | Prisma.property_mediaWhereUniqueInput[]
  connect?: Prisma.property_mediaWhereUniqueInput | Prisma.property_mediaWhereUniqueInput[]
  update?: Prisma.property_mediaUpdateWithWhereUniqueWithoutPropertiesInput | Prisma.property_mediaUpdateWithWhereUniqueWithoutPropertiesInput[]
  updateMany?: Prisma.property_mediaUpdateManyWithWhereWithoutPropertiesInput | Prisma.property_mediaUpdateManyWithWhereWithoutPropertiesInput[]
  deleteMany?: Prisma.property_mediaScalarWhereInput | Prisma.property_mediaScalarWhereInput[]
}

export type property_mediaUncheckedUpdateManyWithoutPropertiesNestedInput = {
  create?: Prisma.XOR<Prisma.property_mediaCreateWithoutPropertiesInput, Prisma.property_mediaUncheckedCreateWithoutPropertiesInput> | Prisma.property_mediaCreateWithoutPropertiesInput[] | Prisma.property_mediaUncheckedCreateWithoutPropertiesInput[]
  connectOrCreate?: Prisma.property_mediaCreateOrConnectWithoutPropertiesInput | Prisma.property_mediaCreateOrConnectWithoutPropertiesInput[]
  upsert?: Prisma.property_mediaUpsertWithWhereUniqueWithoutPropertiesInput | Prisma.property_mediaUpsertWithWhereUniqueWithoutPropertiesInput[]
  createMany?: Prisma.property_mediaCreateManyPropertiesInputEnvelope
  set?: Prisma.property_mediaWhereUniqueInput | Prisma.property_mediaWhereUniqueInput[]
  disconnect?: Prisma.property_mediaWhereUniqueInput | Prisma.property_mediaWhereUniqueInput[]
  delete?: Prisma.property_mediaWhereUniqueInput | Prisma.property_mediaWhereUniqueInput[]
  connect?: Prisma.property_mediaWhereUniqueInput | Prisma.property_mediaWhereUniqueInput[]
  update?: Prisma.property_mediaUpdateWithWhereUniqueWithoutPropertiesInput | Prisma.property_mediaUpdateWithWhereUniqueWithoutPropertiesInput[]
  updateMany?: Prisma.property_mediaUpdateManyWithWhereWithoutPropertiesInput | Prisma.property_mediaUpdateManyWithWhereWithoutPropertiesInput[]
  deleteMany?: Prisma.property_mediaScalarWhereInput | Prisma.property_mediaScalarWhereInput[]
}

export type property_mediaCreateWithoutPropertiesInput = {
  id?: string
  media_type: string
  media_url: string
  file_name: string
  display_order?: number | null
  is_featured?: boolean | null
  created_at?: Date | string | null
}

export type property_mediaUncheckedCreateWithoutPropertiesInput = {
  id?: string
  media_type: string
  media_url: string
  file_name: string
  display_order?: number | null
  is_featured?: boolean | null
  created_at?: Date | string | null
}

export type property_mediaCreateOrConnectWithoutPropertiesInput = {
  where: Prisma.property_mediaWhereUniqueInput
  create: Prisma.XOR<Prisma.property_mediaCreateWithoutPropertiesInput, Prisma.property_mediaUncheckedCreateWithoutPropertiesInput>
}

export type property_mediaCreateManyPropertiesInputEnvelope = {
  data: Prisma.property_mediaCreateManyPropertiesInput | Prisma.property_mediaCreateManyPropertiesInput[]
  skipDuplicates?: boolean
}

export type property_mediaUpsertWithWhereUniqueWithoutPropertiesInput = {
  where: Prisma.property_mediaWhereUniqueInput
  update: Prisma.XOR<Prisma.property_mediaUpdateWithoutPropertiesInput, Prisma.property_mediaUncheckedUpdateWithoutPropertiesInput>
  create: Prisma.XOR<Prisma.property_mediaCreateWithoutPropertiesInput, Prisma.property_mediaUncheckedCreateWithoutPropertiesInput>
}

export type property_mediaUpdateWithWhereUniqueWithoutPropertiesInput = {
  where: Prisma.property_mediaWhereUniqueInput
  data: Prisma.XOR<Prisma.property_mediaUpdateWithoutPropertiesInput, Prisma.property_mediaUncheckedUpdateWithoutPropertiesInput>
}

export type property_mediaUpdateManyWithWhereWithoutPropertiesInput = {
  where: Prisma.property_mediaScalarWhereInput
  data: Prisma.XOR<Prisma.property_mediaUpdateManyMutationInput, Prisma.property_mediaUncheckedUpdateManyWithoutPropertiesInput>
}

export type property_mediaScalarWhereInput = {
  AND?: Prisma.property_mediaScalarWhereInput | Prisma.property_mediaScalarWhereInput[]
  OR?: Prisma.property_mediaScalarWhereInput[]
  NOT?: Prisma.property_mediaScalarWhereInput | Prisma.property_mediaScalarWhereInput[]
  id?: Prisma.UuidFilter<"property_media"> | string
  property_id?: Prisma.UuidFilter<"property_media"> | string
  media_type?: Prisma.StringFilter<"property_media"> | string
  media_url?: Prisma.StringFilter<"property_media"> | string
  file_name?: Prisma.StringFilter<"property_media"> | string
  display_order?: Prisma.IntNullableFilter<"property_media"> | number | null
  is_featured?: Prisma.BoolNullableFilter<"property_media"> | boolean | null
  created_at?: Prisma.DateTimeNullableFilter<"property_media"> | Date | string | null
}

export type property_mediaCreateManyPropertiesInput = {
  id?: string
  media_type: string
  media_url: string
  file_name: string
  display_order?: number | null
  is_featured?: boolean | null
  created_at?: Date | string | null
}

export type property_mediaUpdateWithoutPropertiesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  media_type?: Prisma.StringFieldUpdateOperationsInput | string
  media_url?: Prisma.StringFieldUpdateOperationsInput | string
  file_name?: Prisma.StringFieldUpdateOperationsInput | string
  display_order?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_featured?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type property_mediaUncheckedUpdateWithoutPropertiesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  media_type?: Prisma.StringFieldUpdateOperationsInput | string
  media_url?: Prisma.StringFieldUpdateOperationsInput | string
  file_name?: Prisma.StringFieldUpdateOperationsInput | string
  display_order?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_featured?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type property_mediaUncheckedUpdateManyWithoutPropertiesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  media_type?: Prisma.StringFieldUpdateOperationsInput | string
  media_url?: Prisma.StringFieldUpdateOperationsInput | string
  file_name?: Prisma.StringFieldUpdateOperationsInput | string
  display_order?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  is_featured?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type property_mediaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  property_id?: boolean
  media_type?: boolean
  media_url?: boolean
  file_name?: boolean
  display_order?: boolean
  is_featured?: boolean
  created_at?: boolean
  properties?: boolean | Prisma.propertiesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["property_media"]>

export type property_mediaSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  property_id?: boolean
  media_type?: boolean
  media_url?: boolean
  file_name?: boolean
  display_order?: boolean
  is_featured?: boolean
  created_at?: boolean
  properties?: boolean | Prisma.propertiesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["property_media"]>

export type property_mediaSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  property_id?: boolean
  media_type?: boolean
  media_url?: boolean
  file_name?: boolean
  display_order?: boolean
  is_featured?: boolean
  created_at?: boolean
  properties?: boolean | Prisma.propertiesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["property_media"]>

export type property_mediaSelectScalar = {
  id?: boolean
  property_id?: boolean
  media_type?: boolean
  media_url?: boolean
  file_name?: boolean
  display_order?: boolean
  is_featured?: boolean
  created_at?: boolean
}

export type property_mediaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "property_id" | "media_type" | "media_url" | "file_name" | "display_order" | "is_featured" | "created_at", ExtArgs["result"]["property_media"]>
export type property_mediaInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  properties?: boolean | Prisma.propertiesDefaultArgs<ExtArgs>
}
export type property_mediaIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  properties?: boolean | Prisma.propertiesDefaultArgs<ExtArgs>
}
export type property_mediaIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  properties?: boolean | Prisma.propertiesDefaultArgs<ExtArgs>
}

export type $property_mediaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "property_media"
  objects: {
    properties: Prisma.$propertiesPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    property_id: string
    media_type: string
    media_url: string
    file_name: string
    display_order: number | null
    is_featured: boolean | null
    created_at: Date | null
  }, ExtArgs["result"]["property_media"]>
  composites: {}
}

export type property_mediaGetPayload<S extends boolean | null | undefined | property_mediaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$property_mediaPayload, S>

export type property_mediaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<property_mediaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Property_mediaCountAggregateInputType | true
  }

export interface property_mediaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['property_media'], meta: { name: 'property_media' } }
  /**
   * Find zero or one Property_media that matches the filter.
   * @param {property_mediaFindUniqueArgs} args - Arguments to find a Property_media
   * @example
   * // Get one Property_media
   * const property_media = await prisma.property_media.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends property_mediaFindUniqueArgs>(args: Prisma.SelectSubset<T, property_mediaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__property_mediaClient<runtime.Types.Result.GetResult<Prisma.$property_mediaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Property_media that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {property_mediaFindUniqueOrThrowArgs} args - Arguments to find a Property_media
   * @example
   * // Get one Property_media
   * const property_media = await prisma.property_media.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends property_mediaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, property_mediaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__property_mediaClient<runtime.Types.Result.GetResult<Prisma.$property_mediaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Property_media that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {property_mediaFindFirstArgs} args - Arguments to find a Property_media
   * @example
   * // Get one Property_media
   * const property_media = await prisma.property_media.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends property_mediaFindFirstArgs>(args?: Prisma.SelectSubset<T, property_mediaFindFirstArgs<ExtArgs>>): Prisma.Prisma__property_mediaClient<runtime.Types.Result.GetResult<Prisma.$property_mediaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Property_media that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {property_mediaFindFirstOrThrowArgs} args - Arguments to find a Property_media
   * @example
   * // Get one Property_media
   * const property_media = await prisma.property_media.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends property_mediaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, property_mediaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__property_mediaClient<runtime.Types.Result.GetResult<Prisma.$property_mediaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Property_medias that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {property_mediaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Property_medias
   * const property_medias = await prisma.property_media.findMany()
   * 
   * // Get first 10 Property_medias
   * const property_medias = await prisma.property_media.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const property_mediaWithIdOnly = await prisma.property_media.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends property_mediaFindManyArgs>(args?: Prisma.SelectSubset<T, property_mediaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$property_mediaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Property_media.
   * @param {property_mediaCreateArgs} args - Arguments to create a Property_media.
   * @example
   * // Create one Property_media
   * const Property_media = await prisma.property_media.create({
   *   data: {
   *     // ... data to create a Property_media
   *   }
   * })
   * 
   */
  create<T extends property_mediaCreateArgs>(args: Prisma.SelectSubset<T, property_mediaCreateArgs<ExtArgs>>): Prisma.Prisma__property_mediaClient<runtime.Types.Result.GetResult<Prisma.$property_mediaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Property_medias.
   * @param {property_mediaCreateManyArgs} args - Arguments to create many Property_medias.
   * @example
   * // Create many Property_medias
   * const property_media = await prisma.property_media.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends property_mediaCreateManyArgs>(args?: Prisma.SelectSubset<T, property_mediaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Property_medias and returns the data saved in the database.
   * @param {property_mediaCreateManyAndReturnArgs} args - Arguments to create many Property_medias.
   * @example
   * // Create many Property_medias
   * const property_media = await prisma.property_media.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Property_medias and only return the `id`
   * const property_mediaWithIdOnly = await prisma.property_media.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends property_mediaCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, property_mediaCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$property_mediaPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Property_media.
   * @param {property_mediaDeleteArgs} args - Arguments to delete one Property_media.
   * @example
   * // Delete one Property_media
   * const Property_media = await prisma.property_media.delete({
   *   where: {
   *     // ... filter to delete one Property_media
   *   }
   * })
   * 
   */
  delete<T extends property_mediaDeleteArgs>(args: Prisma.SelectSubset<T, property_mediaDeleteArgs<ExtArgs>>): Prisma.Prisma__property_mediaClient<runtime.Types.Result.GetResult<Prisma.$property_mediaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Property_media.
   * @param {property_mediaUpdateArgs} args - Arguments to update one Property_media.
   * @example
   * // Update one Property_media
   * const property_media = await prisma.property_media.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends property_mediaUpdateArgs>(args: Prisma.SelectSubset<T, property_mediaUpdateArgs<ExtArgs>>): Prisma.Prisma__property_mediaClient<runtime.Types.Result.GetResult<Prisma.$property_mediaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Property_medias.
   * @param {property_mediaDeleteManyArgs} args - Arguments to filter Property_medias to delete.
   * @example
   * // Delete a few Property_medias
   * const { count } = await prisma.property_media.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends property_mediaDeleteManyArgs>(args?: Prisma.SelectSubset<T, property_mediaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Property_medias.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {property_mediaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Property_medias
   * const property_media = await prisma.property_media.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends property_mediaUpdateManyArgs>(args: Prisma.SelectSubset<T, property_mediaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Property_medias and returns the data updated in the database.
   * @param {property_mediaUpdateManyAndReturnArgs} args - Arguments to update many Property_medias.
   * @example
   * // Update many Property_medias
   * const property_media = await prisma.property_media.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Property_medias and only return the `id`
   * const property_mediaWithIdOnly = await prisma.property_media.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends property_mediaUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, property_mediaUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$property_mediaPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Property_media.
   * @param {property_mediaUpsertArgs} args - Arguments to update or create a Property_media.
   * @example
   * // Update or create a Property_media
   * const property_media = await prisma.property_media.upsert({
   *   create: {
   *     // ... data to create a Property_media
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Property_media we want to update
   *   }
   * })
   */
  upsert<T extends property_mediaUpsertArgs>(args: Prisma.SelectSubset<T, property_mediaUpsertArgs<ExtArgs>>): Prisma.Prisma__property_mediaClient<runtime.Types.Result.GetResult<Prisma.$property_mediaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Property_medias.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {property_mediaCountArgs} args - Arguments to filter Property_medias to count.
   * @example
   * // Count the number of Property_medias
   * const count = await prisma.property_media.count({
   *   where: {
   *     // ... the filter for the Property_medias we want to count
   *   }
   * })
  **/
  count<T extends property_mediaCountArgs>(
    args?: Prisma.Subset<T, property_mediaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Property_mediaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Property_media.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Property_mediaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Property_mediaAggregateArgs>(args: Prisma.Subset<T, Property_mediaAggregateArgs>): Prisma.PrismaPromise<GetProperty_mediaAggregateType<T>>

  /**
   * Group by Property_media.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {property_mediaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends property_mediaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: property_mediaGroupByArgs['orderBy'] }
      : { orderBy?: property_mediaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, property_mediaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProperty_mediaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the property_media model
 */
readonly fields: property_mediaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for property_media.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__property_mediaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  properties<T extends Prisma.propertiesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.propertiesDefaultArgs<ExtArgs>>): Prisma.Prisma__propertiesClient<runtime.Types.Result.GetResult<Prisma.$propertiesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the property_media model
 */
export interface property_mediaFieldRefs {
  readonly id: Prisma.FieldRef<"property_media", 'String'>
  readonly property_id: Prisma.FieldRef<"property_media", 'String'>
  readonly media_type: Prisma.FieldRef<"property_media", 'String'>
  readonly media_url: Prisma.FieldRef<"property_media", 'String'>
  readonly file_name: Prisma.FieldRef<"property_media", 'String'>
  readonly display_order: Prisma.FieldRef<"property_media", 'Int'>
  readonly is_featured: Prisma.FieldRef<"property_media", 'Boolean'>
  readonly created_at: Prisma.FieldRef<"property_media", 'DateTime'>
}
    

// Custom InputTypes
/**
 * property_media findUnique
 */
export type property_mediaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the property_media
   */
  select?: Prisma.property_mediaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the property_media
   */
  omit?: Prisma.property_mediaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.property_mediaInclude<ExtArgs> | null
  /**
   * Filter, which property_media to fetch.
   */
  where: Prisma.property_mediaWhereUniqueInput
}

/**
 * property_media findUniqueOrThrow
 */
export type property_mediaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the property_media
   */
  select?: Prisma.property_mediaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the property_media
   */
  omit?: Prisma.property_mediaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.property_mediaInclude<ExtArgs> | null
  /**
   * Filter, which property_media to fetch.
   */
  where: Prisma.property_mediaWhereUniqueInput
}

/**
 * property_media findFirst
 */
export type property_mediaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the property_media
   */
  select?: Prisma.property_mediaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the property_media
   */
  omit?: Prisma.property_mediaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.property_mediaInclude<ExtArgs> | null
  /**
   * Filter, which property_media to fetch.
   */
  where?: Prisma.property_mediaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of property_medias to fetch.
   */
  orderBy?: Prisma.property_mediaOrderByWithRelationInput | Prisma.property_mediaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for property_medias.
   */
  cursor?: Prisma.property_mediaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` property_medias from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` property_medias.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of property_medias.
   */
  distinct?: Prisma.Property_mediaScalarFieldEnum | Prisma.Property_mediaScalarFieldEnum[]
}

/**
 * property_media findFirstOrThrow
 */
export type property_mediaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the property_media
   */
  select?: Prisma.property_mediaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the property_media
   */
  omit?: Prisma.property_mediaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.property_mediaInclude<ExtArgs> | null
  /**
   * Filter, which property_media to fetch.
   */
  where?: Prisma.property_mediaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of property_medias to fetch.
   */
  orderBy?: Prisma.property_mediaOrderByWithRelationInput | Prisma.property_mediaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for property_medias.
   */
  cursor?: Prisma.property_mediaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` property_medias from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` property_medias.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of property_medias.
   */
  distinct?: Prisma.Property_mediaScalarFieldEnum | Prisma.Property_mediaScalarFieldEnum[]
}

/**
 * property_media findMany
 */
export type property_mediaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the property_media
   */
  select?: Prisma.property_mediaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the property_media
   */
  omit?: Prisma.property_mediaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.property_mediaInclude<ExtArgs> | null
  /**
   * Filter, which property_medias to fetch.
   */
  where?: Prisma.property_mediaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of property_medias to fetch.
   */
  orderBy?: Prisma.property_mediaOrderByWithRelationInput | Prisma.property_mediaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing property_medias.
   */
  cursor?: Prisma.property_mediaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` property_medias from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` property_medias.
   */
  skip?: number
  distinct?: Prisma.Property_mediaScalarFieldEnum | Prisma.Property_mediaScalarFieldEnum[]
}

/**
 * property_media create
 */
export type property_mediaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the property_media
   */
  select?: Prisma.property_mediaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the property_media
   */
  omit?: Prisma.property_mediaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.property_mediaInclude<ExtArgs> | null
  /**
   * The data needed to create a property_media.
   */
  data: Prisma.XOR<Prisma.property_mediaCreateInput, Prisma.property_mediaUncheckedCreateInput>
}

/**
 * property_media createMany
 */
export type property_mediaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many property_medias.
   */
  data: Prisma.property_mediaCreateManyInput | Prisma.property_mediaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * property_media createManyAndReturn
 */
export type property_mediaCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the property_media
   */
  select?: Prisma.property_mediaSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the property_media
   */
  omit?: Prisma.property_mediaOmit<ExtArgs> | null
  /**
   * The data used to create many property_medias.
   */
  data: Prisma.property_mediaCreateManyInput | Prisma.property_mediaCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.property_mediaIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * property_media update
 */
export type property_mediaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the property_media
   */
  select?: Prisma.property_mediaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the property_media
   */
  omit?: Prisma.property_mediaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.property_mediaInclude<ExtArgs> | null
  /**
   * The data needed to update a property_media.
   */
  data: Prisma.XOR<Prisma.property_mediaUpdateInput, Prisma.property_mediaUncheckedUpdateInput>
  /**
   * Choose, which property_media to update.
   */
  where: Prisma.property_mediaWhereUniqueInput
}

/**
 * property_media updateMany
 */
export type property_mediaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update property_medias.
   */
  data: Prisma.XOR<Prisma.property_mediaUpdateManyMutationInput, Prisma.property_mediaUncheckedUpdateManyInput>
  /**
   * Filter which property_medias to update
   */
  where?: Prisma.property_mediaWhereInput
  /**
   * Limit how many property_medias to update.
   */
  limit?: number
}

/**
 * property_media updateManyAndReturn
 */
export type property_mediaUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the property_media
   */
  select?: Prisma.property_mediaSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the property_media
   */
  omit?: Prisma.property_mediaOmit<ExtArgs> | null
  /**
   * The data used to update property_medias.
   */
  data: Prisma.XOR<Prisma.property_mediaUpdateManyMutationInput, Prisma.property_mediaUncheckedUpdateManyInput>
  /**
   * Filter which property_medias to update
   */
  where?: Prisma.property_mediaWhereInput
  /**
   * Limit how many property_medias to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.property_mediaIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * property_media upsert
 */
export type property_mediaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the property_media
   */
  select?: Prisma.property_mediaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the property_media
   */
  omit?: Prisma.property_mediaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.property_mediaInclude<ExtArgs> | null
  /**
   * The filter to search for the property_media to update in case it exists.
   */
  where: Prisma.property_mediaWhereUniqueInput
  /**
   * In case the property_media found by the `where` argument doesn't exist, create a new property_media with this data.
   */
  create: Prisma.XOR<Prisma.property_mediaCreateInput, Prisma.property_mediaUncheckedCreateInput>
  /**
   * In case the property_media was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.property_mediaUpdateInput, Prisma.property_mediaUncheckedUpdateInput>
}

/**
 * property_media delete
 */
export type property_mediaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the property_media
   */
  select?: Prisma.property_mediaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the property_media
   */
  omit?: Prisma.property_mediaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.property_mediaInclude<ExtArgs> | null
  /**
   * Filter which property_media to delete.
   */
  where: Prisma.property_mediaWhereUniqueInput
}

/**
 * property_media deleteMany
 */
export type property_mediaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which property_medias to delete
   */
  where?: Prisma.property_mediaWhereInput
  /**
   * Limit how many property_medias to delete.
   */
  limit?: number
}

/**
 * property_media without action
 */
export type property_mediaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the property_media
   */
  select?: Prisma.property_mediaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the property_media
   */
  omit?: Prisma.property_mediaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.property_mediaInclude<ExtArgs> | null
}
